"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, currency, dateTime } from "@/lib/api";
import { clearAuth, getAuth } from "@/lib/auth";
import PosterUploader from "@/components/PosterUploader";
import type { AdminSeat, Auditorium, Booking, Cinema, Movie, Showtime, UserProfile } from "@/lib/types";

type Tab="movies"|"cinemas"|"auditoriums"|"showtimes"|"seats"|"users"|"bookings";
const emptyMovie={title:"",description:"",durationMinutes:120,posterUrl:"",rating:"T13",genre:"",language:"",trailerUrl:"",releaseDate:"",active:true};
const emptyUser={email:"",fullName:"",phone:"",role:"USER",newPassword:""};

export default function Admin(){
 const [tab,setTab]=useState<Tab>("movies"); const [movies,setMovies]=useState<Movie[]>([]); const [shows,setShows]=useState<Showtime[]>([]); const [bookings,setBookings]=useState<Booking[]>([]); const [cinemas,setCinemas]=useState<Cinema[]>([]); const [auditoriums,setAuditoriums]=useState<Auditorium[]>([]); const [seats,setSeats]=useState<AdminSeat[]>([]); const [users,setUsers]=useState<UserProfile[]>([]); const [msg,setMsg]=useState("");
 const [movie,setMovie]=useState({...emptyMovie}); const [movieId,setMovieId]=useState<string|null>(null);
 const [cinema,setCinema]=useState({name:"",address:""}); const [cinemaId,setCinemaId]=useState<string|null>(null);
 const [aud,setAud]=useState({cinemaId:"",name:""}); const [audId,setAudId]=useState<string|null>(null);
 const [show,setShow]=useState({movieId:"",auditoriumId:"",startTime:"",basePrice:90000,status:"OPEN"}); const [showId,setShowId]=useState<string|null>(null);
 const [seat,setSeat]=useState({auditoriumId:"",rowLabel:"A",seatNumber:1,seatType:"STANDARD",priceModifier:0}); const [seatId,setSeatId]=useState<string|null>(null);
 const [user,setUser]=useState({...emptyUser}); const [userId,setUserId]=useState<string|null>(null);
 async function load(){
  try{
   const me=await api<UserProfile>("/me");
   if(me.role!=="ADMIN"){
    clearAuth();
    location.href="/login?returnTo=/admin&reason=admin";
    return;
   }
   const [m,s,b,c,a,st,u]=await Promise.all([api<Movie[]>("/admin/movies"),api<Showtime[]>("/admin/showtimes"),api<Booking[]>("/admin/bookings"),api<Cinema[]>("/admin/cinemas"),api<Auditorium[]>("/admin/auditoriums"),api<AdminSeat[]>("/admin/seats"),api<UserProfile[]>("/admin/users")]);
   setMovies(m);setShows(s);setBookings(b);setCinemas(c);setAuditoriums(a);setSeats(st);setUsers(u);
  }catch(e){
   const message=(e as Error).message;
   if(message.includes("Phiên đăng nhập")){
    location.href="/login?returnTo=/admin&reason=expired";
    return;
   }
   setMsg(message);
  }
 }
 useEffect(()=>{
  const local=getAuth();
  if(!local){location.href="/login?returnTo=/admin&reason=required";return;}
  void load();
 },[]);
 const say=(v:string)=>{setMsg(v);setTimeout(()=>setMsg(""),3500)};
 async function remove(path:string,label:string){if(!confirm(`Xoá ${label}?`))return;try{await api(path,{method:"DELETE"});await load();say(`Đã xoá ${label}.`)}catch(e){say((e as Error).message)}}
 async function saveMovie(e:FormEvent){e.preventDefault();try{const body={...movie,posterUrl:movie.posterUrl||null,releaseDate:movie.releaseDate||null};await api(movieId?`/admin/movies/${movieId}`:"/admin/movies",{method:movieId?"PUT":"POST",body:JSON.stringify(body)});setMovie({...emptyMovie});setMovieId(null);await load();say("Đã lưu phim.")}catch(e){say((e as Error).message)}}
 async function saveCinema(e:FormEvent){e.preventDefault();try{await api(cinemaId?`/admin/cinemas/${cinemaId}`:"/admin/cinemas",{method:cinemaId?"PUT":"POST",body:JSON.stringify(cinema)});setCinema({name:"",address:""});setCinemaId(null);await load();say("Đã lưu rạp.")}catch(e){say((e as Error).message)}}
 async function saveAud(e:FormEvent){e.preventDefault();try{await api(audId?`/admin/auditoriums/${audId}`:"/admin/auditoriums",{method:audId?"PUT":"POST",body:JSON.stringify(aud)});setAud({cinemaId:"",name:""});setAudId(null);await load();say("Đã lưu phòng chiếu.")}catch(e){say((e as Error).message)}}
 async function generateSeats(auditoriumId:string){try{const r=await api<{created:number}>(`/admin/auditoriums/${auditoriumId}/generate-seats`,{method:"POST"});await load();say(`Đã tạo ${r.created} ghế mặc định cho phòng.`)}catch(e){say((e as Error).message)}}
 async function saveShow(e:FormEvent){e.preventDefault();try{const body={...show,startTime:new Date(show.startTime).toISOString(),basePrice:Number(show.basePrice)};await api(showId?`/admin/showtimes/${showId}`:"/admin/showtimes",{method:showId?"PUT":"POST",body:JSON.stringify(body)});setShow({movieId:"",auditoriumId:"",startTime:"",basePrice:90000,status:"OPEN"});setShowId(null);await load();say("Đã lưu suất chiếu.")}catch(e){say((e as Error).message)}}
 async function saveSeat(e:FormEvent){e.preventDefault();try{await api(seatId?`/admin/seats/${seatId}`:"/admin/seats",{method:seatId?"PUT":"POST",body:JSON.stringify({...seat,seatNumber:Number(seat.seatNumber),priceModifier:Number(seat.priceModifier)})});setSeat({auditoriumId:"",rowLabel:"A",seatNumber:1,seatType:"STANDARD",priceModifier:0});setSeatId(null);await load();say("Đã lưu ghế.")}catch(e){say((e as Error).message)}}
 async function saveUser(e:FormEvent){e.preventDefault();try{if(userId){await api(`/admin/users/${userId}`,{method:"PUT",body:JSON.stringify(user)})}else{await api("/admin/users",{method:"POST",body:JSON.stringify({email:user.email,fullName:user.fullName,phone:user.phone,role:user.role,password:user.newPassword})})}setUser({...emptyUser});setUserId(null);await load();say("Đã lưu người dùng.")}catch(e){say((e as Error).message)}}
 async function revokeUserSessions(id:string,email:string){if(!confirm(`Thu hồi toàn bộ phiên đăng nhập của ${email}?`))return;try{const r=await api<{revoked:number}>(`/admin/security/users/${id}/sessions`,{method:"DELETE"});say(`Đã thu hồi ${r.revoked} phiên của ${email}.`);if(getAuth()?.userId===id){clearAuth();location.href="/login?reason=expired"}}catch(e){say((e as Error).message)}}
 const title=useMemo(()=>({movies:"Phim",cinemas:"Rạp",auditoriums:"Phòng chiếu",showtimes:"Suất chiếu",seats:"Ghế",users:"Người dùng",bookings:"Booking"}[tab]),[tab]);
 return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Admin Dashboard</h1><p className="text-slate-400">Quản trị toàn bộ dữ liệu hệ thống.</p></div><div className="flex flex-wrap gap-2"><a href="/admin/bookings" className="btn btn-primary">🎫 Quản lý Booking</a><a href="/admin/analytics" className="btn btn-secondary">📊 Doanh thu</a><a href="/admin/staff" className="btn btn-secondary">👨‍💼 Nhân viên</a><a href="/admin/shifts" className="btn btn-secondary">🕒 Xếp ca</a><a href="/admin/attendance" className="btn btn-secondary">🧾 Bảng công & nghỉ phép</a><a href="/admin/vouchers" className="btn btn-secondary">🎟 Mã ưu đãi</a><a href="/admin/pricing" className="btn btn-secondary">💰 Giá vé động</a><a href="/admin/commerce" className="btn btn-secondary">🍿 Bắp nước & Voucher</a><a href="/admin/inventory" className="btn btn-secondary">📦 Kho bắp nước</a><a href="/admin/reviews" className="btn btn-secondary">⭐ Kiểm duyệt đánh giá</a><a href="/admin/refunds" className="btn btn-secondary">↩ Hoàn vé</a><a href="/admin/audit" className="btn btn-secondary">🛡 Audit log</a></div></div>
 <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Phim",movies.length],["Rạp",cinemas.length],["Phòng",auditoriums.length],["Suất",shows.length],["Ghế",seats.length],["User",users.length]].map(([k,v])=><div className="card p-4" key={String(k)}><div className="text-xs text-slate-400">{k}</div><div className="text-2xl font-bold">{v}</div></div>)}</div>
 <div className="flex flex-wrap gap-2">{(["movies","cinemas","auditoriums","showtimes","seats","users","bookings"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`btn ${tab===t?"btn-primary":"btn-secondary"}`}>{({movies:"Phim",cinemas:"Rạp",auditoriums:"Phòng",showtimes:"Suất chiếu",seats:"Ghế",users:"Người dùng",bookings:"Booking"} as Record<Tab,string>)[t]}</button>)}</div>
 {msg&&<div className="card p-4 text-sm">{msg}</div>}
 <h2 className="text-2xl font-bold">{title}</h2>
 {tab==="movies"&&<div className="grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={saveMovie} className="card p-5 space-y-3"><h3 className="font-bold">{movieId?"Sửa phim":"Thêm phim"}</h3><input className="input" placeholder="Tên phim" value={movie.title} onChange={e=>setMovie({...movie,title:e.target.value})} required/><textarea className="input" placeholder="Mô tả" value={movie.description} onChange={e=>setMovie({...movie,description:e.target.value})}/><input className="input" type="number" min={1} value={movie.durationMinutes} onChange={e=>setMovie({...movie,durationMinutes:Number(e.target.value)})}/><PosterUploader value={movie.posterUrl} onChange={posterUrl=>setMovie({...movie,posterUrl})}/><input className="input" placeholder="Phân loại độ tuổi (P, T13, T16...)" value={movie.rating} onChange={e=>setMovie({...movie,rating:e.target.value})}/><input className="input" placeholder="Thể loại, phân cách bằng dấu phẩy" value={movie.genre} onChange={e=>setMovie({...movie,genre:e.target.value})}/><input className="input" placeholder="Ngôn ngữ" value={movie.language} onChange={e=>setMovie({...movie,language:e.target.value})}/><input className="input" placeholder="URL trailer (YouTube...)" value={movie.trailerUrl} onChange={e=>setMovie({...movie,trailerUrl:e.target.value})}/><input className="input" type="date" value={movie.releaseDate} onChange={e=>setMovie({...movie,releaseDate:e.target.value})}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={movie.active} onChange={e=>setMovie({...movie,active:e.target.checked})}/> Đang hoạt động</label><button className="btn btn-primary w-full">Lưu</button>{movieId&&<button type="button" onClick={()=>{setMovieId(null);setMovie({...emptyMovie})}} className="btn btn-secondary w-full">Huỷ sửa</button>}</form><div className="space-y-3">{movies.map(m=><div key={m.id} className="card p-4 flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3">{m.posterUrl&&<img src={m.posterUrl} alt={m.title} className="h-20 w-14 shrink-0 rounded-lg border border-slate-700 object-cover"/>}<div className="min-w-0"><div className="font-bold">{m.title}</div><div className="text-sm text-slate-400">{m.durationMinutes} phút · {m.genre||"Chưa có thể loại"} · {m.rating||"-"} · {m.active?"Đang bật":"Đã ẩn"}</div></div></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>{setMovieId(m.id);setMovie({title:m.title,description:m.description||"",durationMinutes:m.durationMinutes,posterUrl:m.posterUrl||"",rating:m.rating||"",genre:m.genre||"",language:m.language||"",trailerUrl:m.trailerUrl||"",releaseDate:m.releaseDate||"",active:m.active})}}>Sửa</button><button className="btn btn-secondary" onClick={()=>remove(`/admin/movies/${m.id}`,m.title)}>Xoá/Ẩn</button></div></div>)}</div></div>}
 {tab==="cinemas"&&<div className="grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={saveCinema} className="card p-5 space-y-3"><input className="input" placeholder="Tên rạp" value={cinema.name} onChange={e=>setCinema({...cinema,name:e.target.value})} required/><input className="input" placeholder="Địa chỉ" value={cinema.address} onChange={e=>setCinema({...cinema,address:e.target.value})} required/><button className="btn btn-primary w-full">Lưu rạp</button></form><div className="space-y-3">{cinemas.map(c=><div key={c.id} className="card p-4 flex justify-between gap-3"><div><b>{c.name}</b><div className="text-sm text-slate-400">{c.address}</div></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>{setCinemaId(c.id);setCinema({name:c.name,address:c.address})}}>Sửa</button><button className="btn btn-secondary" onClick={()=>remove(`/admin/cinemas/${c.id}`,c.name)}>Xoá</button></div></div>)}</div></div>}
 {tab==="auditoriums"&&<div className="grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={saveAud} className="card p-5 space-y-3"><select className="input" value={aud.cinemaId} onChange={e=>setAud({...aud,cinemaId:e.target.value})} required><option value="">Chọn rạp</option>{cinemas.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" placeholder="Tên phòng" value={aud.name} onChange={e=>setAud({...aud,name:e.target.value})} required/><p className="text-xs leading-5 text-slate-400">Phòng mới sẽ tự tạo 80 ghế: A-D thường, E-G VIP, H ghế đôi.</p><button className="btn btn-primary w-full">Lưu phòng</button></form><div className="space-y-3">{auditoriums.map(a=>{const count=seats.filter(s=>s.auditoriumId===a.id).length;return <div key={a.id} className="card p-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b>{a.name}</b><div className="text-sm text-slate-400">{a.cinemaName} · {count} ghế</div></div><div className="flex flex-wrap gap-2">{count===0&&<button className="btn btn-primary" onClick={()=>generateSeats(a.id)}>Tạo sơ đồ 80 ghế</button>}<a className="btn btn-secondary" href={`/admin/seat-layout/${a.id}`}>Thiết kế ghế</a><button className="btn btn-secondary" onClick={()=>{setAudId(a.id);setAud({cinemaId:a.cinemaId,name:a.name})}}>Sửa</button><button className="btn btn-secondary" onClick={()=>remove(`/admin/auditoriums/${a.id}`,a.name)}>Xoá</button></div></div>})}</div></div>}
 {tab==="showtimes"&&<div className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={saveShow} className="card p-5 space-y-3"><select className="input" value={show.movieId} onChange={e=>setShow({...show,movieId:e.target.value})} required><option value="">Chọn phim</option>{movies.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select><select className="input" value={show.auditoriumId} onChange={e=>setShow({...show,auditoriumId:e.target.value})} required><option value="">Chọn phòng</option>{auditoriums.map(a=><option key={a.id} value={a.id}>{a.cinemaName} - {a.name}</option>)}</select><input className="input" type="datetime-local" value={show.startTime} onChange={e=>setShow({...show,startTime:e.target.value})} required/><input className="input" type="number" min={0} value={show.basePrice} onChange={e=>setShow({...show,basePrice:Number(e.target.value)})}/><select className="input" value={show.status} onChange={e=>setShow({...show,status:e.target.value})}><option>OPEN</option><option>CLOSED</option><option>CANCELLED</option></select><button className="btn btn-primary w-full">Lưu suất chiếu</button></form><div className="space-y-3">{shows.map(s=><div key={s.id} className="card p-4 flex justify-between gap-3"><div><b>{s.movieTitle}</b><div className="text-sm text-slate-400">{dateTime(s.startTime)} · {s.cinemaName}/{s.auditoriumName} · {currency(s.basePrice)} · {s.status}</div></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>{setShowId(s.id);const d=new Date(s.startTime);setShow({movieId:s.movieId,auditoriumId:s.auditoriumId,startTime:new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16),basePrice:s.basePrice,status:s.status})}}>Sửa</button><button className="btn btn-secondary" onClick={()=>remove(`/admin/showtimes/${s.id}`,"suất chiếu")}>Xoá</button></div></div>)}</div></div>}
 {tab==="seats"&&<div className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={saveSeat} className="card p-5 space-y-3"><select className="input" value={seat.auditoriumId} onChange={e=>setSeat({...seat,auditoriumId:e.target.value})} required><option value="">Chọn phòng</option>{auditoriums.map(a=><option key={a.id} value={a.id}>{a.cinemaName} - {a.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input className="input" value={seat.rowLabel} onChange={e=>setSeat({...seat,rowLabel:e.target.value})} placeholder="Hàng A"/><input className="input" type="number" min={1} value={seat.seatNumber} onChange={e=>setSeat({...seat,seatNumber:Number(e.target.value)})}/></div><select className="input" value={seat.seatType} onChange={e=>setSeat({...seat,seatType:e.target.value})}><option>STANDARD</option><option>VIP</option><option>COUPLE</option><option>ACCESSIBLE</option><option>BLOCKED</option></select><input className="input" type="number" min={0} value={seat.priceModifier} onChange={e=>setSeat({...seat,priceModifier:Number(e.target.value)})} placeholder="Phụ thu"/><button className="btn btn-primary w-full">Lưu ghế</button></form><div className="max-h-[650px] overflow-auto space-y-2">{seats.map(s=><div key={s.id} className="card p-3 flex justify-between"><div><b>{s.rowLabel}{s.seatNumber}</b> · {s.seatType}<div className="text-xs text-slate-400">{s.auditoriumName} · +{currency(s.priceModifier)}</div></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>{setSeatId(s.id);setSeat({auditoriumId:s.auditoriumId,rowLabel:s.rowLabel,seatNumber:s.seatNumber,seatType:s.seatType,priceModifier:s.priceModifier})}}>Sửa</button><button className="btn btn-secondary" onClick={()=>remove(`/admin/seats/${s.id}`,`ghế ${s.rowLabel}${s.seatNumber}`)}>Xoá</button></div></div>)}</div></div>}
 {tab==="users"&&<div className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={saveUser} className="card p-5 space-y-3"><input className="input" type="email" value={user.email} onChange={e=>setUser({...user,email:e.target.value})} placeholder="Email" required/><input className="input" value={user.fullName} onChange={e=>setUser({...user,fullName:e.target.value})} placeholder="Họ tên" required/><input className="input" value={user.phone} onChange={e=>setUser({...user,phone:e.target.value})} placeholder="Số điện thoại"/><select className="input" value={user.role} onChange={e=>setUser({...user,role:e.target.value})}><option>USER</option><option>ADMIN</option></select><input className="input" type="password" minLength={userId?0:8} value={user.newPassword} onChange={e=>setUser({...user,newPassword:e.target.value})} placeholder={userId?"Mật khẩu mới (để trống nếu không đổi)":"Mật khẩu tối thiểu 8 ký tự"} required={!userId}/><button className="btn btn-primary w-full">Lưu người dùng</button></form><div className="space-y-3">{users.map(u=><div key={u.id} className="card p-4 flex justify-between gap-3"><div><b>{u.fullName}</b><div className="text-sm text-slate-400">{u.email} · {u.phone||"-"} · {u.role}</div></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>{setUserId(u.id);setUser({email:u.email,fullName:u.fullName,phone:u.phone||"",role:u.role,newPassword:""})}}>Sửa</button><button className="btn btn-secondary" onClick={()=>revokeUserSessions(u.id,u.email)}>Đăng xuất all</button><button className="btn btn-secondary" onClick={()=>remove(`/admin/users/${u.id}`,u.email)}>Xoá</button></div></div>)}</div></div>}
 {tab==="bookings"&&<div className="space-y-4"><div className="card flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="text-xl font-black">Booking Operations V13</h3><p className="text-sm text-slate-400">Chi tiết khách, payment, QR, check-in, refund và audit được gom vào một màn hình quản trị.</p></div><a href="/admin/bookings" className="btn btn-primary">Mở quản lý Booking →</a></div><div className="card p-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-400"><th className="p-2">Phim</th><th className="p-2">Ngày tạo</th><th className="p-2">Trạng thái</th><th className="p-2">Ghế</th><th className="p-2">Tổng</th><th className="p-2">Thao tác</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id} className="border-t border-slate-800"><td className="p-2">{b.movieTitle}</td><td className="p-2">{dateTime(b.createdAt)}</td><td className="p-2">{b.status}</td><td className="p-2">{b.seats.map(s=>s.code).join(", ")}</td><td className="p-2">{currency(b.totalAmount)}</td><td className="p-2"><a className="btn btn-secondary" href={`/admin/bookings?booking=${b.id}`}>Quản lý</a></td></tr>)}</tbody></table></div></div>}
 </div>
}
