"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, currency, dateTime } from "@/lib/api";
import type { ConcessionProduct, Voucher } from "@/lib/types";
import { concessionProductPresentation } from "@/lib/concession-presentation";
import { usePresentationLanguage } from "@/lib/usePresentationLanguage";

export default function PromotionsPage(){
 const { language, t }=usePresentationLanguage();
 const [vouchers,setVouchers]=useState<Voucher[]>([]); const [products,setProducts]=useState<ConcessionProduct[]>([]);
 useEffect(()=>{Promise.all([api<Voucher[]>("/commerce/vouchers"),api<ConcessionProduct[]>("/commerce/products")]).then(([v,p])=>{setVouchers(v);setProducts(p)}).catch(()=>{});},[]);
 return <div className="space-y-9">
  <div className="section-heading"><div><p className="section-kicker">{t("ƯU ĐÃI CINEBOOKING","CINEBOOKING OFFERS")}</p><h1>{t("Ưu đãi & dịch vụ","Offers & services")}</h1><p className="mt-2 max-w-2xl text-slate-400">{t("Dùng mã ưu đãi, điểm thành viên và chọn thêm bắp nước ngay trong bước đặt ghế.","Use vouchers and loyalty points, and add snacks and drinks while selecting seats.")}</p></div></div>
  <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-2xl font-bold">{t("Mã ưu đãi đang dùng được","Available vouchers")}</h2><p className="mt-1 text-sm text-slate-400">{t("Nhập mã tại phần Đơn hàng khi chọn ghế.","Enter the code in the Order section while selecting seats.")}</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{vouchers.map(v=><article key={v.id} className="promo-card promo-one"><small>{t("MÃ ƯU ĐÃI","VOUCHER")}</small><h3>{v.code}</h3><p className="!text-white" data-i18n-skip="true"><b>{v.name}</b></p><p className="mt-2">{v.discountType==="PERCENT"?t(`Giảm ${v.discountValue}%`,`Save ${v.discountValue}%`):t(`Giảm ${currency(v.discountValue)}`,`Save ${currency(v.discountValue)}`)} {t("cho đơn từ","on orders from")} {currency(v.minOrderAmount)}{v.maxDiscount?t(`, tối đa ${currency(v.maxDiscount)}`,`, up to ${currency(v.maxDiscount)}`):""}.</p>{v.endsAt&&<p className="mt-2 text-xs">{t("Hạn","Expires")}: {dateTime(v.endsAt)}</p>}</article>)}{!vouchers.length&&<div className="card p-6 text-slate-400">{t("Hiện chưa có mã ưu đãi công khai.","There are no public vouchers at the moment.")}</div>}</div></section>
  <section><div className="mb-4"><h2 className="text-2xl font-bold">{t("Bắp nước","Snacks & drinks")}</h2><p className="mt-1 text-sm text-slate-400">{t("Bắp nước/combo được cộng trực tiếp vào đơn vé.","Snacks, drinks, and combos are added directly to the ticket order.")}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=>{const copy=concessionProductPresentation(p.name,p.description,language);return <article key={p.id} className="card p-5"><div className="text-4xl">🍿</div><h3 data-testid="promotion-concession-name-r5" className="mt-3 text-lg font-bold">{copy.name}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-slate-400">{copy.description}</p><div className="mt-3 text-xl font-black text-amber-300">{currency(p.price)}</div></article>})}</div></section>
  <section className="grid gap-5 md:grid-cols-3"><article className="card p-6"><div className="text-4xl">💎</div><h2 className="mt-4 text-xl font-bold">{t("Điểm thành viên","Loyalty points")}</h2><p className="mt-2 leading-7 text-slate-400">{t("Mỗi 10.000 ₫ thanh toán thành công nhận 1 điểm. Khi đặt vé, 1 điểm đổi 100 ₫, tối đa 30% giá trị sau mã ưu đãi.","Earn 1 point for every 10,000 ₫ of successful payments. During booking, 1 point redeems 100 ₫, up to 30% of the amount after the voucher.")}</p></article><article className="card p-6"><div className="text-4xl">🔔</div><h2 className="mt-4 text-xl font-bold">{t("Thông báo giao dịch","Transaction notifications")}</h2><p className="mt-2 leading-7 text-slate-400">{t("Nhận thông báo khi thanh toán thành công, lượt đặt vé hết hạn hoặc bị hủy.","Receive notifications when payment succeeds or when a booking expires or is cancelled.")}</p></article><article className="card p-6"><div className="text-4xl">📲</div><h2 className="mt-4 text-xl font-bold">{t("Vé QR điện tử","Digital QR ticket")}</h2><p className="mt-2 leading-7 text-slate-400">{t("Sau thanh toán, QR vé được lưu trong tài khoản để mở nhanh khi vào rạp.","After payment, the ticket QR is saved to your account for quick access at the cinema.")}</p></article></section>
  <div className="card flex flex-col items-start justify-between gap-4 p-6 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold">{t("Sẵn sàng chọn suất chiếu?","Ready to choose a showtime?")}</h2><p className="mt-1 text-slate-400">{t("Xem phim đang chiếu và áp dụng ưu đãi ngay khi đặt.","Browse now-showing movies and apply offers when booking.")}</p></div><Link className="btn btn-primary" href="/movies">{t("Xem phim","Browse movies")}</Link></div>
 </div>
}
