"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, currency, dateTime } from "@/lib/api";
import type { PaymentHistoryItem } from "@/lib/types";

const statuses=["ALL","PENDING","SUCCESS","FAILED","EXPIRED","REVIEW","REFUNDED"];
function badge(status:string){return status==="SUCCESS"?"border-emerald-700 bg-emerald-950 text-emerald-200":status==="PENDING"?"border-amber-700 bg-amber-950 text-amber-200":status==="REVIEW"?"border-violet-700 bg-violet-950 text-violet-200":status==="REFUNDED"?"border-cyan-800 bg-cyan-950 text-cyan-200":"border-slate-700 bg-slate-900 text-slate-300"}

export default function PaymentsPage(){
 const [items,setItems]=useState<PaymentHistoryItem[]>([]);const [loading,setLoading]=useState(true);const [status,setStatus]=useState("ALL");const [q,setQ]=useState("");const [msg,setMsg]=useState("");
 const load=useCallback(async()=>{setLoading(true);setMsg("");try{setItems(await api<PaymentHistoryItem[]>("/payments/history"));}catch(e){setMsg((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const query=q.trim().toLowerCase();return items.filter(x=>(status==="ALL"||x.status===status)&&(!query||x.movieTitle.toLowerCase().includes(query)||x.bookingId.toLowerCase().includes(query)||x.paymentId.toLowerCase().includes(query)||x.provider.toLowerCase().includes(query)))},[items,status,q]);
 const summary=useMemo(()=>({success:items.filter(x=>x.status==="SUCCESS").reduce((s,x)=>s+x.amount,0),pending:items.filter(x=>x.status==="PENDING").length,review:items.filter(x=>x.status==="REVIEW").length,total:items.length}),[items]);
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.25em] text-rose-400">Payment Center · V38</div><h1 className="text-3xl font-black">Lịch sử thanh toán</h1><p className="mt-2 text-slate-400">Theo dõi payment theo người thanh toán, kể cả sau khi vé đã được chuyển/tặng cho tài khoản khác.</p></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={load} disabled={loading}>↻ Làm mới</button><Link href="/bookings" className="btn btn-primary">Vé của tôi</Link></div></div>
 {msg&&<div className="card border border-rose-500/30 p-4 text-sm text-rose-200">{msg}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="card p-4"><div className="text-xs text-slate-400">Tổng giao dịch</div><div className="text-2xl font-black">{summary.total}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Đã thanh toán</div><div className="text-2xl font-black text-emerald-300">{currency(summary.success)}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Đang chờ</div><div className="text-2xl font-black text-amber-300">{summary.pending}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Cần đối soát</div><div className="text-2xl font-black text-violet-300">{summary.review}</div></div></div>
 <div className="card grid gap-3 p-4 md:grid-cols-[1fr_220px]"><input className="input" placeholder="Phim, booking, payment, provider..." value={q} onChange={e=>setQ(e.target.value)}/><select className="input" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="space-y-3">{loading?<div className="card p-8 text-center text-slate-400">Đang tải payment...</div>:filtered.map(p=><article className="card p-5" key={p.paymentId}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><b>{p.movieTitle}</b><span className={`rounded-full border px-2 py-1 text-xs font-black ${badge(p.status)}`}>{p.status}</span><span className="rounded-full border border-slate-700 px-2 py-1 text-xs">{p.provider}</span></div><div className="mt-2 text-sm text-slate-400">Tạo {dateTime(p.createdAt)}{p.paidAt?` · Thanh toán ${dateTime(p.paidAt)}`:""}</div></div><div className="text-right"><div className="text-xl font-black">{currency(p.amount)}</div>{p.refundedAmount!=null&&<div className="text-sm font-bold text-cyan-300">Đã hoàn {currency(p.refundedAmount)}</div>}</div></div><div className="mt-4 grid gap-2 text-xs text-slate-400 md:grid-cols-2"><div className="break-all">Payment: {p.paymentId}</div><div className="break-all">Booking: {p.bookingId}</div>{p.providerOrderId&&<div className="break-all">Merchant order: {p.providerOrderId}</div>}{p.providerTransactionId&&<div className="break-all">Gateway transaction: {p.providerTransactionId}</div>}{p.providerResponseCode&&<div>Gateway code: {p.providerResponseCode}</div>}{p.refundReference&&<div className="break-all">Refund reference: {p.refundReference}</div>}{p.providerMessage&&<div className="md:col-span-2">{p.providerMessage}</div>}</div><div className="mt-4 flex flex-wrap gap-2"><Link className="btn btn-secondary !px-3 !py-2" href={`/bookings`}>Mở booking</Link>{p.status==="REVIEW"&&<span className="rounded-xl border border-violet-700/60 bg-violet-950/40 px-3 py-2 text-xs text-violet-200">Không thanh toán lại; chờ Admin đối soát.</span>}</div></article>)}{!loading&&filtered.length===0&&<div className="card p-8 text-center text-slate-500">Không có giao dịch phù hợp.</div>}</div>
 </div>
}
