"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, currency, dateTime } from "@/lib/api";
import type { PaymentEventItem, PaymentHistoryItem, PaymentProviderAvailability, PaymentStart } from "@/lib/types";

const statuses=["ALL","PENDING","SUCCESS","FAILED","EXPIRED","CANCELLED","REVIEW","REFUNDED"];
function badge(status:string){return status==="SUCCESS"?"border-emerald-700 bg-emerald-950 text-emerald-200":status==="PENDING"?"border-amber-700 bg-amber-950 text-amber-200":status==="REVIEW"?"border-violet-700 bg-violet-950 text-violet-200":status==="REFUNDED"?"border-cyan-800 bg-cyan-950 text-cyan-200":status==="CANCELLED"?"border-slate-700 bg-slate-950 text-slate-300":"border-rose-800 bg-rose-950 text-rose-200"}
function baseProvider(provider:string){return provider.startsWith("VNPAY")?"VNPAY":provider.startsWith("MOMO")?"MOMO":provider;}

export default function PaymentsPage(){
 const [items,setItems]=useState<PaymentHistoryItem[]>([]);const [providers,setProviders]=useState<PaymentProviderAvailability[]>([]);const [loading,setLoading]=useState(true);const [status,setStatus]=useState("ALL");const [q,setQ]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState("");const [timelineId,setTimelineId]=useState("");const [timeline,setTimeline]=useState<PaymentEventItem[]>([]);
 const load=useCallback(async()=>{setLoading(true);setMsg("");try{const [history,available]=await Promise.all([api<PaymentHistoryItem[]>("/payments/history"),api<PaymentProviderAvailability[]>("/payments/providers")]);setItems(history);setProviders(available);}catch(e){setMsg((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const query=q.trim().toLowerCase();return items.filter(x=>(status==="ALL"||x.status===status)&&(!query||x.movieTitle.toLowerCase().includes(query)||x.bookingId.toLowerCase().includes(query)||x.paymentId.toLowerCase().includes(query)||x.provider.toLowerCase().includes(query)))},[items,status,q]);
 const summary=useMemo(()=>({success:items.filter(x=>x.status==="SUCCESS").reduce((s,x)=>s+x.amount,0),pending:items.filter(x=>x.status==="PENDING").length,review:items.filter(x=>x.status==="REVIEW").length,total:items.length}),[items]);
 function enabled(provider:string){return Boolean(providers.find(x=>x.provider===baseProvider(provider))?.enabled)}
 function retryProvider(p:PaymentHistoryItem){if(enabled(p.provider))return p.provider;const first=providers.find(x=>x.enabled);return first?.provider||""}
 async function cancelPayment(p:PaymentHistoryItem){setBusy(p.paymentId);setMsg("");try{await api(`/payments/${p.paymentId}/cancel`,{method:"POST"});setMsg(`Đã hủy lần thanh toán #${p.attemptNo}. Booking vẫn được giữ đến khi hết hạn.`);await load();}catch(e){setMsg((e as Error).message)}finally{setBusy("")}}
 async function retryPayment(p:PaymentHistoryItem){const provider=retryProvider(p);if(!provider){setMsg("Không có cổng thanh toán nào đang được bật để thử lại.");return;}setBusy(p.paymentId);setMsg("");try{const key=`retry-${p.paymentId}-${Date.now()}`;const r=await api<PaymentStart>(`/payments/${p.paymentId}/retry`,{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({provider})});location.href=r.paymentUrl;}catch(e){setMsg((e as Error).message);setBusy("")}}
 async function showTimeline(paymentId:string){if(timelineId===paymentId){setTimelineId("");setTimeline([]);return;}setBusy(paymentId);setMsg("");try{setTimeline(await api<PaymentEventItem[]>(`/payments/${paymentId}/timeline`));setTimelineId(paymentId);}catch(e){setMsg((e as Error).message)}finally{setBusy("")}}
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.25em] text-rose-400">Payment Center · V47</div><h1 className="text-3xl font-black">Lịch sử thanh toán</h1><p className="mt-2 text-slate-400">Theo dõi từng lần thanh toán, thử lại an toàn và xem timeline sự kiện mà không tạo dữ liệu VNPay/MoMo khi gateway chưa được cấu hình.</p></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={load} disabled={loading}>↻ Làm mới</button><Link href="/bookings" className="btn btn-primary">Vé của tôi</Link></div></div>
 {msg&&<div className="card border border-amber-500/30 p-4 text-sm">{msg}</div>}
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="card p-4"><div className="text-xs text-slate-400">Tổng giao dịch</div><div className="text-2xl font-black">{summary.total}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Đã thanh toán</div><div className="text-2xl font-black text-emerald-300">{currency(summary.success)}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Đang chờ</div><div className="text-2xl font-black text-amber-300">{summary.pending}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Cần đối soát</div><div className="text-2xl font-black text-violet-300">{summary.review}</div></div></div>
 <section className="card p-4"><div className="text-sm font-bold">Cổng đang khả dụng</div><div className="mt-2 flex flex-wrap gap-2">{providers.map(p=><span key={p.provider} className={`rounded-full border px-3 py-1 text-xs ${p.enabled?"border-emerald-700 text-emerald-200":"border-slate-700 text-slate-500"}`}>{p.displayName} · {p.enabled?p.mode:"chưa cấu hình"}</span>)}</div></section>
 <div className="card grid gap-3 p-4 md:grid-cols-[1fr_220px]"><input className="input" placeholder="Phim, booking, payment, provider..." value={q} onChange={e=>setQ(e.target.value)}/><select className="input" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="space-y-3">{loading?<div className="card p-8 text-center text-slate-400">Đang tải payment...</div>:filtered.map(p=><article className="card p-5" key={p.paymentId}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><b>{p.movieTitle}</b><span className={`rounded-full border px-2 py-1 text-xs font-black ${badge(p.status)}`}>{p.status}</span><span className="rounded-full border border-slate-700 px-2 py-1 text-xs">{p.provider}</span><span className="rounded-full border border-slate-700 px-2 py-1 text-xs">Lần #{p.attemptNo}</span></div><div className="mt-2 text-sm text-slate-400">Tạo {dateTime(p.createdAt)}{p.paidAt?` · Thanh toán ${dateTime(p.paidAt)}`:""}{p.cancelledAt?` · Hủy ${dateTime(p.cancelledAt)}`:""}</div></div><div className="text-right"><div className="text-xl font-black">{currency(p.amount)}</div>{p.refundedAmount!=null&&<div className="text-sm font-bold text-cyan-300">Đã hoàn {currency(p.refundedAmount)}</div>}{p.refundReference&&<div className="mt-1 text-xs text-cyan-200">Refund reference: {p.refundReference}</div>}</div></div><div className="mt-4 grid gap-2 text-xs text-slate-400 md:grid-cols-2"><div className="break-all">Payment: {p.paymentId}</div><div className="break-all">Booking: {p.bookingId}</div><div>Merchant order: {p.providerOrderId||"—"}</div><div>Gateway txn: {p.providerTransactionId||"—"}</div><div>Response: {p.providerResponseCode||"—"}</div><div>Đối soát lỗi: {p.reconciliationFailures||0}</div></div>{p.providerMessage&&<div className="mt-3 rounded-xl bg-slate-950 p-3 text-sm text-slate-300">{p.providerMessage}</div>}<div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-secondary !px-3 !py-2" onClick={()=>showTimeline(p.paymentId)} disabled={busy===p.paymentId}>{timelineId===p.paymentId?"Ẩn timeline":"Xem timeline"}</button>{p.status==="PENDING"&&<button className="btn btn-secondary !px-3 !py-2" onClick={()=>cancelPayment(p)} disabled={busy===p.paymentId}>Hủy lần thanh toán</button>}{(p.status==="FAILED"||p.status==="CANCELLED")&&<button className="btn btn-primary !px-3 !py-2" onClick={()=>retryPayment(p)} disabled={busy===p.paymentId||!retryProvider(p)}>Thử lại thanh toán</button>}</div>{timelineId===p.paymentId&&<div className="mt-4 space-y-2 border-t border-slate-800 pt-4">{timeline.map(e=><div key={e.id} className="grid gap-1 rounded-xl bg-slate-950 p-3 text-xs md:grid-cols-[180px_1fr]"><div className="text-slate-500">{dateTime(e.createdAt)}</div><div><b>{e.eventType}</b> · {e.actorType}{e.actorRef?` (${e.actorRef})`:""}<div className="mt-1 text-slate-400">{e.fromStatus||"—"} → {e.toStatus||"—"} · {e.code||"—"}</div>{e.message&&<div className="mt-1 text-slate-300">{e.message}</div>}</div></div>)}{!timeline.length&&<div className="text-sm text-slate-500">Chưa có event.</div>}</div>}</article>)}{!loading&&!filtered.length&&<div className="card p-8 text-center text-slate-500">Không có giao dịch phù hợp.</div>}</div>
 </div>
}
