"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { api, currency, dateTime } from "@/lib/api";
import type { PaymentOpsDashboard, PaymentReconciliationResult } from "@/lib/types";

function badge(status:string){return status==="SUCCESS"?"text-emerald-300":status==="PENDING"?"text-amber-300":status==="REVIEW"?"text-violet-300":status==="FAILED"||status==="EXPIRED"?"text-rose-300":"text-slate-300"}
export default function AdminPayments(){
 const [data,setData]=useState<PaymentOpsDashboard|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [msg,setMsg]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{setData(await api<PaymentOpsDashboard>("/admin/payments"));}catch(e){setMsg((e as Error).message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 async function reconcile(id:string){setBusy(id);setMsg("");try{const r=await api<PaymentReconciliationResult>(`/admin/payments/${id}/reconcile`,{method:"POST"});setMsg(`Đối soát ${r.provider}: local=${r.localStatus}, provider=${r.providerStatus}. ${r.message}`);await load();}catch(e){setMsg((e as Error).message)}finally{setBusy("")}}
 if(loading&&!data)return <div className="card p-8 text-slate-400">Đang tải Payment Operations...</div>;
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.25em] text-rose-400">Payment Operations · V37</div><h1 className="text-3xl font-black">Đối soát thanh toán</h1><p className="mt-2 text-slate-400">Theo dõi payment, IPN, chữ ký và đối soát trạng thái trực tiếp với VNPay/MoMo.</p></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={load}>↻ Làm mới</button><Link href="/admin" className="btn btn-secondary">← Dashboard</Link></div></div>
 {msg&&<div className="card border border-amber-500/30 p-4 text-sm">{msg}</div>}
 {data&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[["Total",data.total],["Pending",data.pending],["Success",data.success],["Failed",data.failed],["Expired",data.expired],["Review",data.review],["Refunded",data.refunded],["Invalid IPN",data.invalidWebhooks]].map(([label,value])=><div className="card p-4" key={String(label)}><div className="text-xs text-slate-400">{label}</div><div className="text-2xl font-black">{value}</div></div>)}</div>
 <section className="card overflow-x-auto p-3"><div className="p-3"><h2 className="text-xl font-black">200 payment gần nhất</h2><p className="text-sm text-slate-500">REVIEW là giao dịch cần kiểm tra trước khi refund/cập nhật thủ công.</p></div><table className="w-full min-w-[1250px] text-sm"><thead><tr className="text-left text-slate-400"><th className="p-3">Payment</th><th className="p-3">Provider</th><th className="p-3">Status</th><th className="p-3">Amount</th><th className="p-3">Merchant / Gateway</th><th className="p-3">Response</th><th className="p-3">Time</th><th className="p-3">Action</th></tr></thead><tbody>{data.payments.map(p=><tr className="border-t border-slate-800 align-top" key={p.id}><td className="p-3"><div className="font-mono text-xs">{p.id.slice(0,12)}</div><div className="mt-1 font-mono text-[10px] text-slate-500">booking {p.bookingId.slice(0,12)}</div></td><td className="p-3 font-bold">{p.provider}</td><td className={`p-3 font-black ${badge(p.status)}`}>{p.status}</td><td className="p-3 font-bold">{currency(p.amount)}</td><td className="p-3 text-xs"><div className="break-all">order: {p.providerOrderId||"-"}</div><div className="mt-1 break-all text-slate-500">txn: {p.providerTransactionId||"-"}</div></td><td className="p-3 text-xs"><b>{p.responseCode||"-"}</b><div className="mt-1 max-w-sm text-slate-400">{p.message||"-"}</div></td><td className="p-3 text-xs">{dateTime(p.createdAt)}{p.lastWebhookAt&&<div className="mt-1 text-slate-500">IPN {dateTime(p.lastWebhookAt)}</div>}</td><td className="p-3">{(p.provider.startsWith("VNPAY")||p.provider.startsWith("MOMO"))?<button className="btn btn-secondary !px-3 !py-2" disabled={busy===p.id} onClick={()=>reconcile(p.id)}>{busy===p.id?"Đang hỏi gateway...":"Đối soát"}</button>:<span className="text-xs text-slate-500">Local</span>}</td></tr>)}</tbody></table></section>
 <section className="card overflow-x-auto p-3"><div className="p-3"><h2 className="text-xl font-black">Webhook / IPN gần nhất</h2><p className="text-sm text-slate-500">{data.webhookEvents} event gần đây · chữ ký không hợp lệ: {data.invalidWebhooks}</p></div><table className="w-full min-w-[1100px] text-sm"><thead><tr className="text-left text-slate-400"><th className="p-3">Provider</th><th className="p-3">Signature</th><th className="p-3">Event key</th><th className="p-3">Result</th><th className="p-3">Merchant response</th><th className="p-3">Received</th></tr></thead><tbody>{data.webhooks.map(e=><tr className="border-t border-slate-800" key={e.id}><td className="p-3 font-bold">{e.provider}</td><td className={`p-3 font-black ${e.signatureValid?"text-emerald-300":"text-rose-300"}`}>{e.signatureValid?"VALID":"INVALID"}</td><td className="p-3 max-w-sm break-all font-mono text-xs">{e.eventKey}</td><td className="p-3">{e.resultCode||"-"}</td><td className="p-3"><b>{e.responseCode||"-"}</b><div className="text-xs text-slate-500">{e.responseMessage||""}</div></td><td className="p-3 text-xs">{dateTime(e.receivedAt)}</td></tr>)}</tbody></table></section></>}
 </div>
}
