"use client";
import { useEffect, useState } from "react";
import { api, dateTime } from "@/lib/api";
import type { AdminSecurityAlertV46, AdminSecuritySummaryV46 } from "@/lib/types";

export default function AdminSecurity(){
 const [summary,setSummary]=useState<AdminSecuritySummaryV46|null>(null);const [alerts,setAlerts]=useState<AdminSecurityAlertV46[]>([]);const [msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{try{const [s,a]=await Promise.all([api<AdminSecuritySummaryV46>("/admin/security/overview"),api<AdminSecurityAlertV46[]>("/admin/security/alerts")]);setSummary(s);setAlerts(a);}catch(e){setMsg((e as Error).message);}})();},[]);
 return <div className="mx-auto max-w-7xl space-y-6 px-4 py-8"><div><p className="section-kicker">V46 · SECURITY OPERATIONS</p><h1 className="text-3xl font-black">Security Operations</h1><p className="mt-2 text-slate-400">Giám sát cảnh báo tài khoản, brute-force và thiết bị mới trên toàn hệ thống.</p></div>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Cảnh báo 24h',summary?.alertsLast24Hours||0],['Chưa xác nhận',summary?.unacknowledgedAlerts||0],['Rủi ro cao',summary?.unacknowledgedHighRisk||0],['Thiết bị tin cậy active',summary?.activeTrustedDevices||0]].map(([k,v])=><div className="card p-5" key={String(k)}><div className="text-xs font-bold uppercase text-slate-500">{k}</div><div className="mt-2 text-3xl font-black">{v}</div></div>)}</section>
 <section className="card overflow-x-auto p-5"><table className="w-full min-w-[900px] text-sm"><thead><tr className="text-left text-slate-500"><th className="p-2">Thời gian</th><th className="p-2">Tài khoản</th><th className="p-2">Sự kiện</th><th className="p-2">Mức</th><th className="p-2">Risk</th><th className="p-2">Thiết bị</th><th className="p-2">IP</th><th className="p-2">Trạng thái</th></tr></thead><tbody>{alerts.map(a=><tr data-testid="admin-security-alert" key={a.id} className="border-t border-slate-800"><td className="p-2">{dateTime(a.createdAt)}</td><td className="p-2"><b>{a.userName}</b><div className="text-xs text-slate-500">{a.userEmail}</div></td><td className="p-2"><b>{a.title}</b><div className="text-xs text-slate-500">{a.eventType}</div></td><td className="p-2">{a.severity}</td><td className="p-2 font-black">{a.riskScore}</td><td className="p-2">{a.deviceName||'—'}</td><td className="p-2">{a.ipAddress||'—'}</td><td className="p-2">{a.acknowledgedAt?'Đã xác nhận':'Cần kiểm tra'}</td></tr>)}</tbody></table>{!alerts.length&&<div className="py-8 text-center text-slate-500">Chưa có cảnh báo.</div>}</section>{msg&&<div className="card p-4 text-sm">{msg}</div>}</div>;
}
