"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, dateTime } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import type { Booking, SupportCase, SupportCaseEvent } from "@/lib/types";

const EMPTY={bookingId:"",category:"BOOKING",subject:"",description:""};
export default function SupportPage(){
  const [cases,setCases]=useState<SupportCase[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [form,setForm]=useState({...EMPTY});const [selected,setSelected]=useState<string|null>(null);const [events,setEvents]=useState<SupportCaseEvent[]>([]);const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!getAuth()){location.href="/login?returnTo=/support";return;}Promise.all([api<SupportCase[]>("/support/cases"),api<Booking[]>("/bookings/me")]).then(([c,b])=>{setCases(c);setBookings(b)}).catch(e=>setError((e as Error).message));},[]);
  async function refresh(){setCases(await api<SupportCase[]>("/support/cases"));if(selected)setEvents(await api<SupportCaseEvent[]>(`/support/cases/${selected}/events`));}
  async function create(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const c=await api<SupportCase>("/support/cases",{method:"POST",body:JSON.stringify({...form,bookingId:form.bookingId||null})});setForm({...EMPTY});setSelected(c.id);await refresh();setEvents(await api<SupportCaseEvent[]>(`/support/cases/${c.id}/events`));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function open(c:SupportCase){setSelected(c.id);setEvents(await api<SupportCaseEvent[]>(`/support/cases/${c.id}/events`));}
  async function send(){if(!selected||!message.trim())return;setBusy(true);try{await api(`/support/cases/${selected}/messages`,{method:"POST",body:JSON.stringify({message})});setMessage("");await refresh();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const current=cases.find(c=>c.id===selected);
  return <div className="mx-auto max-w-7xl space-y-7"><div><p className="section-kicker">V45 · CUSTOMER SUPPORT & SERVICE RECOVERY 2.0</p><h1 className="text-3xl font-bold">Trung tâm hỗ trợ khách hàng</h1><p className="mt-2 text-slate-400">Tạo yêu cầu gắn booking, theo dõi SLA và trao đổi trực tiếp với đội vận hành CineBooking.</p></div>{error&&<div className="rounded-xl border border-red-800 bg-red-950/30 p-4 text-red-200">{error}</div>}
  <div className="grid gap-6 xl:grid-cols-[390px_1fr]"><form onSubmit={create} className="card space-y-3 p-5"><h2 className="text-xl font-bold">Tạo yêu cầu mới</h2><select aria-label="Booking hỗ trợ" className="input" value={form.bookingId} onChange={e=>setForm({...form,bookingId:e.target.value})}><option value="">Không gắn booking</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.movieTitle} · {dateTime(b.showtimeStart)} · {b.id.slice(0,8)}</option>)}</select><select aria-label="Loại hỗ trợ" className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["BOOKING","PAYMENT","REFUND","TICKET","CINEMA_EXPERIENCE","STAFF","OTHER"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Tiêu đề hỗ trợ" className="input" placeholder="Tiêu đề yêu cầu" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/><textarea aria-label="Mô tả hỗ trợ" className="input min-h-32" placeholder="Mô tả chi tiết vấn đề" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/><button className="btn btn-primary w-full" disabled={busy}>{busy?"Đang gửi...":"Gửi yêu cầu hỗ trợ"}</button></form>
  <section className="card p-5"><h2 className="text-xl font-bold">Yêu cầu của tôi</h2><div className="mt-4 space-y-3">{cases.map(c=><button key={c.id} data-testid="support-case-row" className={`w-full rounded-xl border p-4 text-left ${selected===c.id?"border-cyan-600 bg-cyan-950/20":"border-slate-800"}`} onClick={()=>open(c)}><div className="flex flex-wrap items-center justify-between gap-2"><b>{c.caseNumber} · {c.subject}</b><span className="rounded bg-slate-800 px-2 py-1 text-xs">{c.status}</span></div><div className="mt-1 text-xs text-slate-500">{c.category} · {c.priority} · SLA {dateTime(c.slaDueAt)}{c.overdue?" · OVERDUE":""}</div></button>)}{!cases.length&&<div className="py-10 text-center text-slate-500">Chưa có yêu cầu hỗ trợ.</div>}</div></section></div>
  {current&&<section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{current.caseNumber} · {current.subject}</h2><p className="text-sm text-slate-400">{current.description}</p></div><span className="rounded bg-slate-800 px-3 py-1 text-sm font-bold">{current.status}</span></div><div className="mt-5 space-y-2">{events.map(e=><div key={e.id} className="rounded-xl border border-slate-800 p-3"><div className="text-xs text-slate-500">{e.actorName} · {e.eventType} · {dateTime(e.createdAt)}</div>{e.message&&<div className="mt-1 text-sm">{e.message}</div>}</div>)}</div>{current.status!=="CLOSED"&&<div className="mt-4 flex gap-2"><input aria-label="Tin nhắn hỗ trợ" className="input flex-1" placeholder="Nhắn thêm thông tin..." value={message} onChange={e=>setMessage(e.target.value)}/><button className="btn btn-primary" onClick={send} disabled={busy||!message.trim()}>Gửi</button></div>}</section>}</div>;
}
