"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { api, dateTime } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import type { CheckInHistoryItem, CheckInPreview, CheckInResult, StaffGateStatus, LoyaltyConcessionClaim } from "@/lib/types";

function currentReturnTo(){return typeof window==="undefined"?"/staff/check-in":window.location.pathname+window.location.search;}

export default function StaffCheckInPage(){
 const [payload,setPayload]=useState(""); const [preview,setPreview]=useState<CheckInPreview|null>(null); const [result,setResult]=useState<CheckInResult|null>(null); const [message,setMessage]=useState(""); const [rewardCode,setRewardCode]=useState(""); const [rewardClaim,setRewardClaim]=useState<LoyaltyConcessionClaim|null>(null); const [scanning,setScanning]=useState(false); const [gate,setGate]=useState<StaffGateStatus|null>(null); const [history,setHistory]=useState<CheckInHistoryItem[]>([]); const videoRef=useRef<HTMLVideoElement|null>(null); const streamRef=useRef<MediaStream|null>(null); const timerRef=useRef<number|null>(null); const autoHandled=useRef(false);
 useEffect(()=>{void boot();return stopCamera;},[]);
 async function boot(){
  const a=getAuth(); const returnTo=currentReturnTo();
  if(!a||!["STAFF","MANAGER","ADMIN"].includes(a.role)){location.href=`/login?reason=required&returnTo=${encodeURIComponent(returnTo)}`;return;}
  try{
   const [g,h]=await Promise.all([api<StaffGateStatus>("/staff/gate-status"),api<CheckInHistoryItem[]>("/staff/check-in/history")]); setGate(g);setHistory(h);
   const ticket=new URLSearchParams(window.location.search).get("ticket");
   if(ticket&&!autoHandled.current){autoHandled.current=true;const fullUrl=window.location.href;setPayload(fullUrl);await inspectAndMaybeSubmit(fullUrl,g,true);}
  }catch(e){setMessage((e as Error).message)}
 }
 async function refreshHistory(){try{setHistory(await api<CheckInHistoryItem[]>("/staff/check-in/history"))}catch{}}
 function feedback(ok:boolean){
  try{if(navigator.vibrate)navigator.vibrate(ok?[120]:[100,80,100]);}catch{}
  try{const AC=(window as any).AudioContext||(window as any).webkitAudioContext;if(!AC)return;const ctx=new AC();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.frequency.value=ok?880:220;gain.gain.value=0.05;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+0.12);}catch{}
 }
 async function previewTicket(value=payload){const v=value.trim();if(!v)return null;const p=await api<CheckInPreview>("/staff/check-in/preview",{method:"POST",body:JSON.stringify({payload:v})});setPreview(p);return p;}
 async function inspectAndMaybeSubmit(value:string,knownGate=gate,auto=false){
  const v=value.trim();if(!v)return;
  if(knownGate&&!knownGate.canScan){setMessage(knownGate.message);return;}
  setMessage("");setResult(null);
  try{const p=await previewTicket(v);if(!p)return;if(!p.allowed){setMessage(p.message);feedback(false);return;}if(auto)await doSubmit(v);}
  catch(e){setMessage((e as Error).message);feedback(false);}
 }
 async function doSubmit(value=payload){const v=value.trim();if(!v)return;setMessage("");setResult(null);try{const r=await api<CheckInResult>("/staff/check-in",{method:"POST",body:JSON.stringify({payload:v})});setResult(r);setPayload("");setPreview(null);setMessage("Check-in vé thành công.");feedback(true);window.history.replaceState({},"","/staff/check-in");await refreshHistory();}catch(e){setMessage((e as Error).message);feedback(false);}}
 async function submit(value=payload,knownGate=gate){const v=value.trim();if(!v)return;if(knownGate&&!knownGate.canScan){setMessage(knownGate.message);return;}try{const p=await previewTicket(v);if(!p)return;if(!p.allowed){setMessage(p.message);feedback(false);return;}await doSubmit(v);}catch(e){setMessage((e as Error).message);feedback(false);}}
 async function claimLoyaltyReward(){const code=rewardCode.trim();if(!code)return;setMessage("");setRewardClaim(null);try{const r=await api<LoyaltyConcessionClaim>("/staff/loyalty-rewards/claim",{method:"POST",body:JSON.stringify({code})});setRewardClaim(r);setRewardCode("");setMessage(r.message);feedback(true);}catch(e){setMessage((e as Error).message);feedback(false);}}
 async function startCamera(){if(gate&&!gate.canScan){setMessage(gate.message);return;}setMessage("");const BD=(window as any).BarcodeDetector;if(!BD){setMessage("Trình duyệt chưa hỗ trợ BarcodeDetector. Bạn có thể dùng camera mặc định của điện thoại quét QR URL hoặc dán URL vào ô bên cạnh.");return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}const detector=new BD({formats:["qr_code"]});setScanning(true);timerRef.current=window.setInterval(async()=>{try{if(!videoRef.current||videoRef.current.readyState<2)return;const codes=await detector.detect(videoRef.current);const raw=codes?.[0]?.rawValue;if(raw){stopCamera();setPayload(raw);await submit(raw);}}catch{}},450);}catch(e){setMessage("Không mở được camera trong website: "+(e as Error).message+". Bạn vẫn có thể dùng camera mặc định của điện thoại quét QR để mở trang check-in.");}}
 async function decodeImage(file:File){setMessage("");const BD=(window as any).BarcodeDetector;if(!BD){setMessage("Trình duyệt chưa hỗ trợ đọc QR từ ảnh.");return;}try{const detector=new BD({formats:["qr_code"]});const bitmap=await createImageBitmap(file);const codes=await detector.detect(bitmap);bitmap.close();const raw=codes?.[0]?.rawValue;if(!raw)throw new Error("Không tìm thấy mã QR trong ảnh");setPayload(raw);await submit(raw);}catch(e){setMessage((e as Error).message)}}
 function stopCamera(){if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null;}streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setScanning(false);}
 const hasTicket=typeof window!=="undefined"&&new URLSearchParams(window.location.search).has("ticket");
 return <div className="mx-auto max-w-4xl space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">STAFF GATE · PWA V26</p><h1 className="text-3xl font-bold">Quét QR check-in</h1><p className="mt-2 text-slate-400">Hệ thống kiểm tra trước phim, rạp, ca làm và trạng thái vé rồi mới cho check-in.</p></div><Link href="/staff/schedule" className="btn btn-secondary">🕒 Lịch & chấm công</Link></div>
  {gate&&<section className={`rounded-2xl border p-4 ${gate.canScan?"border-emerald-700/60 bg-emerald-950/35":"border-amber-700/60 bg-amber-950/35"}`}><div className="font-bold">{gate.canScan?"✅ Cổng check-in sẵn sàng":"⚠️ Chưa thể quét vé"}</div><div className="mt-1 text-sm text-slate-300">{gate.message}</div>{gate.attendance&&<div className="mt-1 text-xs text-slate-400">Bắt đầu ca: {dateTime(gate.attendance.checkInAt)}</div>}{!gate.canScan&&hasTicket&&<Link className="btn btn-primary mt-3 inline-flex" href={`/staff/schedule?returnTo=${encodeURIComponent(currentReturnTo())}`}>Bắt đầu ca để quét vé này</Link>}</section>}
  {preview&&<section className={`rounded-2xl border p-5 ${preview.allowed?"border-emerald-700/60 bg-emerald-950/25":"border-red-700/60 bg-red-950/30"}`}><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">{preview.allowed?"✅ Vé có thể check-in":"❌ Vé chưa thể check-in"}</h2><span className="text-xs text-slate-400">{preview.bookingId.slice(0,8)}…</span></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p><span className="text-slate-500">Phim:</span> {preview.movieTitle}</p><p><span className="text-slate-500">Rạp:</span> {preview.cinemaName}</p><p><span className="text-slate-500">Phòng:</span> {preview.auditoriumName}</p><p><span className="text-slate-500">Suất:</span> {dateTime(preview.showtimeStart)}</p></div><div className={`mt-3 rounded-xl p-3 font-semibold ${preview.allowed?"bg-emerald-950/60 text-emerald-200":"bg-red-950/60 text-red-200"}`}>{preview.message}</div></section>}
  <section className="card p-6"><div className="grid gap-5 md:grid-cols-2"><div><div className="overflow-hidden rounded-2xl border border-slate-700 bg-black/50"><video ref={videoRef} muted playsInline className="aspect-video w-full object-cover"/></div><div className="mt-3 flex gap-2">{!scanning?<button className="btn btn-primary flex-1" disabled={gate?.canScan===false} onClick={startCamera}>📷 Camera trong web</button>:<button className="btn btn-secondary flex-1" onClick={stopCamera}>Dừng camera</button>}</div><p className="mt-2 text-xs text-slate-500">Camera điện thoại hoặc Google Lens có thể mở QR URL trực tiếp. V11.2 sẽ hiển thị chính xác vé thuộc rạp nào nếu có sai rạp.</p></div><div><label className="text-sm font-bold">QR URL / payload</label><textarea className="input mt-2 min-h-36" value={payload} onChange={e=>{setPayload(e.target.value);setPreview(null)}} placeholder="http://.../staff/check-in?ticket=... hoặc CINEBOOKING|V2|..."/><button className="btn btn-primary mt-3 w-full" disabled={gate?.canScan===false} onClick={()=>submit()}>Kiểm tra & xác nhận check-in</button><label className="btn btn-secondary mt-2 block w-full cursor-pointer text-center">📷 Chụp / đọc QR từ ảnh<input className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(f)void decodeImage(f);e.currentTarget.value=""}}/></label></div></div></section>
  {message&&<div className={`rounded-2xl p-4 text-lg font-semibold ${result?"bg-emerald-950/60 text-emerald-200":"bg-red-950/60 text-red-300"}`}>{message}</div>}
  {result&&<section className="card border-emerald-700/60 p-6"><div className="text-6xl">✅</div><h2 className="mt-3 text-3xl font-bold">{result.movieTitle}</h2><div className="mt-4 grid gap-3 text-base text-slate-300 sm:grid-cols-2"><p><span className="text-slate-500">Rạp:</span> {result.cinemaName}</p><p><span className="text-slate-500">Phòng:</span> {result.auditoriumName}</p><p><span className="text-slate-500">Suất:</span> {dateTime(result.showtimeStart)}</p><p><span className="text-slate-500">Check-in:</span> {dateTime(result.checkedInAt)}</p></div></section>}
  <section className="card p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">LOYALTY V40</p><h2 className="text-xl font-bold">🎁 Xác nhận quà bắp nước</h2><p className="mt-1 text-sm text-slate-400">Nhập mã GIFT-* từ Ví phần thưởng của khách. Xác nhận sẽ trừ tồn kho đúng một lần.</p></div></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input className="input flex-1 font-mono" value={rewardCode} onChange={e=>setRewardCode(e.target.value)} placeholder="GIFT-RWDCORN-XXXXXXXX"/><button className="btn btn-primary" onClick={claimLoyaltyReward}>Xác nhận giao quà</button></div>{rewardClaim&&<div className="mt-4 rounded-2xl border border-emerald-700/50 bg-emerald-950/30 p-4 text-sm"><div className="font-bold text-emerald-200">✅ {rewardClaim.productName} × {rewardClaim.quantity}</div><div className="mt-1 text-slate-300">Khách: {rewardClaim.customerEmail}</div><div className="mt-1 font-mono text-xs text-slate-500">{rewardClaim.redemptionCode}</div></div>}</section>
  <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Lịch sử quét gần đây</h2><button className="text-sm text-slate-400 hover:text-white" onClick={refreshHistory}>Làm mới</button></div><div className="card overflow-x-auto p-4"><table className="w-full min-w-[650px] text-sm"><thead><tr className="text-left text-slate-400"><th className="p-2">Thời gian</th><th>Phim</th><th>Rạp / phòng</th><th>Nguồn</th><th>Booking</th></tr></thead><tbody>{history.length===0?<tr><td className="p-4 text-slate-500" colSpan={5}>Chưa có vé nào được quét.</td></tr>:history.map(x=><tr key={`${x.bookingId}-${x.checkedInAt}`} className="border-t border-slate-800"><td className="p-2">{dateTime(x.checkedInAt)}</td><td>{x.movieTitle}</td><td>{x.cinemaName} · {x.auditoriumName}</td><td>{x.source}</td><td className="font-mono text-xs text-slate-500">{x.bookingId.slice(0,8)}…</td></tr>)}</tbody></table></div></section>
 </div>
}
