"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { api, dateTime } from "@/lib/api";
import { clearAuth, getAuth } from "@/lib/auth";
import type { StaffOption, StaffShift, UserProfile } from "@/lib/types";

type Form={staffUserId:string;shiftDate:string;startTime:string;endTime:string;note:string};
const today=()=>new Date().toISOString().slice(0,10);
const empty=():Form=>({staffUserId:"",shiftDate:today(),startTime:"08:00",endTime:"14:00",note:""});

export default function ShiftManagementPage(){
 const [items,setItems]=useState<StaffShift[]>([]),[staff,setStaff]=useState<StaffOption[]>([]),[form,setForm]=useState<Form>(empty()),[editing,setEditing]=useState<string|null>(null),[msg,setMsg]=useState(""),[role,setRole]=useState(""); const [showCancelled,setShowCancelled]=useState(false);
 const [from,setFrom]=useState(today()),[to,setTo]=useState(()=>{const d=new Date();d.setDate(d.getDate()+14);return d.toISOString().slice(0,10)});
 async function load(){const me=await api<UserProfile>("/me");if(!["ADMIN","MANAGER"].includes(me.role)){clearAuth();location.href="/login?returnTo=/admin/shifts";return;}setRole(me.role);const [s,o]=await Promise.all([api<StaffShift[]>(`/admin/shifts?from=${from}&to=${to}`),api<StaffOption[]>("/admin/shifts/staff-options")]);setItems(s);setStaff(o);}
 useEffect(()=>{if(!getAuth()){location.href="/login?returnTo=/admin/shifts";return;}void load().catch(e=>setMsg((e as Error).message));},[from,to]);
 const visible=useMemo(()=>showCancelled?items:items.filter(s=>s.status!=="CANCELLED"),[items,showCancelled]);
 const grouped=useMemo(()=>Object.entries(visible.reduce<Record<string,StaffShift[]>>((a,s)=>{(a[s.shiftDate]??=[]).push(s);return a},{})),[visible]);
 function edit(s:StaffShift){setEditing(s.id);setForm({staffUserId:s.staffUserId,shiftDate:s.shiftDate,startTime:s.startTime.slice(0,5),endTime:s.endTime.slice(0,5),note:s.note||""});setMsg("");window.scrollTo({top:0,behavior:"smooth"});}
 function reset(){setEditing(null);setForm(empty())}
 async function save(e:FormEvent){e.preventDefault();setMsg("");try{const body={...form,note:form.note||null};await api(editing?`/admin/shifts/${editing}`:"/admin/shifts",{method:editing?"PUT":"POST",body:JSON.stringify(body)});setMsg(editing?"Đã cập nhật ca làm.":"Đã xếp ca cho nhân viên.");reset();await load();}catch(e){setMsg((e as Error).message)}}
 async function cancel(id:string){if(!confirm("Huỷ ca làm này? Ca đã huỷ sẽ không chặn việc tạo lại cùng khung giờ."))return;try{await api(`/admin/shifts/${id}/cancel`,{method:"POST"});await load();setMsg("Đã huỷ ca làm. Bạn có thể tạo lại cùng ngày/giờ nếu cần.")}catch(e){setMsg((e as Error).message)}}
 function statusClass(s:string){return s==="COMPLETED"?"bg-emerald-950/60 text-emerald-300":s==="CANCELLED"?"bg-slate-800 text-slate-400":"bg-blue-950/60 text-blue-300";}
 return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">STAFF OPERATIONS · V23</p><h1 className="text-3xl font-bold">Xếp ca nhân viên</h1><p className="mt-1 text-slate-400">{role==="MANAGER"?"Bạn chỉ xếp ca cho STAFF cùng rạp.":"Admin có thể xếp ca cho STAFF/MANAGER ở mọi rạp."}</p></div><div className="flex gap-2"><Link className="btn btn-secondary" href="/admin/attendance">Bảng công & nghỉ phép</Link>{role==="ADMIN"&&<Link className="btn btn-secondary" href="/admin/staff">Nhân viên</Link>}{role==="MANAGER"&&<Link className="btn btn-secondary" href="/staff/schedule">Lịch của tôi</Link>}</div></div>
 {msg&&<div className="card p-4 text-sm">{msg}</div>}
 <div className="grid gap-6 xl:grid-cols-[420px_1fr]"><form onSubmit={save} className="card h-fit space-y-4 p-5"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Sửa ca":"Tạo ca mới"}</h2>{editing&&<button type="button" className="text-sm text-slate-400" onClick={reset}>Huỷ sửa</button>}</div><div><label className="mb-1 block text-sm">Nhân viên</label><select className="input" value={form.staffUserId} onChange={e=>setForm({...form,staffUserId:e.target.value})} required><option value="">Chọn nhân viên</option>{staff.map(s=><option key={s.userId} value={s.userId}>{s.employeeCode} · {s.fullName} · {s.cinemaName}</option>)}</select></div><div><label className="mb-1 block text-sm">Ngày làm</label><input className="input" type="date" value={form.shiftDate} onChange={e=>setForm({...form,shiftDate:e.target.value})} required/></div><div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-sm">Bắt đầu</label><input className="input" type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} required/></div><div><label className="mb-1 block text-sm">Kết thúc</label><input className="input" type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} required/></div></div><div><label className="mb-1 block text-sm">Ghi chú</label><textarea className="input min-h-24" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Quầy vé, soát vé, hỗ trợ sảnh..."/></div><div className="rounded-xl bg-slate-950/50 p-3 text-xs leading-5 text-slate-400"><div>Giờ ca dùng định dạng 24 giờ: <b>08:00 = 8 giờ sáng</b>, <b>12:00 = 12 giờ trưa</b>, <b>20:00 = 8 giờ tối</b>, <b>00:00 = 12 giờ đêm hôm sau</b>.</div><div className="mt-2">V11.1: nhân viên có thể bắt đầu ca từ 30 phút trước giờ bắt đầu cho tới trước giờ kết thúc. Ca <b>CANCELLED</b> không còn chiếm khung giờ.</div></div><button className="btn btn-primary w-full">{editing?"Lưu thay đổi":"Xếp ca"}</button></form>
 <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-2"><div><label className="mb-1 block text-xs text-slate-400">Từ ngày</label><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label className="mb-1 block text-xs text-slate-400">Đến ngày</label><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><label className="sm:col-span-2 flex items-center gap-2 text-sm text-slate-400"><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/> Hiển thị ca đã huỷ ({items.filter(x=>x.status==="CANCELLED").length})</label></div>{grouped.length===0&&<div className="card p-8 text-center text-slate-400">Chưa có ca làm trong khoảng ngày này.</div>}{grouped.map(([day,list])=><section key={day} className="space-y-2"><h3 className="font-bold">📅 {new Intl.DateTimeFormat("vi-VN",{dateStyle:"full"}).format(new Date(day+"T00:00:00"))}</h3>{list.map(s=><div key={s.id} className={`card p-4 ${s.status==="CANCELLED"?"opacity-60":""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold">{s.employeeCode} · {s.staffName}</div><div className="mt-1 text-sm text-slate-400">🏢 {s.cinemaName} · {s.startTime.slice(0,5)}–{s.endTime.slice(0,5)} · <span className={`rounded px-2 py-0.5 text-xs font-bold ${statusClass(s.status)}`}>{s.status}</span></div>{s.note&&<div className="mt-1 text-sm text-slate-300">{s.note}</div>}<div className="mt-2 text-xs text-slate-400">🎫 Đã quét: <b className="text-white">{s.checkedTickets||0}</b> vé</div>{s.checkInAt&&<div className="mt-1 text-xs text-emerald-300">Vào ca: {dateTime(s.checkInAt)}{s.checkOutAt?` · Ra ca: ${dateTime(s.checkOutAt)}`:" · Đang làm"}{s.workedMinutes!=null?` · Làm ${Math.floor(s.workedMinutes/60)}h ${s.workedMinutes%60}m`:""}{s.lateMinutes?` · Trễ ${s.lateMinutes}m`:""}{s.earlyLeaveMinutes?` · Về sớm ${s.earlyLeaveMinutes}m`:""}</div>}</div><div className="flex gap-2">{s.status==="SCHEDULED"&&!s.checkInAt&&<><button className="btn btn-secondary" onClick={()=>edit(s)}>Sửa</button><button className="btn btn-secondary" onClick={()=>cancel(s.id)}>Huỷ</button></>}</div></div></div>)}</section>)}</div></div></div>
}
