"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { api, dateTime } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import type { StaffAttendance, StaffLeaveRequest, StaffShift } from "@/lib/types";

function safeReturnTo(value:string|null){if(!value||!value.startsWith("/")||value.startsWith("//"))return null;return value;}
function fmtMinutes(v?:number){const n=Math.max(0,v||0);return `${Math.floor(n/60)}h ${n%60}m`;}
function punctualityLabel(v?:string){return v==="LATE_EARLY"?"Đi trễ + về sớm":v==="LATE"?"Đi trễ":v==="EARLY"?"Về sớm":"Đúng giờ";}
function leaveType(v:string){return v==="VACATION"?"Nghỉ phép":v==="SICK"?"Nghỉ bệnh":v==="PERSONAL"?"Việc riêng":"Khác";}
function leaveStatusClass(v:string){return v==="APPROVED"?"text-emerald-300":v==="REJECTED"?"text-rose-300":v==="CANCELLED"?"text-slate-500":"text-amber-300";}

export default function StaffSchedulePage(){
 const [shifts,setShifts]=useState<StaffShift[]>([]),[current,setCurrent]=useState<StaffAttendance|undefined>(),[attendanceHistory,setAttendanceHistory]=useState<StaffAttendance[]>([]),[leaves,setLeaves]=useState<StaffLeaveRequest[]>([]),[msg,setMsg]=useState(""); const [returnTo,setReturnTo]=useState<string|null>(null);
 const [leaveForm,setLeaveForm]=useState({fromDate:"",toDate:"",leaveType:"VACATION",reason:""});
 async function load(){const [s,c,h,l]=await Promise.all([api<StaffShift[]>("/staff/schedule"),api<StaffAttendance|undefined>("/staff/attendance/current"),api<StaffAttendance[]>("/staff/attendance/history"),api<StaffLeaveRequest[]>("/staff/leaves")]);setShifts(s);setCurrent(c);setAttendanceHistory(h);setLeaves(l)}
 useEffect(()=>{const rt=safeReturnTo(new URLSearchParams(window.location.search).get("returnTo"));setReturnTo(rt);const a=getAuth();if(!a||!["STAFF","MANAGER"].includes(a.role)){const here=window.location.pathname+window.location.search;location.href=`/login?reason=required&returnTo=${encodeURIComponent(here)}`;return;}void load().catch(e=>setMsg((e as Error).message));},[]);
 async function start(id:string){try{const a=await api<StaffAttendance>(`/staff/attendance/start/${id}`,{method:"POST"});setCurrent(a);setMsg("Đã bắt đầu ca. Hệ thống sẽ tự ghi nhận đi trễ nếu vượt quá thời gian ân hạn.");await load();if(returnTo)location.href=returnTo;}catch(e){setMsg((e as Error).message)}}
 async function end(){if(!confirm("Kết thúc ca làm hiện tại?"))return;try{const a=await api<StaffAttendance>("/staff/attendance/end",{method:"POST"});setMsg(`Đã kết thúc ca · làm ${fmtMinutes(a.workedMinutes)}${a.earlyLeaveMinutes>0?` · về sớm ${a.earlyLeaveMinutes} phút`:""}.`);await load()}catch(e){setMsg((e as Error).message)}}
 async function submitLeave(e:FormEvent){e.preventDefault();setMsg("");try{await api("/staff/leaves",{method:"POST",body:JSON.stringify(leaveForm)});setLeaveForm({fromDate:"",toDate:"",leaveType:"VACATION",reason:""});setMsg("Đã gửi đơn nghỉ phép để Manager/Admin duyệt.");await load()}catch(e){setMsg((e as Error).message)}}
 async function cancelLeave(id:string){if(!confirm("Huỷ đơn nghỉ đang chờ duyệt?"))return;try{await api(`/staff/leaves/${id}/cancel`,{method:"POST"});setMsg("Đã huỷ đơn nghỉ.");await load()}catch(e){setMsg((e as Error).message)}}
 const upcoming=useMemo(()=>shifts.filter(s=>s.status!=="CANCELLED"),[shifts]);
 const completed=attendanceHistory.filter(x=>x.checkOutAt); const worked=completed.reduce((a,x)=>a+(x.workedMinutes||0),0),late=completed.reduce((a,x)=>a+x.lateMinutes,0),early=completed.reduce((a,x)=>a+x.earlyLeaveMinutes,0);
 return <div className="mx-auto max-w-6xl space-y-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">STAFF OPERATIONS · V23</p><h1 className="text-3xl font-bold">Lịch làm, chấm công & nghỉ phép</h1><p className="mt-1 text-slate-400">Theo dõi giờ làm, đi trễ/về sớm và gửi đơn nghỉ ngay trên CineBooking.</p></div><Link className="btn btn-primary" href={returnTo||"/staff/check-in"}>🎫 {returnTo?"Quay lại vé đang quét":"Quét vé"}</Link></div>{msg&&<div className="card p-4 text-sm">{msg}</div>}
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="card p-4"><div className="text-xs text-slate-400">Ca đã hoàn tất</div><div className="mt-1 text-2xl font-bold">{completed.length}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Thời gian làm</div><div className="mt-1 text-2xl font-bold">{fmtMinutes(worked)}</div></div><div className="card p-4"><div className="text-xs text-slate-400">Đi trễ</div><div className="mt-1 text-2xl font-bold text-amber-300">{late} phút</div></div><div className="card p-4"><div className="text-xs text-slate-400">Về sớm</div><div className="mt-1 text-2xl font-bold text-rose-300">{early} phút</div></div></section>
 <section className={`card p-5 ${current?"border-emerald-700/60":""}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">{current?"🟢 Đang trong ca":"⚪ Chưa bắt đầu ca"}</h2>{current&&<><p className="mt-1 text-sm text-slate-300">{current.cinemaName} · vào ca {dateTime(current.checkInAt)}</p><p className="mt-1 text-xs text-slate-400">{punctualityLabel(current.punctualityStatus)}{current.lateMinutes>0?` · trễ ${current.lateMinutes} phút`:""}</p></>}</div><div className="flex gap-2">{current&&returnTo&&<Link className="btn btn-primary" href={returnTo}>Quay lại check-in</Link>}{current&&<button className="btn btn-secondary" onClick={end}>Kết thúc ca</button>}</div></div></section>
 <section className="space-y-3"><h2 className="text-xl font-bold">Ca được phân</h2>{upcoming.length===0&&<div className="card p-6 text-slate-400">Chưa có ca làm.</div>}{upcoming.map(s=><div className="card p-4" key={s.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{new Intl.DateTimeFormat("vi-VN",{dateStyle:"full"}).format(new Date(s.shiftDate+"T00:00:00"))}</b><div className="mt-1 text-sm text-slate-400">{s.startTime.slice(0,5)}–{s.endTime.slice(0,5)} · {s.cinemaName}</div>{s.note&&<div className="mt-1 text-sm">{s.note}</div>}<div className="mt-1 text-xs text-slate-500">Trạng thái: {s.status}{s.checkInAt?` · vào ${dateTime(s.checkInAt)}`:""} · Đã quét {s.checkedTickets||0} vé</div>{s.punctualityStatus&&<div className={`mt-1 text-xs ${s.punctualityStatus==="ON_TIME"?"text-emerald-300":"text-amber-300"}`}>{punctualityLabel(s.punctualityStatus)}{s.lateMinutes?` · trễ ${s.lateMinutes} phút`:""}{s.earlyLeaveMinutes?` · về sớm ${s.earlyLeaveMinutes} phút`:""}</div>}</div>{s.status==="SCHEDULED"&&!s.checkInAt&&!current&&<button className="btn btn-primary" onClick={()=>start(s.id)}>Bắt đầu ca</button>}</div></div>)}</section>
 <section className="grid gap-5 lg:grid-cols-[380px_1fr]"><form onSubmit={submitLeave} className="card h-fit space-y-4 p-5"><div><p className="section-kicker">LEAVE REQUEST</p><h2 className="text-xl font-bold">Gửi đơn nghỉ</h2></div><div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-sm">Từ ngày</label><input className="input" type="date" required value={leaveForm.fromDate} onChange={e=>setLeaveForm({...leaveForm,fromDate:e.target.value})}/></div><div><label className="mb-1 block text-sm">Đến ngày</label><input className="input" type="date" required value={leaveForm.toDate} onChange={e=>setLeaveForm({...leaveForm,toDate:e.target.value})}/></div></div><div><label className="mb-1 block text-sm">Loại nghỉ</label><select className="input" value={leaveForm.leaveType} onChange={e=>setLeaveForm({...leaveForm,leaveType:e.target.value})}><option value="VACATION">Nghỉ phép</option><option value="SICK">Nghỉ bệnh</option><option value="PERSONAL">Việc riêng</option><option value="OTHER">Khác</option></select></div><div><label className="mb-1 block text-sm">Lý do</label><textarea className="input min-h-24" required maxLength={500} value={leaveForm.reason} onChange={e=>setLeaveForm({...leaveForm,reason:e.target.value})}/></div><p className="text-xs leading-5 text-slate-400">Đơn đã duyệt sẽ chặn việc xếp ca mới trong ngày nghỉ. Nếu đã có ca SCHEDULED, quản lý phải xử lý ca trước khi duyệt nghỉ.</p><button className="btn btn-primary w-full">Gửi đơn nghỉ</button></form>
 <div className="space-y-3"><h2 className="text-xl font-bold">Đơn nghỉ của tôi</h2>{leaves.length===0&&<div className="card p-6 text-slate-400">Chưa có đơn nghỉ.</div>}{leaves.map(l=><div className="card p-4" key={l.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold">{leaveType(l.leaveType)} · {l.fromDate}{l.toDate!==l.fromDate?` → ${l.toDate}`:""}</div><div className="mt-1 text-sm text-slate-300">{l.reason}</div><div className={`mt-2 text-xs font-bold ${leaveStatusClass(l.status)}`}>{l.status}</div>{l.reviewNote&&<div className="mt-1 text-xs text-slate-400">Phản hồi: {l.reviewNote}</div>}</div>{l.status==="PENDING"&&<button className="btn btn-secondary" onClick={()=>cancelLeave(l.id)}>Huỷ đơn</button>}</div></div>)}</div></section>
 <section className="space-y-3"><h2 className="text-xl font-bold">Lịch sử chấm công</h2><div className="card overflow-x-auto p-4"><table className="w-full min-w-[780px] text-sm"><thead><tr className="text-left text-slate-400"><th className="p-2">Rạp</th><th className="p-2">Vào ca</th><th className="p-2">Ra ca</th><th className="p-2">Thời gian</th><th className="p-2">Đi trễ</th><th className="p-2">Về sớm</th><th className="p-2">Đánh giá</th></tr></thead><tbody>{attendanceHistory.map(a=><tr key={a.id} className="border-t border-slate-800"><td className="p-2">{a.cinemaName}</td><td className="p-2">{dateTime(a.checkInAt)}</td><td className="p-2">{a.checkOutAt?dateTime(a.checkOutAt):"—"}</td><td className="p-2">{a.workedMinutes!=null?fmtMinutes(a.workedMinutes):"—"}</td><td className="p-2">{a.lateMinutes} phút</td><td className="p-2">{a.earlyLeaveMinutes} phút</td><td className={`p-2 font-semibold ${a.punctualityStatus==="ON_TIME"?"text-emerald-300":"text-amber-300"}`}>{punctualityLabel(a.punctualityStatus)}</td></tr>)}</tbody></table></div></section></div>
}
