"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { api, dateTime } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import type { AdminLoyaltyMember, LoyaltySummary } from "@/lib/types";

export default function AdminLoyaltyPage(){
 const [members,setMembers]=useState<AdminLoyaltyMember[]>([]); const [q,setQ]=useState(""); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 const [delta,setDelta]=useState<Record<string,string>>({}); const [reason,setReason]=useState<Record<string,string>>({}); const [birthDate,setBirthDate]=useState<Record<string,string>>({}); const [birthReason,setBirthReason]=useState<Record<string,string>>({});
 async function load(){setMembers(await api<AdminLoyaltyMember[]>("/admin/loyalty/members"));}
 useEffect(()=>{const a=getAuth();if(!a||a.role!=="ADMIN"){location.href="/login?next=/admin/loyalty";return;}load().catch(e=>setMsg(e.message));},[]);
 const rows=useMemo(()=>{const s=q.trim().toLowerCase();return !s?members:members.filter(m=>`${m.email} ${m.fullName} ${m.membershipTier}`.toLowerCase().includes(s));},[members,q]);
 async function adjust(m:AdminLoyaltyMember){const d=Number(delta[m.userId]||0);const why=(reason[m.userId]||"").trim();if(!Number.isInteger(d)||d===0){setMsg("Nhập số điểm nguyên khác 0.");return;}if(!why){setMsg("Cần nhập lý do điều chỉnh để lưu audit.");return;}if(!confirm(`${d>0?"Cộng":"Trừ"} ${Math.abs(d)} điểm cho ${m.email}?`))return;setBusy(true);setMsg("");try{const r=await api<LoyaltySummary>(`/admin/loyalty/users/${m.userId}/adjustments`,{method:"POST",body:JSON.stringify({deltaPoints:d,reason:why})});setDelta(v=>({...v,[m.userId]:""}));setReason(v=>({...v,[m.userId]:""}));setMsg(`Đã điều chỉnh. Số dư mới: ${r.balancePoints} điểm.`);await load();}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 async function saveBirthDate(m:AdminLoyaltyMember){const value=birthDate[m.userId]??m.birthDate??"";const why=(birthReason[m.userId]||"").trim();if(!why){setMsg("Cần nhập lý do chỉnh ngày sinh để lưu audit.");return;}setBusy(true);setMsg("");try{await api<AdminLoyaltyMember>(`/admin/loyalty/users/${m.userId}/birth-date`,{method:"PUT",body:JSON.stringify({birthDate:value||null,reason:why})});setBirthReason(v=>({...v,[m.userId]:""}));setMsg(`Đã cập nhật ngày sinh cho ${m.email}.`);await load();}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 async function expireNow(){setBusy(true);setMsg("");try{const r=await api<{expiredPoints:number}>("/admin/loyalty/expire-now",{method:"POST"});setMsg(`Đã quét hạn điểm. Hết hạn ${r.expiredPoints} điểm.`);await load();}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">V40 · LOYALTY OPERATIONS</p><h1 className="text-3xl font-bold">Loyalty & Membership 2.0</h1><p className="mt-2 max-w-3xl text-slate-400">Theo dõi số dư, lifetime tier, điểm sắp hết hạn và điều chỉnh thủ công có audit. Điều chỉnh admin không làm thay đổi lifetime tier.</p></div><div className="flex gap-2"><button className="btn btn-secondary" disabled={busy} onClick={expireNow}>Quét hạn điểm</button><Link href="/admin" className="btn btn-secondary">← Admin</Link></div></div>{msg&&<div className="rounded-xl bg-slate-900 p-4">{msg}</div>}<section className="card p-5"><input className="input" placeholder="Tìm theo email, tên, hạng..." value={q} onChange={e=>setQ(e.target.value)}/><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1280px] text-sm"><thead><tr className="text-left text-slate-400"><th className="p-2">Khách hàng</th><th>Số dư</th><th>Lifetime</th><th>Hạng</th><th>Sắp hết hạn</th><th>Ngày sinh</th><th className="min-w-[360px]">Điều chỉnh</th></tr></thead><tbody>{rows.map(m=><tr key={m.userId} className="border-t border-slate-800 align-top"><td className="p-2"><div className="font-bold">{m.fullName}</div><div className="text-xs text-slate-500">{m.email}</div></td><td className="font-black text-amber-300">{m.balancePoints}</td><td>{m.lifetimePoints}</td><td><span className="rounded-lg bg-slate-800 px-2 py-1 text-xs font-bold">{m.membershipTier}</span></td><td><div>{m.expiringSoonPoints} điểm</div><div className="text-xs text-slate-500">{m.nextExpiryAt?dateTime(m.nextExpiryAt):"—"}</div></td><td><div className="grid min-w-[310px] grid-cols-[145px_1fr_auto] gap-2"><input className="input" type="date" value={birthDate[m.userId]??m.birthDate??""} onChange={e=>setBirthDate(v=>({...v,[m.userId]:e.target.value}))}/><input className="input" value={birthReason[m.userId]||""} onChange={e=>setBirthReason(v=>({...v,[m.userId]:e.target.value}))} placeholder="Lý do chỉnh ngày sinh"/><button className="btn btn-secondary" disabled={busy} onClick={()=>saveBirthDate(m)}>Lưu</button></div></td><td><div className="grid grid-cols-[110px_1fr_auto] gap-2"><input className="input" inputMode="numeric" value={delta[m.userId]||""} onChange={e=>setDelta(v=>({...v,[m.userId]:e.target.value}))} placeholder="+100 / -50"/><input className="input" value={reason[m.userId]||""} onChange={e=>setReason(v=>({...v,[m.userId]:e.target.value}))} placeholder="Lý do điều chỉnh"/><button className="btn btn-primary" disabled={busy} onClick={()=>adjust(m)}>Lưu</button></div></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="p-6 text-slate-500">Không có khách hàng phù hợp.</td></tr>}</tbody></table></div></section></div>
}
