"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { clearAuth, getAuth } from "@/lib/auth";
import type { StaffLeaveRequest, StaffTimesheetReport, UserProfile } from "@/lib/types";

type Cinema={id:string;name:string};
const currentMonth=()=>new Date().toISOString().slice(0,7);
const hours=(v:number)=>(v/60).toLocaleString("vi-VN",{maximumFractionDigits:1})+"h";
function leaveType(v:string){return v==="VACATION"?"Nghỉ phép":v==="SICK"?"Nghỉ bệnh":v==="PERSONAL"?"Việc riêng":"Khác";}

export default function AdminAttendancePage(){
 const [month,setMonth]=useState(currentMonth()),[cinemaId,setCinemaId]=useState(""),[cinemas,setCinemas]=useState<Cinema[]>([]),[report,setReport]=useState<StaffTimesheetReport|null>(null),[leaves,setLeaves]=useState<StaffLeaveRequest[]>([]),[status,setStatus]=useState("PENDING"),[msg,setMsg]=useState(""),[role,setRole]=useState("");
 async function load(){const me=await api<UserProfile>("/me");if(!["ADMIN","MANAGER"].includes(me.role)){clearAuth();location.href="/login?returnTo=/admin/attendance";return;}setRole(me.role);const query=cinemaId?`&cinemaId=${encodeURIComponent(cinemaId)}`:"";const [r,l,c]=await Promise.all([api<StaffTimesheetReport>(`/admin/attendance/timesheet?month=${month}${query}`),api<StaffLeaveRequest[]>(`/admin/attendance/leaves?status=${status}`),api<Cinema[]>("/admin/shifts/cinema-options")]);setReport(r);setLeaves(l);setCinemas(c);if(me.role==="MANAGER"&&c.length===1)setCinemaId(c[0].id);}
 useEffect(()=>{if(!getAuth()){location.href="/login?returnTo=/admin/attendance";return;}void load().catch(e=>setMsg((e as Error).message));},[month,cinemaId,status]);
 async function review(id:string,decision:"APPROVED"|"REJECTED"){const note=prompt(decision==="APPROVED"?"Ghi chú duyệt (có thể bỏ trống):":"Lý do từ chối:","");if(note===null)return;try{await api(`/admin/attendance/leaves/${id}/review`,{method:"POST",body:JSON.stringify({decision,note:note||null})});setMsg(decision==="APPROVED"?"Đã duyệt đơn nghỉ.":"Đã từ chối đơn nghỉ.");await load()}catch(e){setMsg((e as Error).message)}}
 const kpis=useMemo(()=>report?[{label:"Giờ được xếp",value:hours(report.totalScheduledMinutes)},{label:"Giờ thực làm",value:hours(report.totalWorkedMinutes)},{label:"Đi trễ",value:`${report.totalLateMinutes} phút`},{label:"Về sớm",value:`${report.totalEarlyLeaveMinutes} phút`},{label:"Vắng ca",value:String(report.totalAbsentShifts)}]:[],[report]);
 return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">HR & ATTENDANCE · V23</p><h1 className="text-3xl font-bold">Bảng công & nghỉ phép</h1><p className="mt-1 text-slate-400">Theo dõi giờ làm, đi trễ/về sớm, vắng ca và phê duyệt nghỉ phép.</p></div><Link className="btn btn-secondary" href="/admin/shifts">← Xếp ca</Link></div>{msg&&<div className="card p-4 text-sm">{msg}</div>}
 <section className="card grid gap-3 p-4 md:grid-cols-3"><div><label className="mb-1 block text-xs text-slate-400">Tháng</label><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><div><label className="mb-1 block text-xs text-slate-400">Rạp</label><select className="input" value={cinemaId} onChange={e=>setCinemaId(e.target.value)} disabled={role==="MANAGER"}><option value="">Tất cả rạp</option>{cinemas.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="flex items-end"><div className="text-sm text-slate-400">Bảng công: <b className="text-white">{report?.cinemaName||"—"}</b></div></div></section>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(k=><div className="card p-4" key={k.label}><div className="text-xs text-slate-400">{k.label}</div><div className="mt-1 text-2xl font-bold">{k.value}</div></div>)}</section>
 <section className="space-y-3"><h2 className="text-xl font-bold">Bảng công tháng</h2><div className="card overflow-x-auto p-3"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="text-left text-slate-400"><th className="p-2">Nhân viên</th><th className="p-2">Rạp</th><th className="p-2">Ca xếp</th><th className="p-2">Hoàn tất</th><th className="p-2">Vắng</th><th className="p-2">Giờ xếp</th><th className="p-2">Giờ làm</th><th className="p-2">Đi trễ</th><th className="p-2">Về sớm</th><th className="p-2">Ngày nghỉ</th></tr></thead><tbody>{report?.rows.map(r=><tr className="border-t border-slate-800" key={r.staffUserId}><td className="p-2"><b>{r.employeeCode}</b><div className="text-xs text-slate-400">{r.staffName}</div></td><td className="p-2">{r.cinemaName}</td><td className="p-2">{r.scheduledShifts}</td><td className="p-2 text-emerald-300">{r.completedShifts}</td><td className={`p-2 ${r.absentShifts?"text-rose-300":""}`}>{r.absentShifts}</td><td className="p-2">{hours(r.scheduledMinutes)}</td><td className="p-2">{hours(r.workedMinutes)}</td><td className={`p-2 ${r.lateMinutes?"text-amber-300":""}`}>{r.lateMinutes}m</td><td className={`p-2 ${r.earlyLeaveMinutes?"text-amber-300":""}`}>{r.earlyLeaveMinutes}m</td><td className="p-2">{r.approvedLeaveDays}</td></tr>)}{report&&report.rows.length===0&&<tr><td className="p-6 text-center text-slate-400" colSpan={10}>Chưa có nhân viên/dữ liệu trong tháng.</td></tr>}</tbody></table></div></section>
 <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Đơn nghỉ phép</h2><select className="input !w-auto" value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Đang chờ</option><option value="APPROVED">Đã duyệt</option><option value="REJECTED">Từ chối</option><option value="CANCELLED">Đã huỷ</option><option value="ALL">Tất cả</option></select></div>{leaves.length===0&&<div className="card p-6 text-slate-400">Không có đơn nghỉ theo bộ lọc.</div>}{leaves.map(l=><div className="card p-4" key={l.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-bold">{l.employeeCode} · {l.staffName}</div><div className="mt-1 text-sm text-slate-400">{l.cinemaName} · {leaveType(l.leaveType)} · {l.fromDate}{l.toDate!==l.fromDate?` → ${l.toDate}`:""}</div><div className="mt-2 text-sm">{l.reason}</div><div className="mt-2 text-xs text-slate-500">Trạng thái: {l.status}{l.reviewedByEmail?` · xử lý bởi ${l.reviewedByEmail}`:""}</div>{l.reviewNote&&<div className="mt-1 text-xs text-slate-400">Ghi chú: {l.reviewNote}</div>}</div>{l.status==="PENDING"&&<div className="flex gap-2"><button className="btn btn-primary" onClick={()=>review(l.id,"APPROVED")}>Duyệt</button><button className="btn btn-secondary" onClick={()=>review(l.id,"REJECTED")}>Từ chối</button></div>}</div></div>)}</section></div>
}
