"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { api, currency, dateTime } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import { copyBookingCode, downloadBookingCalendar } from "@/lib/calendar";
import type { Booking, RefundQuote } from "@/lib/types";

type TimeTab = "upcoming" | "past" | "all";
type SortMode = "showtime-asc" | "showtime-desc" | "created-desc";

export default function Bookings(){
 const [items,setItems]=useState<Booking[]>([]); const [error,setError]=useState(""); const [msg,setMsg]=useState("");
 const [tab,setTab]=useState<TimeTab>("upcoming"); const [query,setQuery]=useState(""); const [status,setStatus]=useState("ALL"); const [sort,setSort]=useState<SortMode>("showtime-asc");
 const [busyId,setBusyId]=useState(""); const [now,setNow]=useState<number|null>(null); const [refundQuotes,setRefundQuotes]=useState<Record<string,RefundQuote>>({});
 async function load(){setItems(await api<Booking[]>("/bookings/me"));}
 useEffect(()=>{if(!getAuth()){location.href="/login";return;}load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{const refresh=()=>setNow(Date.now());const first=setTimeout(refresh,0);const timer=setInterval(refresh,60000);return()=>{clearTimeout(first);clearInterval(timer);};},[]);
 async function quoteRefund(b:Booking){setBusyId(b.id);setMsg("");try{const q=await api<RefundQuote>(`/bookings/${b.id}/refund-quote`);setRefundQuotes(v=>({...v,[b.id]:q}));}catch(e){setMsg((e as Error).message)}finally{setBusyId("")}}
 async function refund(b:Booking){setBusyId(b.id);setMsg("");try{const result=await api<{status:string;refundAmount:number;automatic:boolean}>(`/bookings/${b.id}/refund-request`,{method:"POST",body:JSON.stringify({reason:"Khách hàng xác nhận hủy vé từ ví vé"})});setRefundQuotes(v=>{const copy={...v};delete copy[b.id];return copy;});setMsg(result.status==="REFUNDED"?`Đã hoàn vé tự động ${currency(result.refundAmount)}. Ghế đã được mở bán lại.`:"Đã gửi yêu cầu hoàn vé. Admin sẽ xác nhận giao dịch hoàn tiền.");await load();}catch(e){setMsg((e as Error).message)}finally{setBusyId("")}}
 async function calendar(b:Booking){setBusyId(b.id);setMsg("");try{await downloadBookingCalendar(b.id);setMsg("Đã tải lịch suất chiếu (.ics). Mở file để thêm vào Google Calendar, Apple Calendar hoặc Outlook.");}catch(e){setMsg((e as Error).message)}finally{setBusyId("")}}
 async function copyCode(b:Booking){try{await copyBookingCode(b.id);setMsg(`Đã sao chép mã booking ${b.id}.`);}catch{setMsg("Không thể sao chép tự động. Hãy chọn mã booking và sao chép thủ công.");}}
 const badge=(s:string)=>s==="CONFIRMED"?"bg-emerald-900 text-emerald-200":s==="PENDING"?"bg-amber-900 text-amber-200":s==="REFUND_REQUESTED"?"bg-orange-900 text-orange-200":s==="REFUNDED"?"bg-cyan-950 text-cyan-200":"bg-slate-800 text-slate-300";
 const currentTime=now??0;
 const summary=useMemo(()=>({
   upcoming:items.filter(b=>new Date(b.showtimeStart).getTime()>=currentTime&&b.status==="CONFIRMED").length,
   pending:items.filter(b=>b.status==="PENDING").length,
   refund:items.filter(b=>b.status==="REFUND_REQUESTED").length,
   total:items.length,
 }),[items,currentTime]);
 const visible=useMemo(()=>{
   const q=query.trim().toLocaleLowerCase("vi-VN");
   return items.filter(b=>{
     const start=new Date(b.showtimeStart).getTime();
     if(tab==="upcoming"&&start<currentTime)return false;
     if(tab==="past"&&start>=currentTime)return false;
     if(status!=="ALL"&&b.status!==status)return false;
     if(q&&!`${b.movieTitle} ${b.id} ${b.seats.map(s=>s.code).join(" ")}`.toLocaleLowerCase("vi-VN").includes(q))return false;
     return true;
   }).sort((a,b)=>sort==="created-desc"?new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime():sort==="showtime-desc"?new Date(b.showtimeStart).getTime()-new Date(a.showtimeStart).getTime():new Date(a.showtimeStart).getTime()-new Date(b.showtimeStart).getTime());
 },[items,tab,status,query,sort,currentTime]);
 return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker">V31 · TICKET WALLET · V38 REFUND POLICY</p><h1 className="text-3xl font-bold">Ví vé của tôi</h1><p className="mt-2 text-slate-400">Tìm vé nhanh, mở QR, thêm suất chiếu vào lịch và theo dõi hoàn tiền.</p></div><Link href="/offline-tickets" className="btn btn-secondary">📴 Vé offline</Link></div>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Tổng quan vé"><div className="card p-4"><div className="text-sm text-slate-400">Sắp chiếu</div><div className="mt-1 text-2xl font-black text-emerald-300">{summary.upcoming}</div></div><div className="card p-4"><div className="text-sm text-slate-400">Chờ thanh toán</div><div className="mt-1 text-2xl font-black text-amber-300">{summary.pending}</div></div><div className="card p-4"><div className="text-sm text-slate-400">Chờ hoàn tiền</div><div className="mt-1 text-2xl font-black text-orange-300">{summary.refund}</div></div><div className="card p-4"><div className="text-sm text-slate-400">Tổng booking</div><div className="mt-1 text-2xl font-black">{summary.total}</div></div></section>
 <section className="card mt-5 p-4"><div className="flex flex-wrap gap-2" role="group" aria-label="Khoảng thời gian"><button type="button" className={`btn ${tab==="upcoming"?"btn-primary":"btn-secondary"}`} onClick={()=>setTab("upcoming")}>Sắp chiếu</button><button type="button" className={`btn ${tab==="past"?"btn-primary":"btn-secondary"}`} onClick={()=>setTab("past")}>Đã qua</button><button type="button" className={`btn ${tab==="all"?"btn-primary":"btn-secondary"}`} onClick={()=>setTab("all")}>Tất cả</button></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div><label htmlFor="booking-search" className="text-sm text-slate-400">Tìm phim / mã booking / ghế</label><input id="booking-search" className="input mt-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ví dụ: Sao Hỏa, A1..."/></div><div><label htmlFor="booking-status" className="text-sm text-slate-400">Trạng thái</label><select id="booking-status" className="input mt-1" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Tất cả trạng thái</option><option value="CONFIRMED">CONFIRMED</option><option value="PENDING">PENDING</option><option value="REFUND_REQUESTED">REFUND_REQUESTED</option><option value="REFUNDED">REFUNDED</option><option value="CANCELLED">CANCELLED</option><option value="EXPIRED">EXPIRED</option></select></div><div><label htmlFor="booking-sort" className="text-sm text-slate-400">Sắp xếp</label><select id="booking-sort" className="input mt-1" value={sort} onChange={e=>setSort(e.target.value as SortMode)}><option value="showtime-asc">Suất chiếu gần nhất</option><option value="showtime-desc">Suất chiếu xa → gần</option><option value="created-desc">Booking mới tạo</option></select></div></div><div className="mt-3 text-sm text-slate-400">Hiển thị <b className="text-slate-200">{visible.length}</b> / {items.length} booking.</div></section>
 {error&&<p className="mt-5 text-red-300">{error}</p>}{msg&&<div className="mt-5 rounded-xl bg-slate-900 p-4 text-sm">{msg}</div>}<div className="mt-6 grid gap-4">
  {visible.map(b=><div key={b.id} className="card p-5"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="text-lg font-extrabold">{b.movieTitle}</div><div className="mt-1 text-sm text-slate-400">{dateTime(b.showtimeStart)} · Ghế {b.seats.map(s=>s.code).join(", ")}</div><button type="button" onClick={()=>copyCode(b)} className="mt-2 text-left text-xs text-slate-500 hover:text-slate-300" title="Sao chép mã booking">Booking #{b.id} · 📋 Sao chép</button>{b.checkedInAt&&<div className="mt-2 inline-flex rounded-lg bg-emerald-950 px-2 py-1 text-xs font-bold text-emerald-300">✅ Đã check-in {dateTime(b.checkedInAt)}</div>}</div><div className="md:text-right"><div className="text-xl font-bold">{currency(b.totalAmount)}</div><div aria-label={`Trạng thái booking: ${b.status}`} className={`mt-1 inline-block rounded-lg px-2 py-1 text-xs font-bold ${badge(b.status)}`}>{b.status}</div>{b.refundAmount!=null&&<div className="mt-1 text-xs text-cyan-300">Mức hoàn: {currency(b.refundAmount)}{b.refundRatePercent!=null?` · ${b.refundRatePercent}%`:""}</div>}</div></div>
   <div className="mt-4 grid gap-3 border-t border-slate-800 pt-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-slate-500">Tiền vé</span><div className="font-semibold">{currency(b.seatAmount??b.totalAmount)}</div></div><div><span className="text-slate-500">Bắp nước</span><div className="font-semibold">{currency(b.concessionAmount||0)}</div></div><div><span className="text-slate-500">Giảm giá</span><div className="font-semibold text-emerald-300">-{currency(b.discountAmount||0)}</div></div><div><span className="text-slate-500">Ưu đãi</span><div className="font-semibold">{b.voucherCode||"—"}{b.pointsRedeemed?` · ${b.pointsRedeemed} điểm`:""}</div></div></div>
   {!!b.concessions?.length&&<div className="mt-3 rounded-xl bg-slate-950/55 p-3 text-sm"><b>🍿 Bắp nước</b><div className="mt-2 flex flex-wrap gap-2">{b.concessions.map((x,i)=><span key={`${x.productId}-${i}`} className="rounded-lg border border-slate-700 px-2 py-1 text-slate-300">{x.name} × {x.quantity}</span>)}</div></div>}
   <div className="mt-4 flex flex-wrap gap-2">{b.status==="CONFIRMED"&&<Link className="btn btn-primary" href={`/ticket/${b.id}`}>Mở QR vé</Link>}{b.status==="CONFIRMED"&&<button className="btn btn-secondary" disabled={busyId===b.id} onClick={()=>calendar(b)}>📅 {busyId===b.id?"Đang tạo lịch...":"Thêm vào lịch"}</button>}{b.status==="CONFIRMED"&&!b.checkedInAt&&<button className="btn btn-secondary" disabled={busyId===b.id} onClick={()=>quoteRefund(b)}>↩ {busyId===b.id?"Đang tính...":"Kiểm tra hoàn vé"}</button>}{b.status==="REFUND_REQUESTED"&&<span className="rounded-xl bg-orange-950/40 px-3 py-2 text-sm text-orange-200">Đang chờ duyệt hoàn tiền</span>}{b.status==="REFUNDED"&&<span className="rounded-xl bg-cyan-950/40 px-3 py-2 text-sm text-cyan-200">Đã hoàn tiền</span>}</div>
   {refundQuotes[b.id]&&<div className="mt-4 rounded-xl border border-cyan-900/60 bg-cyan-950/20 p-4" aria-label={`Chính sách hoàn vé ${b.id}`}><div className="font-bold text-cyan-200">Chính sách hoàn vé · {refundQuotes[b.id].policyCode}</div><div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><div><span className="text-slate-500">Mức hoàn</span><div className="font-bold">{refundQuotes[b.id].ratePercent}% · {currency(refundQuotes[b.id].refundAmount)}</div></div><div><span className="text-slate-500">Phí hủy</span><div className="font-bold">{currency(refundQuotes[b.id].feeAmount)}</div></div><div><span className="text-slate-500">Xử lý</span><div className="font-bold">{refundQuotes[b.id].automatic?"Tự động":"Cần admin xác nhận"}</div></div></div><p className="mt-2 text-sm text-slate-300">{refundQuotes[b.id].message}</p><div className="mt-3 flex gap-2">{refundQuotes[b.id].refundable&&<button className="btn btn-primary" disabled={busyId===b.id} onClick={()=>refund(b)}>Xác nhận hủy & hoàn {currency(refundQuotes[b.id].refundAmount)}</button>}<button className="btn btn-secondary" onClick={()=>setRefundQuotes(v=>{const copy={...v};delete copy[b.id];return copy;})}>Đóng</button></div></div>}
  </div>)}
  {!visible.length&&!error&&<div className="card p-6 text-slate-400">Không có booking phù hợp bộ lọc hiện tại.</div>}
 </div></div>
}
