"use client";
import { useEffect, useState } from "react";
import { api, dateTime } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import type { SupportCase, SupportCaseEvent, SupportCinema, SupportStaff, SupportSummary } from "@/lib/types";

export default function AdminSupportPage(){
 const [role,setRole]=useState("");const [cinemas,setCinemas]=useState<SupportCinema[]>([]);const [cinemaId,setCinemaId]=useState("");const [summary,setSummary]=useState<SupportSummary|null>(null);const [cases,setCases]=useState<SupportCase[]>([]);const [staff,setStaff]=useState<SupportStaff[]>([]);const [events,setEvents]=useState<Record<string,SupportCaseEvent[]>>({});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{const a=getAuth();if(!a||(a.role!=="ADMIN"&&a.role!=="MANAGER")){location.href="/login?returnTo=/admin/support&reason=manager";return;}setRole(a.role);api<SupportCinema[]>("/admin/support/cinemas").then(x=>{setCinemas(x);if(a.role!=="ADMIN"&&x[0])setCinemaId(x[0].id)}).catch(e=>setError((e as Error).message));},[]);
 async function load(id=cinemaId){if(!id&&role==="ADMIN"){setSummary(null);setStaff([]);setCases(await api<SupportCase[]>("/admin/support/cases"));return;}if(!id)return;const q=`?cinemaId=${encodeURIComponent(id)}`;const [s,c,p]=await Promise.all([api<SupportSummary>(`/admin/support/summary${q}`),api<SupportCase[]>(`/admin/support/cases${q}`),api<SupportStaff[]>(`/admin/support/staff-options${q}`)]);setSummary(s);setCases(c);setStaff(p);}
 useEffect(()=>{if(role&&(cinemaId||role==="ADMIN"))load().catch(e=>setError((e as Error).message));},[cinemaId,role]);
 async function history(id:string){setEvents({...events,[id]:await api<SupportCaseEvent[]>(`/admin/support/cases/${id}/events`)})}
 async function reply(c:SupportCase){const message=prompt("Nội dung phản hồi khách hàng:");if(!message)return;setBusy(true);try{await api(`/admin/support/cases/${c.id}/reply`,{method:"POST",body:JSON.stringify({message,internal:false})});await load();await history(c.id);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function internal(c:SupportCase){const message=prompt("Ghi chú nội bộ:");if(!message)return;setBusy(true);try{await api(`/admin/support/cases/${c.id}/reply`,{method:"POST",body:JSON.stringify({message,internal:true})});await history(c.id);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function transition(c:SupportCase,target:string){let note:string|null=null;if(target==="RESOLVED"||target==="CLOSED"){note=prompt(target==="RESOLVED"?"Kết quả xử lý:":"Lý do đóng:");if(!note)return;}setBusy(true);try{await api(`/admin/support/cases/${c.id}/transition`,{method:"POST",body:JSON.stringify({targetStatus:target,note})});await load();await history(c.id);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function plan(c:SupportCase,priority:string,assignedTo:string){setBusy(true);try{await api(`/admin/support/cases/${c.id}/plan`,{method:"PUT",body:JSON.stringify({priority,assignedTo:assignedTo||null})});await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="mx-auto max-w-7xl space-y-7"><div><p className="section-kicker">V45 · CUSTOMER SUPPORT & SERVICE RECOVERY 2.0</p><h1 className="text-3xl font-bold">Support Operations</h1><p className="mt-2 text-slate-400">Triage yêu cầu khách hàng theo rạp, SLA, mức ưu tiên, người phụ trách và lịch sử append-only.</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm"><span className="mb-1 block text-slate-400">Rạp hỗ trợ</span><select aria-label="Rạp hỗ trợ" className="input min-w-64" value={cinemaId} onChange={e=>setCinemaId(e.target.value)}>{role==="ADMIN"&&<option value="">Tất cả / chưa gắn rạp</option>}{cinemas.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn btn-secondary" onClick={()=>load()} disabled={!cinemaId&&role!=="ADMIN"}>Làm mới</button></div>{error&&<div className="rounded-xl border border-red-800 bg-red-950/30 p-4 text-red-200">{error}</div>}
 {summary&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Đang xử lý",summary.activeCases],["Chờ khách",summary.waitingCustomer],["Critical",summary.criticalActive],["Quá SLA",summary.overdueSla]].map(([k,v])=><div className="card p-4" key={String(k)}><div className="text-xs text-slate-400">{k}</div><div className="text-2xl font-black">{v}</div></div>)}</div>}
 <section className="space-y-3">{cases.map(c=><div key={c.id} data-testid="admin-support-case" className={`card p-5 ${c.overdue?"border-red-800":""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b>{c.caseNumber} · {c.subject}</b><span className="rounded bg-slate-800 px-2 py-1 text-xs">{c.status}</span>{c.overdue&&<span className="rounded bg-red-900 px-2 py-1 text-xs">OVERDUE</span>}</div><div className="mt-1 text-sm text-slate-400">{c.customerName} · {c.customerEmail} · {c.category}{c.bookingId?` · Booking ${c.bookingId.slice(0,8)}`:""}</div><p className="mt-2 text-sm">{c.description}</p><div className="mt-2 text-xs text-slate-500">SLA: {dateTime(c.slaDueAt)} · Phụ trách: {c.assignedToName||"Chưa phân công"}</div></div><div className="flex flex-wrap gap-2"><button className="btn btn-secondary" onClick={()=>history(c.id)}>Lịch sử</button><button className="btn btn-secondary" onClick={()=>internal(c)}>Note</button>{c.status!=="CLOSED"&&<button className="btn btn-primary" onClick={()=>reply(c)}>Phản hồi</button>}{c.status==="OPEN"&&<button className="btn btn-primary" onClick={()=>transition(c,"IN_PROGRESS")}>Nhận xử lý</button>}{["IN_PROGRESS","WAITING_CUSTOMER"].includes(c.status)&&<button className="btn btn-secondary" onClick={()=>transition(c,"RESOLVED")}>Giải quyết</button>}{c.status==="IN_PROGRESS"&&<button className="btn btn-secondary" onClick={()=>transition(c,"WAITING_CUSTOMER")}>Chờ khách</button>}{c.status==="RESOLVED"&&<button className="btn btn-secondary" onClick={()=>transition(c,"CLOSED")}>Đóng</button>}</div></div><div className="mt-3 grid gap-2 md:grid-cols-2"><label className="text-xs text-slate-500">Ưu tiên<select aria-label={`Ưu tiên ${c.caseNumber}`} className="input mt-1" value={c.priority} disabled={busy} onChange={e=>plan(c,e.target.value,c.assignedTo||"")}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-slate-500">Phụ trách<select aria-label={`Phụ trách ${c.caseNumber}`} className="input mt-1" value={c.assignedTo||""} disabled={busy} onChange={e=>plan(c,c.priority,e.target.value)}><option value="">Chưa phân công</option>{staff.map(s=><option key={s.userId} value={s.userId}>{s.employeeCode} · {s.fullName}</option>)}</select></label></div>{events[c.id]&&<div className="mt-4 border-t border-slate-800 pt-3 space-y-2">{events[c.id].map(e=><div key={e.id} className={`rounded-lg p-2 text-xs ${e.visibility==="INTERNAL"?"bg-amber-950/30":"bg-slate-900"}`}><b>{e.eventType}</b> · {e.actorName} ({e.actorRole}) · {dateTime(e.createdAt)}{e.message?` · ${e.message}`:""}</div>)}</div>}</div>)}{!cases.length&&<div className="card p-10 text-center text-slate-500">Chưa có yêu cầu hỗ trợ tại rạp này.</div>}</section><div className="text-xs text-slate-600">Role hiện tại: {role}</div></div>;
}
