package com.cinebooking.commerce;

import com.cinebooking.common.ApiException;
import com.cinebooking.domain.*;
import com.cinebooking.movie.CinemaRepository;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.Instant; import java.util.*; import java.util.stream.Collectors;
import static com.cinebooking.commerce.CommerceDtos.*;

@Service
public class CommerceService {
 private final ConcessionProductRepository products; private final VoucherRepository vouchers; private final VoucherRedemptionRepository redemptions; private final BookingConcessionRepository bookingConcessions;
 private final CinemaRepository cinemas; private final CinemaConcessionInventoryRepository branchInventory; private final CinemaConcessionPriceRepository branchPrices;
 public CommerceService(ConcessionProductRepository products,VoucherRepository vouchers,VoucherRedemptionRepository redemptions,BookingConcessionRepository bookingConcessions,CinemaRepository cinemas,CinemaConcessionInventoryRepository branchInventory,CinemaConcessionPriceRepository branchPrices){this.products=products;this.vouchers=vouchers;this.redemptions=redemptions;this.bookingConcessions=bookingConcessions;this.cinemas=cinemas;this.branchInventory=branchInventory;this.branchPrices=branchPrices;}
 public List<ProductResponse> publicProducts(){return publicProducts(null);}
 public List<ProductResponse> publicProducts(UUID cinemaId){
  List<ConcessionProduct> list=products.findByActiveTrueOrderBySortOrderAscNameAsc(); if(cinemaId==null)return list.stream().map(this::productDto).toList();
  Cinema cinema=cinemas.findById(cinemaId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy rạp"));
  Map<UUID,CinemaConcessionInventory> inv=branchInventory.findByCinemaId(cinemaId).stream().collect(Collectors.toMap(CinemaConcessionInventory::getProductId,x->x));
  Map<UUID,CinemaConcessionPrice> prices=branchPrices.findByCinemaId(cinemaId).stream().collect(Collectors.toMap(CinemaConcessionPrice::getProductId,x->x));
  return list.stream().filter(p->{var i=inv.get(p.getId());return i!=null&&Boolean.TRUE.equals(i.getActive());}).map(p->productDto(p,cinema,inv.get(p.getId()),prices.get(p.getId()))).toList();
 }
 public List<ProductResponse> allProducts(){return products.findAllByOrderBySortOrderAscNameAsc().stream().map(this::productDto).toList();}
 @Transactional public ProductResponse saveProduct(UUID id,ProductRequest r){
  ConcessionProduct product=id==null?new ConcessionProduct():products.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy sản phẩm"));
  BigDecimal oldPrice=product.getPrice();
  product.setName(r.name().trim());product.setDescription(blank(r.description()));product.setPrice(r.price());product.setImageUrl(blank(r.imageUrl()));product.setActive(r.active()==null?true:r.active());product.setSortOrder(r.sortOrder()==null?0:r.sortOrder());
  product.setInventoryEnabled(r.inventoryEnabled()==null?(product.getInventoryEnabled()==null?true:product.getInventoryEnabled()):r.inventoryEnabled());product.setLowStockThreshold(r.lowStockThreshold()==null?(product.getLowStockThreshold()==null?10:product.getLowStockThreshold()):r.lowStockThreshold());if(product.getStockOnHand()==null)product.setStockOnHand(0);if(product.getStockReserved()==null)product.setStockReserved(0);
  final ConcessionProduct savedProduct=products.save(product);
  for(Cinema c:cinemas.findAllByOrderByNameAsc()){
   CinemaConcessionInventory bi=branchInventory.findByCinemaIdAndProductId(c.getId(),savedProduct.getId()).orElseGet(()->{CinemaConcessionInventory x=new CinemaConcessionInventory();x.setCinemaId(c.getId());x.setProductId(savedProduct.getId());x.setStockOnHand(0);x.setStockReserved(0);x.setLowStockThreshold(savedProduct.getLowStockThreshold());x.setTargetStock(Math.max(30,savedProduct.getLowStockThreshold()*3));x.setActive(Boolean.TRUE.equals(savedProduct.getActive()));return x;});branchInventory.save(bi);
   CinemaConcessionPrice bp=branchPrices.findByCinemaIdAndProductId(c.getId(),savedProduct.getId()).orElseGet(()->{CinemaConcessionPrice x=new CinemaConcessionPrice();x.setCinemaId(c.getId());x.setProductId(savedProduct.getId());x.setPrice(savedProduct.getPrice());x.setActive(true);return x;});
   if(oldPrice!=null&&bp.getPrice()!=null&&bp.getPrice().compareTo(oldPrice)==0)bp.setPrice(savedProduct.getPrice());branchPrices.save(bp);
  }
  return productDto(savedProduct);
 }
 @Transactional public void deleteProduct(UUID id){ConcessionProduct p=products.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy sản phẩm"));p.setActive(false);products.save(p);for(CinemaConcessionInventory i:branchInventory.findByCinemaIdIn(cinemas.findAllByOrderByNameAsc().stream().map(Cinema::getId).toList()))if(i.getProductId().equals(id)){i.setActive(false);branchInventory.save(i);}}
 public List<VoucherResponse> allVouchers(){return vouchers.findByOwnerUserIdIsNullOrderByCreatedAtDesc().stream().map(this::voucherDto).toList();}
 public List<VoucherResponse> publicVouchers(){Instant now=Instant.now();return vouchers.findByActiveTrueAndOwnerUserIdIsNullOrderByCreatedAtDesc().stream().filter(v->(v.getStartsAt()==null||!now.isBefore(v.getStartsAt()))&&(v.getEndsAt()==null||!now.isAfter(v.getEndsAt()))&&(v.getUsageLimit()==null||v.getUsedCount()<v.getUsageLimit())).map(this::voucherDto).toList();}
 @Transactional public VoucherResponse saveVoucher(UUID id,VoucherRequest r){String type=r.discountType().trim().toUpperCase(Locale.ROOT);String code=r.code().trim().toUpperCase(Locale.ROOT);if(!Set.of("PERCENT","FIXED").contains(type))throw new ApiException(HttpStatus.BAD_REQUEST,"Loại voucher không hợp lệ");if(!code.matches("[A-Z0-9_-]{3,30}"))throw new ApiException(HttpStatus.BAD_REQUEST,"Mã ưu đãi chỉ gồm A-Z, 0-9, dấu gạch ngang/gạch dưới và dài 3-30 ký tự");if(type.equals("PERCENT")&&r.discountValue().compareTo(BigDecimal.valueOf(100))>0)throw new ApiException(HttpStatus.BAD_REQUEST,"Phần trăm giảm không được vượt 100");if(r.maxDiscount()!=null&&r.maxDiscount().compareTo(BigDecimal.ZERO)<0)throw new ApiException(HttpStatus.BAD_REQUEST,"Mức giảm tối đa không được âm");if(r.usageLimit()!=null&&r.usageLimit()<1)throw new ApiException(HttpStatus.BAD_REQUEST,"Giới hạn lượt dùng phải từ 1 trở lên hoặc để trống nếu không giới hạn");if(r.endsAt()!=null&&r.startsAt()!=null&&!r.endsAt().isAfter(r.startsAt()))throw new ApiException(HttpStatus.BAD_REQUEST,"Thời gian kết thúc phải sau thời gian bắt đầu");vouchers.findByCodeIgnoreCase(code).filter(other->id==null||!other.getId().equals(id)).ifPresent(other->{throw new ApiException(HttpStatus.CONFLICT,"Mã ưu đãi "+code+" đã tồn tại");});Voucher v=id==null?new Voucher():vouchers.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy voucher"));v.setCode(code);v.setName(r.name().trim());v.setDiscountType(type);v.setDiscountValue(r.discountValue());v.setMinOrderAmount(r.minOrderAmount()==null?BigDecimal.ZERO:r.minOrderAmount());v.setMaxDiscount(r.maxDiscount());v.setStartsAt(r.startsAt());v.setEndsAt(r.endsAt());v.setUsageLimit(r.usageLimit());v.setActive(r.active()==null?true:r.active());if(v.getUsedCount()==null)v.setUsedCount(0);return voucherDto(vouchers.save(v));}
 @Transactional public void deleteVoucher(UUID id){Voucher v=vouchers.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy voucher"));v.setActive(false);vouchers.save(v);}
 public VoucherQuoteResponse quote(String code,BigDecimal amount,UUID userId){Voucher v=vouchers.findByCodeIgnoreCase(code.trim()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Mã ưu đãi không tồn tại"));requireVoucherOwner(v,userId);BigDecimal d=discount(v,amount,true);return new VoucherQuoteResponse(v.getCode(),v.getName(),d,amount.subtract(d).max(BigDecimal.ZERO));}
 @Transactional public AppliedVoucher applyVoucher(String code,BigDecimal amount,UUID userId,UUID bookingId){if(code==null||code.isBlank())return new AppliedVoucher(null,BigDecimal.ZERO,null);Voucher v=vouchers.findByCodeForUpdate(code.trim()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Mã ưu đãi không tồn tại"));requireVoucherOwner(v,userId);BigDecimal d=discount(v,amount,true);v.setUsedCount(v.getUsedCount()+1);vouchers.save(v);VoucherRedemption rd=new VoucherRedemption();rd.setVoucherId(v.getId());rd.setUserId(userId);rd.setBookingId(bookingId);rd.setDiscountAmount(d);redemptions.save(rd);return new AppliedVoucher(v.getCode(),d,v.getId());}
 @Transactional public void releaseVoucher(UUID bookingId){redemptions.findByBookingId(bookingId).ifPresent(rd->{vouchers.findById(rd.getVoucherId()).ifPresent(v->{v.setUsedCount(Math.max(0,v.getUsedCount()-1));vouchers.save(v);});redemptions.delete(rd);});}
 public List<BookingConcession> buildConcessions(UUID bookingId,UUID cinemaId,List<Selection> selections){if(selections==null||selections.isEmpty())return List.of();Cinema cinema=cinemas.findById(cinemaId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy rạp"));Map<UUID,Integer> qty=new LinkedHashMap<>();for(Selection s:selections){if(s==null||s.productId()==null||s.quantity()<=0)continue;if(s.quantity()>10)throw new ApiException(HttpStatus.BAD_REQUEST,"Mỗi combo tối đa 10 phần");qty.merge(s.productId(),s.quantity(),Integer::sum);}List<ConcessionProduct> found=products.findAllById(qty.keySet());if(found.size()!=qty.size())throw new ApiException(HttpStatus.BAD_REQUEST,"Có sản phẩm bắp nước không hợp lệ");Map<UUID,ConcessionProduct> map=new HashMap<>();found.forEach(p->map.put(p.getId(),p));Map<UUID,CinemaConcessionInventory> inv=branchInventory.findByCinemaId(cinemaId).stream().collect(Collectors.toMap(CinemaConcessionInventory::getProductId,x->x));Map<UUID,CinemaConcessionPrice> prices=branchPrices.findByCinemaId(cinemaId).stream().collect(Collectors.toMap(CinemaConcessionPrice::getProductId,x->x));List<BookingConcession> result=new ArrayList<>();for(var e:qty.entrySet()){ConcessionProduct p=map.get(e.getKey());CinemaConcessionInventory bi=inv.get(p.getId());if(!Boolean.TRUE.equals(p.getActive())||bi==null||!Boolean.TRUE.equals(bi.getActive()))throw new ApiException(HttpStatus.CONFLICT,"Sản phẩm "+p.getName()+" hiện không bán tại "+cinema.getName());BigDecimal unit=Optional.ofNullable(prices.get(p.getId())).filter(x->Boolean.TRUE.equals(x.getActive())).map(CinemaConcessionPrice::getPrice).orElse(p.getPrice());BookingConcession bc=new BookingConcession();bc.setBookingId(bookingId);bc.setProductId(p.getId());bc.setProductName(p.getName());bc.setUnitPrice(unit);bc.setQuantity(e.getValue());bc.setSubtotal(unit.multiply(BigDecimal.valueOf(e.getValue())));result.add(bc);}return result;}
 public BigDecimal total(List<BookingConcession> rows){return rows.stream().map(BookingConcession::getSubtotal).reduce(BigDecimal.ZERO,BigDecimal::add);} public void saveConcessions(List<BookingConcession> rows){bookingConcessions.saveAll(rows);} public List<BookingConcession> bookingItems(UUID bookingId){return bookingConcessions.findByBookingId(bookingId);}
 private void requireVoucherOwner(Voucher v,UUID userId){if(v.getOwnerUserId()!=null&&!v.getOwnerUserId().equals(userId))throw new ApiException(HttpStatus.FORBIDDEN,"Voucher này thuộc tài khoản thành viên khác");}
 private BigDecimal discount(Voucher v,BigDecimal amount,boolean enforceUsage){Instant now=Instant.now();if(!Boolean.TRUE.equals(v.getActive()))throw new ApiException(HttpStatus.CONFLICT,"Voucher đã tạm dừng");if(v.getStartsAt()!=null&&now.isBefore(v.getStartsAt()))throw new ApiException(HttpStatus.CONFLICT,"Voucher chưa đến thời gian sử dụng");if(v.getEndsAt()!=null&&now.isAfter(v.getEndsAt()))throw new ApiException(HttpStatus.CONFLICT,"Voucher đã hết hạn");if(enforceUsage&&v.getUsageLimit()!=null&&v.getUsedCount()>=v.getUsageLimit())throw new ApiException(HttpStatus.CONFLICT,"Voucher đã hết lượt sử dụng");if(amount.compareTo(v.getMinOrderAmount())<0)throw new ApiException(HttpStatus.CONFLICT,"Đơn hàng chưa đạt giá trị tối thiểu "+v.getMinOrderAmount().toPlainString()+"đ");BigDecimal d=v.getDiscountType().equals("PERCENT")?amount.multiply(v.getDiscountValue()).divide(BigDecimal.valueOf(100),0,RoundingMode.DOWN):v.getDiscountValue();if(v.getMaxDiscount()!=null)d=d.min(v.getMaxDiscount());return d.min(amount).max(BigDecimal.ZERO);}
 private ProductResponse productDto(ConcessionProduct p){int on=p.getStockOnHand()==null?0:p.getStockOnHand(),reserved=p.getStockReserved()==null?0:p.getStockReserved(),available=Math.max(0,on-reserved),threshold=p.getLowStockThreshold()==null?0:p.getLowStockThreshold();boolean tracked=Boolean.TRUE.equals(p.getInventoryEnabled());return new ProductResponse(p.getId(),p.getName(),p.getDescription(),p.getPrice(),p.getImageUrl(),Boolean.TRUE.equals(p.getActive()),p.getSortOrder(),tracked,on,reserved,available,threshold,tracked&&available<=threshold,tracked&&available<=0,null,null,p.getPrice(),false);}
 private ProductResponse productDto(ConcessionProduct p,Cinema c,CinemaConcessionInventory i,CinemaConcessionPrice bp){int on=i==null?0:Optional.ofNullable(i.getStockOnHand()).orElse(0),reserved=i==null?0:Optional.ofNullable(i.getStockReserved()).orElse(0),available=Math.max(0,on-reserved),threshold=i==null?0:Optional.ofNullable(i.getLowStockThreshold()).orElse(0);boolean tracked=Boolean.TRUE.equals(p.getInventoryEnabled())&&i!=null&&Boolean.TRUE.equals(i.getActive());BigDecimal price=bp!=null&&Boolean.TRUE.equals(bp.getActive())?bp.getPrice():p.getPrice();boolean override=price.compareTo(p.getPrice())!=0;return new ProductResponse(p.getId(),p.getName(),p.getDescription(),price,p.getImageUrl(),Boolean.TRUE.equals(p.getActive())&&i!=null&&Boolean.TRUE.equals(i.getActive()),p.getSortOrder(),tracked,on,reserved,available,threshold,tracked&&available<=threshold,tracked&&available<=0,c.getId(),c.getName(),p.getPrice(),override);}
 private VoucherResponse voucherDto(Voucher v){return new VoucherResponse(v.getId(),v.getCode(),v.getName(),v.getDiscountType(),v.getDiscountValue(),v.getMinOrderAmount(),v.getMaxDiscount(),v.getStartsAt(),v.getEndsAt(),v.getUsageLimit(),v.getUsedCount(),Boolean.TRUE.equals(v.getActive()));}
 private String blank(String s){return s==null||s.isBlank()?null:s.trim();} public record Selection(UUID productId,int quantity){} public record AppliedVoucher(String code,BigDecimal discount,UUID voucherId){}
}
