global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules-v65.yml

scrape_configs:
  - job_name: cinebooking-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend-1:8080', 'backend-2:8080']
