from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(path): return (ROOT/path).read_text(encoding="utf-8")
def check(name,cond): checks.append((name,bool(cond)))

mig=text("backend/src/main/resources/db/migration/V44__cinema_maintenance_asset_reliability.sql")
asset=text("backend/src/main/java/com/cinebooking/domain/CinemaEquipmentAsset.java")
order=text("backend/src/main/java/com/cinebooking/domain/MaintenanceWorkOrder.java")
event=text("backend/src/main/java/com/cinebooking/domain/MaintenanceWorkOrderEvent.java")
svc=text("backend/src/main/java/com/cinebooking/maintenance/MaintenanceService.java")
ctl=text("backend/src/main/java/com/cinebooking/maintenance/AdminMaintenanceController.java")
dtos=text("backend/src/main/java/com/cinebooking/maintenance/MaintenanceDtos.java")
rules=text("backend/src/main/java/com/cinebooking/maintenance/MaintenanceWorkOrderRules.java")
security=text("backend/src/main/java/com/cinebooking/config/SecurityConfig.java")
audrepo=text("backend/src/main/java/com/cinebooking/movie/AuditoriumRepository.java")
ui=text("frontend/app/admin/maintenance/page.tsx")
types=text("frontend/lib/types.ts")
header=text("frontend/components/Header.tsx")
e2e=text("frontend/e2e/maintenance-reliability.spec.ts")
integration=text("backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java")
unit=text("backend/src/test/java/com/cinebooking/maintenance/MaintenanceWorkOrderRulesTest.java")
readme=text("README.md")
ci=text(".github/workflows/ci.yml")
rc=text(".github/workflows/release-candidate.yml")
release=text(".github/workflows/release.yml")
make=text("Makefile")
diag=text("tools/diagnose-v44.ps1")

check("V44 migration creates equipment registry", all(x in mig for x in ["cinema_equipment_asset","asset_code","next_service_due","ck_equipment_status"]))
check("V44 migration creates work-order lifecycle", all(x in mig for x in ["maintenance_work_order","OPEN","IN_PROGRESS","BLOCKED","RESOLVED","CANCELLED"]))
check("V44 migration creates immutable work-order event history", all(x in mig for x in ["maintenance_work_order_event","trg_v44_maintenance_event_immutable","append-only"]))
check("V44 migration adds reliability and SLA indexes", all(x in mig for x in ["idx_equipment_service_due","idx_maintenance_work_order_due","idx_maintenance_work_order_assignee_status"]))
check("Equipment entity maps V44 asset fields", all(x in asset for x in ["CinemaEquipmentAsset","nextServiceDue","lastServiceAt","assetCode","auditoriumId"]))
check("Work-order entity maps lifecycle and assignment fields", all(x in order for x in ["MaintenanceWorkOrder","sourceIncidentId","assignedTo","startedAt","resolvedAt","resolutionNote"]))
check("Work-order event entity maps append-only history rows", all(x in event for x in ["MaintenanceWorkOrderEvent","eventType","fromStatus","toStatus","actorUserId"]))
check("V44 repositories exist", all((ROOT/p).exists() for p in ["backend/src/main/java/com/cinebooking/maintenance/CinemaEquipmentAssetRepository.java","backend/src/main/java/com/cinebooking/maintenance/MaintenanceWorkOrderRepository.java","backend/src/main/java/com/cinebooking/maintenance/MaintenanceWorkOrderEventRepository.java"]))
check("Auditorium repository supports cinema-scoped maintenance options", "findByCinemaIdOrderByNameAsc" in audrepo)
check("Maintenance DTOs expose summary, assets, work orders and events", all(x in dtos for x in ["MaintenanceSummary","AssetRequest","AssetResponse","WorkOrderCreateRequest","WorkOrderPlanRequest","WorkOrderTransitionRequest","WorkOrderEventResponse"]))
check("Work-order rules keep terminal states immutable", all(x in rules for x in ['"RESOLVED",Set.of()','"CANCELLED",Set.of()','canTransition','openStatuses']))
check("Maintenance service restricts operations to Manager/Admin", all(x in svc for x in ["Role.MANAGER","Role.ADMIN","Chỉ Manager/Admin được quản lý bảo trì"]))
check("Manager maintenance access is cinema-scoped", all(x in svc for x in ["managerCinema(actor)","Manager chỉ quản lý bảo trì tại rạp của mình"]))
check("Maintenance service validates asset category and status", all(x in svc for x in ["CATEGORIES","ASSET_STATUSES","Mã tài sản đã tồn tại"]))
check("Maintenance service validates same-cinema equipment and assignee", all(x in svc for x in ["Thiết bị không thuộc rạp đã chọn","Người phụ trách phải đang làm việc tại đúng rạp"]))
check("Maintenance service can link an open V43 incident", all(x in svc for x in ["sourceIncidentId","Sự cố nguồn đã được đóng","incidentOptions"]))
check("Maintenance summary includes outage, critical, overdue and service-due KPIs", all(x in svc for x in ["OUT_OF_SERVICE","CRITICAL","countByCinemaIdAndDueAtBeforeAndStatusIn","countByCinemaIdAndNextServiceDueBetween"]))
check("Work-order creation appends immutable event and audit entry", all(x in svc for x in ["appendEvent(x,\"CREATED\"","MAINTENANCE_WORK_ORDER_CREATE"]))
check("Work-order status transition enforces lifecycle rules", all(x in svc for x in ["MaintenanceWorkOrderRules.canTransition","STATUS_CHANGED","RESOLVED","BLOCKED","CANCELLED"]))
check("Maintenance controller exposes option and KPI endpoints", all(x in ctl for x in ["/cinemas","/auditoriums","/staff-options","/incident-options","/summary"]))
check("Maintenance controller exposes asset CRUD surface", all(x in ctl for x in ["/assets","createAsset","updateAsset"]))
check("Maintenance controller exposes work-order lifecycle and history", all(x in ctl for x in ["/work-orders","/plan","/transition","/events"]))
check("Security allows Manager/Admin for V44 maintenance APIs", '.requestMatchers("/api/admin/maintenance/**").hasAnyRole("MANAGER","ADMIN")' in security)
check("V44 frontend is a maintenance reliability control center", all(x in ui for x in ["V44 · CINEMA MAINTENANCE & ASSET RELIABILITY 2.0","Trung tâm bảo trì & độ tin cậy thiết bị","Danh mục thiết bị","Tạo work order"]))
check("V44 frontend exposes asset status and next-service planning", all(x in ui for x in ["OUT_OF_SERVICE","MAINTENANCE","Bảo trì kế tiếp","nextServiceDue"]))
check("V44 frontend exposes work-order transitions", all(x in ui for x in ["Bắt đầu","Tiếp tục","Hoàn tất","BLOCKED","CANCELLED"]))
check("V44 frontend keeps V34 blackout compatibility for Admin", all(x in ui for x in ["V34 COMPATIBILITY","/admin/auditorium-blackouts","Bảo trì & khóa phòng chiếu",'aria-label="Mở lại phòng"']))
check("Frontend types include V44 maintenance contracts", all(x in types for x in ["MaintenanceSummary","MaintenanceAsset","MaintenanceWorkOrder","MaintenanceWorkOrderEvent"]))
check("Header exposes maintenance to Manager/Admin", "/admin/maintenance" in header and "Bảo trì & thiết bị" in header)
check("V44 Playwright covers asset and work-order resolution", all(x in e2e for x in ["V44 admin registers equipment","Thêm thiết bị","Tạo work order","IN_PROGRESS","RESOLVED","Lịch sử"]))
check("V44 unit tests cover lifecycle rules", all(x in unit for x in ["openCanStartBlockOrCancel","terminalStatesAreImmutable","openStatusSetMatchesSlaQueries"]))
check("Integration test retains V44 schema coverage on current Flyway", "maintenanceV44Tables" in integration and any(x in integration for x in ['isEqualTo("44")','isEqualTo("45")','isEqualTo("46")','isEqualTo("47")','isEqualTo("48")','isEqualTo("49")','isEqualTo("50")']))
check("Integration test validates V44 tables, indexes and immutable trigger", all(x in integration for x in ["maintenanceV44Tables","maintenanceV44Indexes","maintenanceV44Trigger","trg_v44_maintenance_event_immutable"]))
check("README retains V44 release history", all(x in readme for x in ["### V44 - Cinema Maintenance & Asset Reliability 2.0","V44__cinema_maintenance_asset_reliability.sql"]))
check("README version history maps V44 migration", "V44__cinema_maintenance_asset_reliability.sql" in readme)
check("Main CI keeps V44 in source regression", "python3 tools/verify_v44_maintenance_reliability.py" in ci and ("name: V26-V44 source regression" in ci or "name: V26-V45 source regression" in ci or "name: V26-V46 source regression" in ci or "name: V26-V47 source regression" in ci or "name: V26-V48 source regression" in ci or "name: V26-V49 source regression" in ci or "name: V26-V50 source regression" in ci))
check("Standalone RC keeps V44 verifier in current source gate", "verify_v44_maintenance_reliability.py" in rc and ("Verify V44 source gate" in rc or "Verify V45 source gate" in rc or "Verify V46 source gate" in rc or "Verify V47 source gate" in rc or "Verify V48 source gate" in rc or "Verify V49 source gate" in rc or "Verify V50 source gate" in rc))
check("Stable release keeps V44 verifier in current source gate", "verify_v44_maintenance_reliability.py" in release and ("Verify V44 source gate" in release or "Verify V45 source gate" in release or "Verify V46 source gate" in release or "Verify V47 source gate" in release or "Verify V48 source gate" in release or "Verify V49 source gate" in release or "Verify V50 source gate" in release))
check("Stable release still publishes immutable GitHub Release", all(x in release for x in ["Create immutable RC tag","Publish stable tag and GitHub Release",'gh release create "$STABLE_TAG"']))
check("Makefile exposes V44 verify and diagnose", "verify-v44:" in make and "diagnose-v44:" in make and "verify_v44_maintenance_reliability.py" in make)
check("V44 diagnostics chains V43 and V44", all(x in diag for x in ["verify_v43_staff_operations.py","verify_v43_analytics_excel_detail.py","verify_v43_analytics_csv_detail.py","verify_v44_maintenance_reliability.py","v44.0.0-rc.N"]))

for name,ok in checks: print(f"[{' OK ' if ok else 'FAIL'}] {name}")
passed=sum(ok for _,ok in checks);total=len(checks)
print(f"\nV44 verification: {passed}/{total} checks passed")
if passed!=total:
    print("Failed checks:")
    for name,ok in checks:
        if not ok: print(" -",name)
    sys.exit(1)
