from pathlib import Path
import re, sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,ok):
    ok=bool(ok);checks.append((name,ok));print(('PASS' if ok else 'FAIL')+': '+name)

mig=text('backend/src/main/resources/db/migration/V40__loyalty_membership_2.sql')
user=text('backend/src/main/java/com/cinebooking/domain/AppUser.java')
tx=text('backend/src/main/java/com/cinebooking/domain/LoyaltyTransaction.java')
lot=text('backend/src/main/java/com/cinebooking/domain/LoyaltyPointLot.java')
reward=text('backend/src/main/java/com/cinebooking/domain/LoyaltyReward.java')
redemption=text('backend/src/main/java/com/cinebooking/domain/LoyaltyRewardRedemption.java')
svc=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyService.java')
repo=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyPointLotRepository.java')
controller=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyController.java')
admin_controller=text('backend/src/main/java/com/cinebooking/commerce/AdminLoyaltyController.java')
staff_controller=text('backend/src/main/java/com/cinebooking/commerce/StaffLoyaltyController.java')
dtos=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyDtos.java')
booking=text('backend/src/main/java/com/cinebooking/booking/BookingService.java')
payment=text('backend/src/main/java/com/cinebooking/payment/PaymentService.java')
refund=text('backend/src/main/java/com/cinebooking/operations/RefundService.java')
commerce=text('backend/src/main/java/com/cinebooking/commerce/CommerceService.java')
inventory=text('backend/src/main/java/com/cinebooking/commerce/InventoryService.java')
profile_service=text('backend/src/main/java/com/cinebooking/user/UserService.java')
app=text('backend/src/main/resources/application.yml')
compose=text('docker-compose.yml')
env=text('.env.example')
types=text('frontend/lib/types.ts')
profile=text('frontend/app/profile/page.tsx')
admin_ui=text('frontend/app/admin/loyalty/page.tsx')
staff_ui=text('frontend/app/staff/check-in/page.tsx')
header=text('frontend/components/Header.tsx')
e2e=text('frontend/e2e/loyalty-membership.spec.ts')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
diag=text('tools/diagnose-v40.ps1')
make=text('Makefile')
readme=text('README.md')
legacy_v39=text('tools/verify_v39_seat_map_ux.py')

check('V40 Flyway migration exists', bool(mig))
check('V40 adds lifetime points, birth date and birthday reward year', all(x in mig for x in ['loyalty_lifetime_points','birth_date','birthday_reward_year']))
check('Lifetime points are backfilled from economic earn/reversal history', "transaction_type = 'EARN'" in mig and "transaction_type = 'REVERSAL'" in mig and 'GREATEST' in mig)
check('Lifetime membership tiers preserve established thresholds', all(x in mig for x in [">= 500 THEN 'SILVER'", ">= 1500 THEN 'GOLD'", ">= 4000 THEN 'DIAMOND'"]))
check('Birth-date DB check avoids volatile CURRENT_DATE dependency', "birth_date >= DATE '1900-01-01'" in mig and 'CURRENT_DATE' not in mig)
check('Loyalty transaction enum expands for expiry, rewards and admin adjustments', all(x in mig for x in ["'EXPIRE'","'REWARD'","'ADJUST_CREDIT'","'ADJUST_DEBIT'"]))
check('V40 transaction ledger stores expiry, balance-after and references', all(x in mig for x in ['expires_at','balance_after','reference_type','reference_id']))
check('V40 creates FIFO point-lot table', 'CREATE TABLE loyalty_point_lot' in mig and 'remaining_points' in mig and 'expires_at' in mig)
check('Legacy balances are backfilled into expiring point lots', 'INSERT INTO loyalty_point_lot' in mig and "INTERVAL '365 days'" in mig)
check('V40 creates reward catalog and redemption tables', 'CREATE TABLE loyalty_reward' in mig and 'CREATE TABLE loyalty_reward_redemption' in mig)
check('Reward catalog supports voucher and concession reward types', "reward_type IN ('VOUCHER','CONCESSION')" in mig)
check('Reward catalog seeds fixed voucher, percent voucher and caramel popcorn', all(x in mig for x in ['RWD20K','RWD10','RWDCORN']))
check('Private voucher ownership is persisted', 'owner_user_id UUID REFERENCES app_user' in mig)
check('Inventory movement supports loyalty reward claims', "'LOYALTY_REWARD'" in mig)

check('AppUser maps lifetime points and birthday fields', all(x in user for x in ['loyalty_lifetime_points','birth_date','birthday_reward_year']))
check('LoyaltyTransaction maps V40 ledger metadata', all(x in tx for x in ['expiresAt','balanceAfter','referenceType','referenceId']))
check('Point-lot entity maps source transaction, remaining amount and expiry', all(x in lot for x in ['sourceTransactionId','remainingPoints','expiresAt','expiredAt']))
check('Reward entity supports concession linkage and voucher economics', all(x in reward for x in ['rewardType','pointsCost','concessionProductId','discountValue']))
check('Redemption entity stores claim status and claimant', all(x in redemption for x in ['redemptionCode','status','claimedAt','claimedByUserId']))

check('Spendable lots are locked and ordered earliest-expiry first', '@Lock(LockModeType.PESSIMISTIC_WRITE)' in repo and 'order by l.expiresAt asc,l.createdAt asc,l.id asc' in repo)
check('Loyalty service expires due lots before mutable balance flows', 'expireDue(u,now)' in svc and 'expireDue(lockedUser,Instant.now())' in svc)
check('Point expiry writes EXPIRE ledger transaction', '"EXPIRE"' in svc and 'Điểm thành viên hết hạn' in svc)
check('New point lots use calendar-month expiry rather than unsupported Instant MONTHS', 'plusMonths(expiryMonths)' in svc and 'ChronoUnit.MONTHS' not in svc)
check('Booking redemption consumes point lots FIFO', 'consumeLots(u.getId(),amount)' in svc and 'findSpendableForUpdate(userId)' in svc)
check('Spending points does not reduce lifetime tier', 'debit(u,cost,"REWARD"' in svc and 'setLoyaltyLifetimePoints' not in re.search(r'private void debit\(.*?\n    \}',svc,re.S).group(0))
check('Payment earning applies tier multiplier from lifetime points', 'multiplier(tier(lifetime(u)))' in svc and 'awardForPayment' in svc)
check('Tier multiplier reaches 1.50x Diamond', 'new BigDecimal("1.50")' in svc)
check('Reward redemption debits points before issuance', 'debit(u,cost,"REWARD"' in svc and 'issueRewardVoucher' in svc)
check('Private reward vouchers are bound to member owner', 'v.setOwnerUserId(u.getId())' in svc)
check('Concession reward claim is one-time', 'if("CLAIMED".equals(rd.getStatus()))' in svc and 'rd.setStatus("CLAIMED")' in svc)
check('Concession reward claim updates tracked inventory', 'inventory.consumeLoyaltyReward' in svc)
check('Admin point adjustments are audited', '"LOYALTY_ADJUST"' in svc and 'audit.record' in svc)
check('Admin point credits intentionally do not change lifetime tier', 'credit(u,delta,false,"ADJUST_CREDIT"' in svc)
check('Admin birth-date correction is audited', 'adminBirthDate' in svc and 'LOYALTY_BIRTHDATE_ADJUST' in svc)
check('Birthday reward is timezone-aware and once per year', 'Asia/Ho_Chi_Minh' in svc and 'getBirthdayRewardYear' in svc and 'setBirthdayRewardYear(today.getYear())' in svc)
check('Birthday voucher is private, one-use and time-limited', 'BDAY-' in svc and 'setUsageLimit(1)' in svc and 'now.plus(30,ChronoUnit.DAYS)' in svc)
check('Scheduled expiry sweep exists', 'expireSweep' in svc and 'LoyaltyExpiryJob' in text('backend/src/main/java/com/cinebooking/commerce/LoyaltyExpiryJob.java'))

check('Customer loyalty API exposes summary/history/rewards/redemptions/vouchers', all(x in controller for x in ['/summary','/transactions','/rewards','/redemptions','/vouchers']))
check('Customer can redeem rewards and claim birthday reward', '/rewards/{id}/redeem' in controller and '/birthday-reward' in controller)
check('Admin API exposes member operations and expiry sweep', '/members' in admin_controller and '/adjustments' in admin_controller and '/expire-now' in admin_controller)
check('Admin API exposes audited birth-date correction', '/birth-date' in admin_controller and 'AdminBirthDateRequest' in admin_controller)
check('Staff API exposes concession reward claim', '/api/staff/loyalty-rewards' in staff_controller and '/claim' in staff_controller)
check('DTOs expose V40 summary, reward, redemption and admin member contracts', all(x in dtos for x in ['LoyaltySummaryResponse','LoyaltyRewardResponse','LoyaltyRedemptionResponse','AdminMemberResponse','ConcessionClaimResponse']))

check('BookingService delegates point redemption/refund to LoyaltyService', 'loyalty.redeemForBooking' in booking and 'loyalty.refundRedeemedPoints' in booking)
check('PaymentService delegates earning to LoyaltyService', 'loyalty.awardForPayment' in payment)
check('RefundService reverses/returns loyalty via original economic owner', 'benefitOwnerId' in refund and 'loyalty.reverseEarnedPoints' in refund and 'loyalty.refundRedeemedPoints' in refund)
check('Commerce hides private vouchers from public/admin global catalog', 'findByOwnerUserIdIsNullOrderByCreatedAtDesc' in commerce and 'findByActiveTrueAndOwnerUserIdIsNullOrderByCreatedAtDesc' in commerce)
check('Commerce enforces private voucher ownership at quote and apply', commerce.count('requireVoucherOwner')>=3 and 'Voucher này thuộc tài khoản thành viên khác' in commerce)
check('Inventory service records loyalty reward stock movement', 'consumeLoyaltyReward' in inventory and '"LOYALTY_REWARD"' in inventory)
check('Profile service exposes lifetime tier and birth date', 'getLoyaltyLifetimePoints' in profile_service and 'getBirthDate' in profile_service)
check('Profile self-service prevents arbitrary birth-date changes', 'Ngày sinh chỉ được tự thiết lập một lần' in profile_service and 'LocalDate.of(1900,1,1)' in profile_service)

check('Application config exposes point expiry settings', all(x in app for x in ['LOYALTY_POINT_EXPIRY_MONTHS','LOYALTY_EXPIRING_SOON_DAYS','LOYALTY_EXPIRY_SCAN_MS']))
check('Compose forwards V40 loyalty settings', all(x in compose for x in ['LOYALTY_POINT_EXPIRY_MONTHS','LOYALTY_EXPIRING_SOON_DAYS','LOYALTY_EXPIRY_SCAN_MS']))
check('Example env documents safe V40 loyalty defaults', all(x in env for x in ['LOYALTY_POINT_EXPIRY_MONTHS=12','LOYALTY_EXPIRING_SOON_DAYS=30','LOYALTY_EXPIRY_SCAN_MS=3600000']))

check('Frontend types expose lifetime summary, rewards and admin member', all(x in types for x in ['LoyaltySummary','LoyaltyReward','LoyaltyRedemption','AdminLoyaltyMember','LoyaltyConcessionClaim']))
check('Profile UI displays lifetime tier and progress', 'Lifetime:' in profile and 'pointsToNextTier' in profile and 'earnMultiplier' in profile)
check('Profile UI displays point expiry forecast', 'sắp hết hạn' in profile and 'nextExpiryAt' in profile)
check('Profile UI has reward catalog and private reward wallet', '🎁 Đổi điểm lấy phần thưởng' in profile and '🎟 Ví phần thưởng' in profile)
check('Profile UI supports birthday reward and immutable self-entered birth date', '🎂 Quà sinh nhật' in profile and 'birthdayRewardEligible' in profile and 'disabled={Boolean(profile.birthDate)}' in profile)
check('Profile UI exposes stable loyalty state anchors for browser tests', all(x in profile for x in ['data-testid="loyalty-balance-points"','data-testid="loyalty-lifetime-points"','data-testid="loyalty-membership-tier"']))
check('Admin UI supports audited signed point adjustments', 'deltaPoints' in admin_ui and 'Lý do điều chỉnh' in admin_ui and '/adjustments' in admin_ui)
check('Admin UI supports audited birth-date correction', '/birth-date' in admin_ui and 'Lý do chỉnh ngày sinh' in admin_ui)
check('Staff gate supports GIFT concession claim', 'GIFT-RWDCORN-XXXXXXXX' in staff_ui and 'Xác nhận giao quà' in staff_ui)
check('Staff reward claim result exposes stable product, customer and code anchors', all(x in staff_ui for x in ['data-testid="loyalty-reward-claim-result"','data-testid="loyalty-reward-claim-product"','data-testid="loyalty-reward-claim-customer-email"','data-testid="loyalty-reward-claim-code"']))
check('Header links admin to loyalty operations', '/admin/loyalty' in header and 'Thành viên' in header)

check('V40 Playwright journey exists', 'V40 admin credit -> private voucher + concession reward -> staff claim' in e2e)
check('V40 Playwright proves admin credit does not manufacture lifetime tier', 'lifetimePoints).toBe(0)' in e2e and 'membershipTier).toBe("BRONZE")' in e2e)
check('V40 Playwright verifies customer-side persisted summary before UI assertions', 'const beforeSpend = await authedJson' in e2e and 'beforeSpend.body?.balancePoints).toBe(500)' in e2e)
check('V40 Playwright uses stable loyalty test ids instead of brittle combined-text locators', all(x in e2e for x in ['getByTestId("loyalty-balance-points")','getByTestId("loyalty-lifetime-points")','getByTestId("loyalty-membership-tier")']) and 'getByText("500 điểm", { exact:true })' not in e2e and 'getByText("BRONZE", { exact:true })' not in e2e)
check('V40 Playwright proves visible balance transitions 500 -> 300 -> 0', e2e.count('getByTestId("loyalty-balance-points")')>=3 and 'toHaveText("500")' in e2e and 'toHaveText("300")' in e2e and 'toHaveText("0")' in e2e)
check('V40 Playwright redeems both voucher and concession rewards', 'Voucher giảm 20.000đ' in e2e and 'Bắp Caramel miễn phí' in e2e)
check('V40 Playwright login helper waits for post-login navigation', 'expectedRole: "USER" | "ADMIN"' in e2e and 'page.waitForURL(expectedRole === "ADMIN" ? /\\/admin$/ : /\\/$/' in e2e)
check('V40 Playwright login helper verifies persisted auth role', 'localStorage.getItem("cinebooking_auth_v3")' in e2e and 'toBe(expectedRole)' in e2e)
check('V40 Playwright proves Admin token with backend before staff route', 'const adminMe = await authedJson<{ role:string }>(page, "/api/me")' in e2e and 'adminMe.body?.role).toBe("ADMIN")' in e2e)
check('V40 Playwright asserts staff route is not bounced back to login', 'toHaveURL(/\\/staff\\/check-in$/)' in e2e)
check('V40 Playwright validates rendered reward-claim contract with stable anchors', all(x in e2e for x in ['getByTestId("loyalty-reward-claim-result")','getByTestId("loyalty-reward-claim-product")','getByTestId("loyalty-reward-claim-customer-email")','getByTestId("loyalty-reward-claim-code")']) and 'getByText(email, { exact:true })' not in e2e)
check('V40 Playwright validates GIFT one-time claim', 'duplicate.status).toBe(409)' in e2e)

check('Integration test expects Flyway V40 or newer', any(f'assertThat(latest).isEqualTo("{v}")' in integration for v in range(40,100)))
check('Integration test verifies V40 tables and reward seeds', 'loyalty_point_lot' in integration and 'loyalty_reward_redemption' in integration and 'rewardSeeds' in integration)
check('Integration test covers adjustment, reward voucher and expiry ledger', 'loyaltyV40RewardRedemptionAndPointExpiryStayLedgerConsistent' in integration and 'integration credit' in integration and "transaction_type='EXPIRE'" in integration)
check('Integration test re-reads customer summary after admin credit and reward debit', 'var customerSummary = loyalty.summary(customer.getEmail())' in integration and 'var afterVoucher = loyalty.summary(customer.getEmail())' in integration and 'afterVoucher.membershipTier()).isEqualTo("BRONZE")' in integration)

check('Main CI runs V40 verifier', bool(re.search(r'V26-V(?:4[0-9]|[5-9][0-9]) source regression',ci)) and 'python3 tools/verify_v40_loyalty_membership.py' in ci)
check('Standalone RC defaults to V40-or-newer candidate', bool(re.search(r'default: "v(?:4[0-9]|[5-9][0-9])\.0\.0-rc\.1"',rc)) and bool(re.search(r'cinebooking_v(?:4[0-9]|[5-9][0-9])_rc_\$\{\{ github\.run_id \}\}',rc)))
check('Standalone RC browser coverage includes V40', 'V38 + V39 + V40' in rc)
check('Stable release defaults to V40-or-newer', bool(re.search(r'default: "(?:4[0-9]|[5-9][0-9])\.0\.0"',release)) and bool(re.search(r'cinebooking_v(?:4[0-9]|[5-9][0-9])_release_\$\{\{ github\.run_id \}\}',release)) and bool(re.search(r'v(?:4[0-9]|[5-9][0-9])-release-test-secret',release)))
check('V39 verifier is forward-compatible with V40 lifecycle', 'V39-or-newer candidate' in legacy_v39 and 'V39 or newer' in legacy_v39)
check('V40 diagnostics chains V39 and V40 verifier', 'diagnose-v39.ps1' in diag and 'verify_v40_loyalty_membership.py' in diag)
check('Makefile exposes V40 verify and diagnose', 'verify-v40:' in make and 'diagnose-v40:' in make)
check('README documents V40 feature and release lifecycle', 'V40 - Loyalty & Membership 2.0' in readme and 'v40.0.0-rc.1' in readme and 'v40.0.0' in readme)

ignored={'.git','node_modules','.next','target','playwright-report','test-results'}
markdown=[p for p in ROOT.rglob('*.md') if not any(part in ignored for part in p.parts)]
check('source still contains exactly one README.md', len(markdown)==1 and markdown[0].resolve()==(ROOT/'README.md').resolve())
check('destructive volume reset remains blocked', 'destructive volume reset is disabled' in make and '@exit 1' in make)
check('real gateway credentials remain blank in example env', re.search(r'^VNPAY_HASH_SECRET=\s*$',env,re.M) and re.search(r'^MOMO_SECRET_KEY=\s*$',env,re.M))
check('example env contains no JWT secret value beyond safe placeholder', 'JWT_SECRET=change-this-to-a-long-random-secret-at-least-32-characters' in env)

failed=[n for n,ok in checks if not ok]
print(f'\n{len(checks)-len(failed)}/{len(checks)} checks passed')
if failed:
    print('Failed checks:')
    for n in failed: print(' -',n)
    sys.exit(1)
