from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

service=text('backend/src/main/java/com/cinebooking/customervalue/CustomerValueIntelligenceService.java')
dtos=text('backend/src/main/java/com/cinebooking/customervalue/CustomerValueDtos.java')
controller=text('backend/src/main/java/com/cinebooking/customervalue/AdminCustomerValueController.java')
security=text('backend/src/main/java/com/cinebooking/config/SecurityConfig.java')
page=text('frontend/app/admin/customer-value/page.tsx')
types=text('frontend/lib/types.ts')
header=text('frontend/components/Header.tsx')
admin=text('frontend/app/admin/page.tsx')
e2e=text('frontend/e2e/customer-value-v56.spec.ts')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v56.ps1')
readme=text('README.md')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
seed_verify=text('tools/verify_seed_demo_57.py')
v55verify=text('tools/verify_v55_customer_retention.py')

check('V56 is a no-schema customer-value release', not (ROOT/'backend/src/main/resources/db/migration/V56__customer_value_rfm_intelligence_3.sql').exists())
check('V52 remains latest Flyway migration under V56', (ROOT/'backend/src/main/resources/db/migration/V52__pwa_mobile_experience_3.sql').exists() and 'assertThat(latest).isEqualTo("52")' in integration)
check('V56 keeps the 57-table data contract', 'Final verification enumerates all 57 pgAdmin tables' in seed_verify and 'pwa_device' in seed_verify)
check('V55 verifier remains forward-compatible with V56 source', 'int(current_match.group(1))>=55' in v55verify and '>=55' in v55verify)
check('Customer-value DTOs expose scorecard RFM value-band and privacy-safe row contracts', all(x in dtos for x in ['CustomerValueScorecard','RfmSegment','ValueBand','CustomerValueRow','customerRef','top10RevenueShare']))
check('Customer-value controller exposes cinema and scorecard endpoints', '@RequestMapping("/api/admin/customer-value")' in controller and '@GetMapping("/cinemas")' in controller and '@GetMapping("/scorecard")' in controller)
check('Security allows Manager/Admin into V56 before generic admin rule', '.requestMatchers("/api/admin/customer-value/**").hasAnyRole("MANAGER","ADMIN")' in security and security.index('/api/admin/customer-value/**') < security.index('/api/admin/**'))
check('V56 service restricts access to Manager/Admin', 'actor.getRole() != Role.ADMIN && actor.getRole() != Role.MANAGER' in service and 'Customer Value & RFM Intelligence' in service)
check('Manager customer-value scope is locked to assigned cinema', 'Manager chỉ xem Customer Value & RFM Intelligence của rạp mình' in service and 'managerCinema(actor)' in service)
check('Admin can use all-cinema or explicit cinema value scope', 'actor.getRole() == Role.ADMIN' in service and 'requestedCinemaId' in service and 'Toàn hệ thống' in service)
check('V56 supports deterministic 90 and 365 day active windows', 'ALLOWED_PERIOD_DAYS = List.of(90, 365)' in service and 'validatePeriod(periodDays)' in service)
check('V56 uses Asia Ho Chi Minh business dates', 'ZoneId.of("Asia/Ho_Chi_Minh")' in service and 'LocalDate.now(BUSINESS_ZONE)' in service)
check('Customer value excludes operator accounts', service.count("u.role='USER'") >= 2)
check('Customer value attributes activity to original purchaser', service.count('b.purchaser_user_id') >= 4)
check('Active-base membership uses confirmed bookings only', "b.status='CONFIRMED'" in service and 'b.confirmed_at is not null' in service and 'select distinct customer_id from confirmed where booking_date>=? and booking_date<?' in service)
check('Monetary value uses successful payments only', "p.status='SUCCESS'" in service and 'p.paid_at is not null' in service)
check('Period revenue uses payment business date and safe placeholders', "date(p.paid_at at time zone 'Asia/Ho_Chi_Minh')>=?" in service and "date(p.paid_at at time zone 'Asia/Ho_Chi_Minh')<?" in service)
check('Lifetime metrics remain branch-scoped for selected cinema', service.count('String scopeFilter = cinemaId == null ? "" : " and a.cinema_id=?"') >= 2 and service.count('if (cinemaId != null) args.add(cinemaId)') >= 3)
check('Lifetime booking dates and frequency come from confirmed history', 'min(booking_date) first_date,max(booking_date) last_date,count(*) lifetime_bookings' in service)
check('Lifetime revenue is realized and left joins zero-value confirmed customers', 'coalesce(sum(p.amount),0) lifetime_revenue' in service and 'left join paid p on p.customer_id=x.customer_id' in service and 'coalesce(p.lifetime_revenue,0)' in service)
check('RFM recency derives from last confirmed booking date', 'ChronoUnit.DAYS.between(row.lastDate(), today)' in service)
check('RFM scores use deterministic relative quintiles', 'quintileScores' in service and 'Math.floor((double) index * 5.0 / count)' in service and service.count('quintileScores(raw') == 3)
check('RFM scoring gives low recency high rank and high frequency/monetary high rank', 'Comparator.comparingLong((CustomerMetricRaw row) -> recencyDays(row, today))' in service and 'Comparator.comparingLong(CustomerMetricRaw::lifetimeBookings).reversed()' in service and 'Comparator.comparing(CustomerMetricRaw::lifetimeRevenue).reversed()' in service)
check('V56 exposes transparent mutually ordered RFM segments', all(x in service for x in ['CHAMPIONS','LOYAL','NEW_RECENT','HIGH_VALUE','NEEDS_ATTENTION','DEVELOPING']) and 'if (r >= 4 && f >= 4 && m >= 4)' in service)
check('New recent segment requires one booking and recency <=30', 'row.lifetimeBookings() == 1 && recencyDays <= 30' in service)
check('Needs-attention segment is rule-based not predictive', 'r <= 2 && (f >= 3 || m >= 3)' in service and 'không gán nhãn rời bỏ' in service)
check('Value bands rank realized revenue into top next middle and long-tail bands', all(x in service for x in ['TOP_10','NEXT_15','MIDDLE_25','LONG_TAIL']) and 'percentile <= 0.10' in service and 'percentile <= 0.25' in service and 'percentile <= 0.50' in service)
check('Top 10 percent concentration is divide-by-zero safe', 'if (rows.isEmpty() || totalRevenue.signum() <= 0) return 0.0' in service and 'Math.ceil(rows.size() * 0.10)' in service)
check('Average lifetime revenue and frequency are divide-by-zero safe', 'averageMoney(activeBaseLifetimeRevenue, scored.size())' in service and 'averageCount(lifetimeBookings, scored.size())' in service and 'if (count <= 0)' in service)
check('Median recency handles empty odd and even active sets', 'if (rows.isEmpty()) return 0.0' in service and 'values.size() % 2 == 1' in service)
check('V56 top-customer rows are pseudonymous', 'return "KH-" + customerId.toString().substring(0, 8)' in service and 'email' not in dtos.lower() and 'phone' not in dtos.lower())
check('V56 top customer list is bounded', 'rows.stream().limit(20)' in service)
check('V56 customer-value service is read-only', 'jdbc.update(' not in service and 'jdbc.batchUpdate(' not in service and 'jdbc.execute(' not in service)
check('V56 uses unambiguous two-argument RowMapper callbacks', service.count('(rs, rowNum) ->') >= 2 and '(RowCallbackHandler)' not in service)
check('Frontend V56 page exposes Customer Value source marker', 'Customer Value & RFM Intelligence · V56' in page and 'customer-value-intelligence-v56' in page)
check('Frontend supports Admin cinema filter and Manager fixed branch scope', 'customer-value-cinema-filter-v56' in page and 'profile.role==="MANAGER"' in page and 'me?.role==="ADMIN"' in page)
check('Frontend supports 90 and 365 day active windows', 'customer-value-period-v56' in page and '<option value={90}>90 ngày</option>' in page and '<option value={365}>365 ngày</option>' in page)
check('Frontend renders summary RFM bands and top customer sections', all(x in page for x in ['customer-value-summary-v56','customer-value-rfm-v56','customer-value-bands-v56','customer-value-top-v56']))
check('Frontend documents honest realized-value semantics', all(x in page for x in ['realized customer value','không phải dự đoán CLV tương lai','không phải dự đoán CLV tương lai hay điểm churn AI','payment SUCCESS']))
check('Frontend documents privacy-safe customer references', 'privacy-safe reference' in page and 'không email/số điện thoại' in page)
check('Frontend types include V56 customer-value contracts', all(x in types for x in ['CustomerValueCinemaV56','CustomerValueRfmSegmentV56','CustomerValueBandV56','CustomerValueRowV56','CustomerValueScorecardV56']))
check('Header exposes V56 Customer Value to Manager/Admin menus', header.count('/admin/customer-value') >= 4)
check('Admin dashboard links V56 Customer Value', '/admin/customer-value' in admin and 'Customer Value V56' in admin)
check('V56 Playwright covers summary RFM bands period and cinema filters', all(x in e2e for x in ['V56 admin reviews privacy-safe realized customer value and RFM by cinema','customer-value-summary-v56','customer-value-rfm-v56','customer-value-bands-v56','customer-value-period-v56','customer-value-cinema-filter-v56']))
ci_match=re.search(r'name:\s*V26-V(\d+) source regression',ci)
check('Main CI extends source regression through V56', bool(ci_match) and int(ci_match.group(1))>=56 and 'verify_v56_customer_value_rfm.py' in ci)
rc_versions=[int(v) for v in re.findall(r'default: "v(\d+)\.0\.0-rc\.1"',rc)]
check('Standalone RC defaults to V56-or-newer and runs V56 gate', bool(rc_versions) and max(rc_versions)>=56 and 'verify_v56_customer_value_rfm.py' in rc)
release_versions=[int(v) for v in re.findall(r'default: "(\d+)\.0\.0"',release)]
check('Stable release defaults to V56-or-newer and runs V56 gate', bool(release_versions) and max(release_versions)>=56 and 'verify_v56_customer_value_rfm.py' in release)
rc_namespaces=[int(v) for v in re.findall(r'cinebooking_v(\d+)_rc_',rc)]
release_namespaces=[int(v) for v in re.findall(r'cinebooking_v(\d+)_release_',release)]
check('Release compose project namespaces remain V56-or-newer', bool(rc_namespaces) and max(rc_namespaces)>=56 and bool(release_namespaces) and max(release_namespaces)>=56)
check('Makefile exposes V56 verify diagnose and unchanged 57-table lifecycle', all(x in make for x in ['verify-v56:','diagnose-v56:','verify-seed-demo-v56:','check-seed-demo-v56:','verify-reference-v56:','seed-reference-v56:']))
check('V56 diagnostics chain V55 V56 and 57-table verifier', all(x in diagnose for x in ['verify_v55_customer_retention.py','verify_v56_customer_value_rfm.py','verify_seed_demo_57.py','V56 source diagnostics passed.']))
current_match=re.search(r'^# CineBooking Pro V(\d+)',readme,re.M)
check('README identifies V56 Customer Value release', bool(current_match) and int(current_match.group(1))>=56 and 'V56 - Customer Value & RFM Intelligence 3.0' in readme)
check('README states V56 is read-only no-schema and keeps 57 public tables', 'V56 không tạo migration Flyway mới' in readme and '57 public tables' in readme and 'customer value analytics read-only' in readme)
check('README documents realized value RFM privacy and no predictive CLV', all(x in readme for x in ['realized lifetime revenue','RFM','không dự đoán CLV tương lai','KH-']))
check('README release lifecycle defaults to v56.0.0-rc.1 and v56.0.0', 'v56.0.0-rc.1' in readme and 'v56.0.0' in readme)

passed=sum(ok for _,ok in checks)
print(f"\nV56 verification: {passed}/{len(checks)} checks passed")
raise SystemExit(0 if passed==len(checks) else 1)
