from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

migration=text('backend/src/main/resources/db/migration/V52__pwa_mobile_experience_3.sql')
entity=text('backend/src/main/java/com/cinebooking/domain/PwaDevice.java')
repo=text('backend/src/main/java/com/cinebooking/notification/PwaDeviceRepository.java')
dtos=text('backend/src/main/java/com/cinebooking/notification/PwaDtos.java')
service=text('backend/src/main/java/com/cinebooking/notification/PwaDeviceService.java')
controller=text('backend/src/main/java/com/cinebooking/notification/PwaController.java')
sender=text('backend/src/main/java/com/cinebooking/notification/WebPushSender.java')
push_delivery=text('backend/src/main/java/com/cinebooking/notification/WebPushDeliveryService.java')
notifications=text('backend/src/main/java/com/cinebooking/notification/NotificationService.java')
ticket=text('backend/src/main/java/com/cinebooking/ticket/TicketController.java')
security=text('backend/src/main/java/com/cinebooking/config/SecurityConfig.java')
yml=text('backend/src/main/resources/application.yml')
env=text('.env.example')
compose=text('docker-compose.yml')
pwa=text('frontend/lib/pwa.ts')
offline=text('frontend/lib/offlineTickets.ts')
sw=text('frontend/public/sw.js')
manifest=text('frontend/public/manifest.webmanifest')
manager=text('frontend/components/PwaManager.tsx')
mobile=text('frontend/app/mobile/page.tsx')
offline_ui=text('frontend/app/offline-tickets/page.tsx')
ticket_ui=text('frontend/app/ticket/[bookingId]/page.tsx')
notifications_ui=text('frontend/app/notifications/page.tsx')
header=text('frontend/components/Header.tsx')
api=text('frontend/lib/api.ts')
types=text('frontend/lib/types.ts')
css=text('frontend/app/globals.css')
e2e=text('frontend/e2e/pwa-mobile-v52.spec.ts')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
seed=text('tools/seed-demo-57-tables-10-rows.sql')
seed_verify=text('tools/verify_seed_demo_57.py')
vapid_tool=text('tools/VapidKeyGenerator.java')
vapid_ps=text('tools/generate-vapid-keys.ps1')
ci=text('.github/workflows/ci.yml');rc=text('.github/workflows/release-candidate.yml');release=text('.github/workflows/release.yml')
make=text('Makefile');diagnose=text('tools/diagnose-v52.ps1');readme=text('README.md')

check('V52 migration creates durable PWA device table', 'CREATE TABLE pwa_device' in migration and 'uq_pwa_device_key' in migration)
check('V52 device schema keeps real PushSubscription credential fields nullable', all(x in migration for x in ['push_endpoint TEXT','p256dh TEXT','auth_secret TEXT']))
check('V52 migration requires credentials only when push is enabled', 'ck_pwa_device_push_credentials' in migration and 'push_enabled = FALSE' in migration)
check('V52 migration indexes endpoint and per-user device reads', all(x in migration for x in ['uq_pwa_device_push_endpoint','idx_pwa_device_user_seen','idx_pwa_device_user_push']))
check('PwaDevice entity maps lifecycle push and failure metadata', '@Table(name="pwa_device"' in entity and all(x in entity for x in ['pushEndpoint','authSecret','failureCount','lastSeenAt','lastPushAt','lastFailureAt']))
check('PWA repository supports device endpoint and active-push lookups', all(x in repo for x in ['findByDeviceKey','findByPushEndpoint','findByUserIdOrderByLastSeenAtDesc','findByUserIdAndPushEnabledTrueOrderByLastSeenAtDesc']))
check('PWA DTOs expose config registration and safe device response without push secrets', all(x in dtos for x in ['PushConfig','DeviceRegistration','DeviceResponse']) and 'pushEndpoint' not in dtos.split('DeviceResponse',1)[1])
check('PWA config reports VAPID background or foreground fallback honestly', 'VAPID_BACKGROUND' in service and 'FOREGROUND_FALLBACK' in service and 'webPushReady()' in service)
check('PWA registration refuses requested push when server VAPID is unavailable', 'Web Push chưa được cấu hình VAPID' in service and 'HttpStatus.CONFLICT' in service)
check('PWA registration validates real subscription fields and rejects private SSRF endpoints', 'Thiếu PushSubscription endpoint/p256dh/auth' in service and all(x in service for x in ['validatePushEndpoint(request.endpoint())','validateSubscriptionKeys(request.p256dh(),request.authSecret())','\"https\".equalsIgnoreCase','isLoopbackAddress()','isLinkLocalAddress()','isSiteLocalAddress()','uniqueLocalV6']))
check('PWA service prevents cross-account device-key or push-endpoint takeover', 'findByPushEndpoint' in service and 'PushSubscription đã thuộc thiết bị của tài khoản khác' in service and 'deviceKey đã thuộc tài khoản khác' in service and 'other.setPushEndpoint(null)' in service)
check('PWA device remove and seen operations enforce ownership', service.count('Thiết bị không thuộc tài khoản hiện tại') >= 2)
check('PWA controller exposes authenticated config device register seen and remove endpoints', '@RequestMapping("/api/pwa")' in controller and all(x in controller for x in ['@GetMapping("/config")','@GetMapping("/devices")','@PutMapping("/devices/{deviceKey}")','@PostMapping("/devices/{deviceKey}/seen")','@DeleteMapping("/devices/{deviceKey}")']))
check('Security keeps PWA API behind authenticated fallback', 'anyRequest().authenticated()' in security and '/api/pwa/**' not in security)
check('Web Push sender performs P-256 ECDH and RFC8291 HKDF derivation', all(x in sender for x in ['KeyAgreement.getInstance("ECDH")','WebPush: info\\0','Content-Encoding: aes128gcm\\0','Content-Encoding: nonce\\0']))
check('Web Push sender encrypts aes128gcm payloads with AES GCM and record delimiter', 'AES/GCM/NoPadding' in sender and 'plain[plain.length-1]=0x02' in sender and 'RECORD_SIZE=4096' in sender)
check('Web Push sender signs VAPID JWT with ES256 and converts DER to JOSE signature', 'SHA256withECDSA' in sender and 'ES256' in sender and 'derToJose' in sender and 'vapid t=' in sender)
check('Web Push sender rejects redirects and treats 404/410 as expired subscriptions', 'HttpClient.Redirect.NEVER' in sender and 'status==404||status==410' in sender)
check('Web Push delivery disables repeatedly failing or gone subscriptions', 'result.gone()||device.getFailureCount()>=5' in push_delivery and 'device.setPushEnabled(false)' in push_delivery)
check('Notification creation dispatches background push only after transaction commit', 'afterCommit' in notifications and 'webPush.deliver' in notifications and 'Boolean.TRUE.equals(pref.getBrowserEnabled())' in notifications)
check('V52 runtime config defaults Web Push OFF until real keys are supplied', 'enabled: ${WEB_PUSH_ENABLED:false}' in yml and 'WEB_PUSH_ENABLED=false' in env)
check('V52 runtime exposes VAPID key subject and TTL settings to both backend replicas', all(x in yml for x in ['vapid-public-key','vapid-private-key','subject:','ttl-seconds:']) and 'WEB_PUSH_VAPID_PUBLIC_KEY:' in compose and '&backend_env' in compose and 'environment: *backend_env' in compose)
check('VAPID generator creates P-256 public and private base64url values without saving secrets', 'secp256r1' in vapid_tool and 'VAPID_PUBLIC_KEY' in vapid_tool and 'VAPID_PRIVATE_KEY' in vapid_tool and 'VapidKeyGenerator.java' in vapid_ps and '& java' in vapid_ps)
check('Frontend PWA helper creates a durable random device key and detects standalone mode', 'cinebooking_pwa_device_v52' in pwa and 'crypto.randomUUID()' in pwa and 'display-mode: standalone' in pwa)
check('Frontend PWA helper checks PushManager support before subscribing', 'if(!pushManager)throw new Error' in pwa and 'pushManager.subscribe' in pwa)
check('Frontend PWA helper sends real browser PushSubscription fields only when present', 'subscription.toJSON()' in pwa and 'fields.p256dh' in pwa and 'fields.authSecret' in pwa)
check('Logout unsubscribes browser push and removes server PWA device before auth logout', 'subscription.unsubscribe()' in api and 'cinebooking_pwa_device_v52' in api and '/pwa/devices/' in api and '/auth/logout' in api)
check('Service Worker V52 explicitly never caches API responses', 'const VERSION = "v52"' in sw and 'if (url.pathname.startsWith("/api/")) return;' in sw)
check('Service Worker V52 keeps authenticated private navigation out of runtime cache', 'PRIVATE_NAV_PREFIXES' in sw and 'privateNavigation(request)' in sw and '!isPrivateNavigation(url.pathname)' in sw)
check('Service Worker V52 has bounded shell runtime and image caches', all(x in sw for x in ['trimCache(RUNTIME_CACHE,40)','trimCache(RUNTIME_CACHE,60)','trimCache(IMAGE_CACHE,80)']))
check('Service Worker handles background push notification display and click navigation', 'self.addEventListener("push"' in sw and 'showNotification' in sw and 'self.addEventListener("notificationclick"' in sw and 'openWindow' in sw)
check('Service Worker forwards push delivery to open clients to avoid duplicate foreground alerts', 'CINEBOOKING_PUSH_DELIVERED' in sw and 'client.postMessage' in sw)
check('PWA manager registers V52 Service Worker without stale script caching and refreshes device presence', 'updateViaCache:"none"' in manager and 'registerCurrentPwaDevice()' in manager and '5*60*1000' in manager)
check('Manifest starts PWA with source marker and links Mobile Center shortcut', '"start_url": "/?source=pwa"' in manifest and '"url": "/mobile"' in manifest and '"prefer_related_applications": false' in manifest)
check('V52 offline ticket schema tracks ticket version sync state and validation time', 'ticketVersion:' in offline and 'syncState:' in offline and 'lastValidatedAt:' in offline and 'DB_VERSION = 2' in offline)
check('Offline sync revalidates booking ticket and QR against authenticated APIs', all(x in offline for x in ['`/bookings/${current.bookingId}`','`/tickets/${current.bookingId}`','`/tickets/${current.bookingId}/qr`']))
check('Offline sync marks revoked transferred refunded or missing tickets stale', 'syncState:"STALE"' in offline and '[403,404,409].includes(error.status)' in offline)
check('Offline ticket list is scoped to the current authenticated owner', 'listOfflineTickets(auth.userId)' in offline_ui and 'getAuth()' in offline_ui)
check('Ticket page hides stale offline QR and requires cached owner match', 'staleOffline' in ticket_ui and 'qrDataUrl&&!staleOffline' in ticket_ui and 'cached.ownerUserId===auth.userId' in ticket_ui)
check('Ticket API exposes ticketVersion so offline snapshots detect QR rotation', 'ticketVersion' in ticket and 'getTicketVersion()' in ticket and 'ticketVersion:number' in types)
check('Mobile Center identifies V52, registers the current browser before listing devices, and exposes push offline sync storage and device management', 'PWA / MOBILE · V52' in mobile and 'await registerCurrentPwaDevice()' in mobile and mobile.index('await registerCurrentPwaDevice()') < mobile.index('listPwaDevices()') and all(x in mobile for x in ['pwa-push-v52','offline-sync-v52','pwa-devices-v52','persistent storage']))
check('Notification Center bridges browser preference to V52 Web Push and honest fallback', 'registerCurrentPwaDevice({subscribe:true})' in notifications_ui and 'Background Web Push V52' in notifications_ui and 'foreground fallback' in notifications_ui)
check('Header receives Service Worker push events and links authenticated mobile center', 'CINEBOOKING_PUSH_DELIVERED' in header and 'cinebooking-push-delivered' in header and 'href="/mobile"' in header)
check('Mobile CSS improves touch targets safe areas and sticky booking action', 'env(safe-area-inset-bottom)' in css and 'min-height:44px' in css and 'position:sticky' in css)
check('Dedicated V52 Playwright verifies real device registration with push fallback and offline center', all(x in e2e for x in ['V52 PWA registers a real browser device','FOREGROUND_FALLBACK','pwa-devices-v52','Vé offline đã kiểm soát']))
check('V52 reference seed covers pwa_device without fake PushSubscription credentials', 'seed52:pwa-device:' in seed and 'push_enabled=FALSE' in seed and 'must not contain fabricated Web Push credentials' in seed)
check('V52 reference seed survives pre-existing natural-key rows', 'ON CONFLICT (cinema_id,period_kind,period_start) DO UPDATE SET\n    id=EXCLUDED.id' in seed and 'ON CONFLICT (device_key) DO UPDATE SET\n    id=EXCLUDED.id' in seed)
check('V52 57-table realistic-data verifier is wired', 'Final verification enumerates all 57 pgAdmin tables' in seed_verify and 'pwa_device' in seed_verify and '44/44' not in seed_verify)
check('Integration test covers Flyway V52 schema and push-disabled device API contract', 'flywayMigratesRealPostgresToV52PwaMobileExperienceSchemaAndCatalog' in integration and 'assertThat(latest).isEqualTo("52")' in integration and 'isGreaterThanOrEqualTo(57)' in integration and 'pwaV52Columns' in integration and 'pwaV52Indexes' in integration and 'pwaV52RegistersDeviceWithoutFabricatingPushCredentialsWhenVapidIsDisabled' in integration and 'unsafeCredentials' in integration)
check('Main CI includes V52 source and 57-table reference gates', 'V26-V52 source regression' in ci and 'verify_v52_pwa_mobile_3.py' in ci and 'verify_seed_demo_57.py' in ci)
check('Standalone RC defaults to V52 and runs V52 gate', 'v52.0.0-rc.1' in rc and 'cinebooking_v52_rc_' in rc and 'verify_v52_pwa_mobile_3.py' in rc and 'verify_seed_demo_57.py' in rc)
check('Stable release defaults to 52.0.0 and runs V52 gate', 'default: "52.0.0"' in release and 'cinebooking_v52_release_' in release and 'verify_v52_pwa_mobile_3.py' in release and 'verify_seed_demo_57.py' in release)
check('Makefile diagnostics and README expose complete V52 lifecycle', all(x in make for x in ['verify-v52:','diagnose-v52:','seed-demo-v52:','verify-reference-v52:','seed-reference-v52:']) and 'verify_v52_pwa_mobile_3.py' in diagnose and 'V52 - PWA / Mobile Experience 3.0' in readme and 'V52__pwa_mobile_experience_3.sql' in readme)

passed=sum(ok for _,ok in checks)
print(f"\nV52 verification: {passed}/{len(checks)} checks passed")
raise SystemExit(0 if passed==len(checks) else 1)
