from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

service=text('backend/src/main/java/com/cinebooking/operationscontrol/OperationsControlCenterService.java')
state=text('backend/src/main/java/com/cinebooking/operationscontrol/OperationsAlertStateService.java')
dtos=text('backend/src/main/java/com/cinebooking/operationscontrol/OperationsControlCenterDtos.java')
controller=text('backend/src/main/java/com/cinebooking/operationscontrol/AdminOperationsControlCenterController.java')
signal=text('backend/src/main/java/com/cinebooking/websocket/OperationsSignalPublisher.java')
subscriber=text('backend/src/main/java/com/cinebooking/websocket/RedisOperationsControlEventSubscriber.java')
redis_config=text('backend/src/main/java/com/cinebooking/config/RedisPubSubConfig.java')
audit=text('backend/src/main/java/com/cinebooking/audit/AuditService.java')
audit_repo=text('backend/src/main/java/com/cinebooking/audit/AuditLogRepository.java')
payment_events=text('backend/src/main/java/com/cinebooking/payment/PaymentEventService.java')
booking=text('backend/src/main/java/com/cinebooking/booking/BookingService.java')
inventory=text('backend/src/main/java/com/cinebooking/commerce/InventoryService.java')
security=text('backend/src/main/java/com/cinebooking/config/SecurityConfig.java')
ws_config=text('backend/src/main/java/com/cinebooking/config/WebSocketConfig.java')
page=text('frontend/app/admin/operations-control/page.tsx')
types=text('frontend/lib/types.ts')
e2e=text('frontend/e2e/realtime-operations-v59.spec.ts')
package=text('frontend/package.json')
header=text('frontend/components/Header.tsx')
admin=text('frontend/app/admin/page.tsx')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v59.ps1')
readme=text('README.md')
seed_verify=text('tools/verify_seed_demo_57.py')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')

check('V59 is no-schema and keeps Flyway V52 latest', not any((ROOT/'backend/src/main/resources/db/migration').glob('V59__*.sql')) and (ROOT/'backend/src/main/resources/db/migration/V52__pwa_mobile_experience_3.sql').exists())
check('V59 preserves 57 public-table contract', 'Final verification enumerates all 57 pgAdmin tables' in seed_verify and 'assertThat(latest).isEqualTo("52")' in integration)
check('V59 reuses existing Spring WebSocket endpoint', '@EnableWebSocketMessageBroker' in ws_config and 'addEndpoint("/ws")' in ws_config)
check('Frontend already pins STOMP client dependency', '"@stomp/stompjs"' in package)

check('Operations signal publisher exists', 'class OperationsSignalPublisher' in signal)
check('Operations signal publisher uses Redis Pub/Sub', 'StringRedisTemplate' in signal and 'convertAndSend' in signal)
check('Operations signal publisher uses dedicated channel', 'cinebooking:operations-control-events' in signal)
check('Operations signal waits for transaction commit when possible', 'afterCommit()' in signal and 'TransactionSynchronizationManager' in signal)
check('Operations subscriber exists', 'class RedisOperationsControlEventSubscriber' in subscriber)
check('Operations subscriber sends STOMP topic', '"/topic/operations-control"' in subscriber and 'convertAndSend' in subscriber)
check('Operations event payload carries only type and time', 'record Event(String type, Instant at)' in subscriber)
check('Redis listener container subscribes operations channel', 'RedisOperationsControlEventSubscriber' in redis_config and 'OperationsSignalPublisher.CHANNEL' in redis_config)

check('AuditService injects operations signal publisher', 'OperationsSignalPublisher operationsSignals' in audit)
check('AuditService excludes generic ADMIN reads from realtime loop', 'action.startsWith("ADMIN_")' in audit)
check('AuditService excludes OPS alert audit actions from feedback loop', 'action.startsWith("OPS_ALERT_")' in audit)
for prefix in ['BOOKING_','PAYMENT_','REFUND_','MAINTENANCE_','SUPPORT_','SHIFT_','STAFF_','INVENTORY_']:
    check(f'AuditService forwards {prefix} operational actions', f'action.startsWith("{prefix}")' in audit)
check('AuditService publishes only after durable audit save path', 'logs.save(l);' in audit and 'operationsSignals.publish("AUDIT:" + action)' in audit)
check('BookingService emits realtime lifecycle signals', 'OperationsSignalPublisher operationsSignals' in booking and all(x in booking for x in ['BOOKING:CREATED','BOOKING:CONFIRMED','BOOKING:'+chr(34)+'+finalStatus.name()']))
check('PaymentEventService emits realtime signal', 'OperationsSignalPublisher operationsSignals' in payment_events and 'operationsSignals.publish("PAYMENT:"+eventType)' in payment_events)
check('InventoryService emits realtime signal from persisted movement', 'movements.save(m);operationsSignals.publish("INVENTORY:"+type)' in inventory)

for field in ['fingerprint','effectiveSeverity','state','firstSeenAt','stateChangedAt','stateActor','escalated']:
    check(f'V59 alert DTO exposes {field}', field in dtos)
check('V59 snapshot advertises realtime transport', 'realtimeTransport' in dtos and 'realtimeTopic' in dtos)
check('V59 keeps pollAfterSeconds for fallback compatibility', 'pollAfterSeconds' in dtos)
check('V59 DTO exposes alert action request', 'record AlertActionRequest' in dtos)
check('V59 DTO exposes alert history item', 'record AlertHistoryItem' in dtos)

check('Alert state uses Redis key namespace', 'cinebooking:ops-alert:' in state)
check('Alert state has 24h Redis lifecycle', 'Duration.ofHours(24)' in state)
check('Acknowledgement window is 60 minutes', 'Duration.ofMinutes(60)' in state)
check('Resolve cooldown is 15 minutes', 'Duration.ofMinutes(15)' in state)
check('Escalation threshold is 10 minutes', 'Duration.ofMinutes(10)' in state)
check('Alert states include OPEN ACKNOWLEDGED RESOLVED', all(x in state for x in ['"OPEN"','"ACKNOWLEDGED"','"RESOLVED"']))
check('Escalation raises HIGH to CRITICAL', 'case "HIGH" -> "CRITICAL"' in state)
check('Escalation raises MEDIUM to HIGH', 'case "MEDIUM" -> "HIGH"' in state)
check('Escalation raises LOW to MEDIUM', 'case "LOW" -> "MEDIUM"' in state)
check('ACK action is durably audited', 'OPS_ALERT_ACKNOWLEDGE' in state and 'audit.record' in state)
check('Resolve action is durably audited', 'OPS_ALERT_RESOLVE' in state and 'audit.record' in state)
check('Alert actions explicitly publish realtime signal', 'signals.publish(action)' in state)
check('Alert history reads existing audit_log repository', 'findTop100ByEntityTypeOrderByCreatedAtDesc("OPERATIONS_ALERT")' in state)
check('Audit repository supports global operations-alert history', 'findTop100ByEntityTypeOrderByCreatedAtDesc' in audit_repo)

check('Operations snapshot uses 30-second fallback', 'FALLBACK_REFRESH_SECONDS = 30' in service)
check('Operations snapshot advertises STOMP websocket', '"STOMP_WEBSOCKET"' in service and 'REALTIME_TOPIC' in service)
check('Operations alert fingerprint is stable and scope-aware', 'UUID.nameUUIDFromBytes' in service and 'scopeKey + "|" + domain + "|" + title + "|" + href' in service and 'ALL_CINEMAS' in service)
check('Operations service decorates alerts with realtime state', 'alertStates.decorate(raw)' in service)
check('Operations overall status uses effective severity', 'effectiveSeverity()' in service)
check('Resolved alerts do not keep global status critical', 'filter(a -> !"RESOLVED".equals(a.state()))' in service)
check('Operations service exposes acknowledge action', 'public Snapshot acknowledge' in service and 'alertStates.acknowledge' in service)
check('Operations service exposes resolve action', 'public Snapshot resolve' in service and 'alertStates.resolve' in service)
check('Operations action validates alert in current scoped snapshot', 'requireVisibleAlert' in service and 'snapshot(email, cinemaId).alerts()' in service)
check('Operations history is restricted to visible fingerprints', 'Set<String> visible' in service and 'alertStates.history(visible)' in service)
check('V59 keeps all seven V58 operational domains', all(f'pulse("{d}"' in service for d in ['PAYMENT','BOOKING','EQUIPMENT','STAFF','SUPPORT','INVENTORY','INCIDENT']))

check('Controller keeps V58 snapshot endpoint', '@GetMapping("/snapshot")' in controller)
check('Controller exposes alert acknowledge endpoint', '@PostMapping("/alerts/{fingerprint}/acknowledge")' in controller)
check('Controller exposes alert resolve endpoint', '@PostMapping("/alerts/{fingerprint}/resolve")' in controller)
check('Controller exposes alert history endpoint', '@GetMapping("/alerts/history")' in controller)
check('Operations API remains Manager/Admin protected', '"/api/admin/operations-control/**"' in security and 'hasAnyRole("MANAGER","ADMIN")' in security)

check('V59 frontend imports STOMP Client', 'import { Client } from "@stomp/stompjs"' in page)
check('V59 frontend has roadmap marker', 'Realtime Operations · V59' in page and 'operations-control-center-v59' in page)
check('V59 frontend preserves V58 browser contract', 'operations-control-center-v58' in page and 'Operations Control Center · V58' in page)
check('V59 frontend connects /ws', 'brokerURL:`${scheme}://${location.host}/ws`' in page)
check('V59 frontend subscribes operations topic', 'client.subscribe("/topic/operations-control"' in page)
check('V59 frontend enables websocket reconnect', 'reconnectDelay:2000' in page)
check('V59 frontend debounces burst events', 'setTimeout(()=>{' in page and '250' in page)
check('V59 frontend tracks connection state', 'operations-control-realtime-v59' in page and 'WebSocket:' in page)
check('V59 frontend keeps fallback refresh switch', 'operations-control-auto-refresh-v58' in page and 'data.pollAfterSeconds' in page and 'setInterval' in page)
check('V59 frontend exposes acknowledge action', 'action:"acknowledge"|"resolve"' in page and 'alertAction(item.fingerprint,"acknowledge")' in page and 'Tiếp nhận' in page)
check('V59 frontend exposes resolve action', 'alertAction(item.fingerprint,"resolve")' in page and 'Đánh dấu đã xử lý' in page)
check('V59 frontend renders alert action history', 'operations-control-history-v59' in page and '/alerts/history' in page)
check('V59 frontend displays escalation badge', 'ESCALATED' in page and 'item.escalated' in page)
check('V59 frontend displays Redis/audit lifecycle copy', 'ACK giữ trạng thái 60 phút' in page and 'Resolve suppress 15 phút' in page)
check('V59 TS contracts exist', all(x in types for x in ['OperationsControlAlertStateV59','OperationsControlAlertV59','OperationsControlHistoryV59','OperationsControlSnapshotV59']))
check('Admin dashboard links Realtime Operations V59', '/admin/operations-control' in admin and 'Realtime Operations V59' in admin)
check('Header exposes Realtime Operations V59', header.count('/admin/operations-control')>=4 and 'Realtime Operations V59' in header)

check('V59 Playwright journey exists', 'V59 admin receives websocket operations signals and manages alert state' in e2e)
check('V59 Playwright waits for WebSocket connection', 'operations-control-realtime-v59' in e2e and 'WebSocket: Đã kết nối' in e2e)
check('V59 Playwright checks realtime transport contract', 'STOMP_WEBSOCKET' in e2e)
check('V59 Playwright checks alert history', 'operations-control-history-v59' in e2e)
check('V59 Playwright exercises alert acknowledgement when present', 'getByRole("button",{name:/Tiếp nhận/})' in e2e and 'Tiếp nhận cảnh báo' in e2e)
check('V59 Playwright keeps cinema-scope coverage', 'operations-control-cinema-filter-v58' in e2e and 'selectOption({index:1})' in e2e)

ci_match=re.search(r'name:\s*V26-V(\d+) source regression',ci)
check('Main CI source regression extends through V59', bool(ci_match) and int(ci_match.group(1))>=59)
check('Main CI runs V59 source gate', 'Verify V59 Realtime Operations 4.0' in ci and 'verify_v59_realtime_operations_4.py' in ci)
check('RC defaults to V59 RC1', 'default: "v59.0.0-rc.1"' in rc)
check('RC uses V59 compose namespace', 'cinebooking_v59_rc_' in rc)
check('RC runs V59 source gate', 'Verify V59 source gate' in rc and 'verify_v59_realtime_operations_4.py' in rc)
check('RC browser gate label includes V59', '+ V59)' in rc)
check('Stable release defaults to 59.0.0', 'default: "59.0.0"' in release)
check('Stable release uses V59 compose namespace', 'cinebooking_v59_release_' in release)
check('Stable release runs V59 source gate', 'Verify V59 source gate' in release and 'verify_v59_realtime_operations_4.py' in release)
check('Makefile exposes V59 lifecycle', all(x in make for x in ['verify-v59:','diagnose-v59:','verify-seed-demo-v59:','check-seed-demo-v59:','verify-reference-v59:','audit-realistic-data-v59:']))
check('V59 diagnostics chains V58 V59 and realistic data gates', all(x in diagnose for x in ['verify_v58_operations_control_center.py','verify_v59_realtime_operations_4.py','verify_realistic_data_57.py','V59 source diagnostics passed.']))

check('README current release is V59', readme.startswith('# CineBooking Pro V59') and 'Current release:** V59 - Realtime Operations 4.0' in readme)
check('README history contains V59 row', '**V59**' in readme and 'Redis Pub/Sub + STOMP WebSocket' in readme)
check('README documents event-driven architecture', 'cinebooking:operations-control-events' in readme and '/topic/operations-control' in readme)
check('README documents ACK Resolve and escalation windows', all(x in readme for x in ['ACKNOWLEDGED','RESOLVED','OPEN > 10 phút','suppress 15 phút']))
check('README documents V59 no-schema 57-table contract', 'V59 không tạo Flyway migration mới' in readme and '= 57 public tables' in readme)
check('README documents V59 release tags', 'v59.0.0-rc.1' in readme and 'v59.0.0' in readme)

passed=sum(ok for _,ok in checks)
print(f"\nV59 verification: {passed}/{len(checks)} checks passed")
raise SystemExit(0 if passed==len(checks) else 1)
