from pathlib import Path
import re, sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,ok):
    ok=bool(ok);checks.append((name,ok));print(('PASS' if ok else 'FAIL')+': '+name)

mig=text('backend/src/main/resources/db/migration/V41__notification_engagement_2.sql')
entity=text('backend/src/main/java/com/cinebooking/domain/UserNotification.java')
pref=text('backend/src/main/java/com/cinebooking/domain/NotificationPreference.java')
dtos=text('backend/src/main/java/com/cinebooking/notification/NotificationDtos.java')
repo=text('backend/src/main/java/com/cinebooking/notification/NotificationRepository.java')
svc=text('backend/src/main/java/com/cinebooking/notification/NotificationService.java')
controller=text('backend/src/main/java/com/cinebooking/notification/NotificationController.java')
booking=text('backend/src/main/java/com/cinebooking/booking/BookingService.java')
booking_repo=text('backend/src/main/java/com/cinebooking/booking/BookingRepository.java')
reminder_job=text('backend/src/main/java/com/cinebooking/booking/ShowtimeReminderJob.java')
loyalty=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyService.java')
loyalty_job=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyExpiryJob.java')
app=text('backend/src/main/resources/application.yml')
compose=text('docker-compose.yml')
env=text('.env.example')
types=text('frontend/lib/types.ts')
ui=text('frontend/app/notifications/page.tsx')
e2e=text('frontend/e2e/notification-engagement.spec.ts')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
diag=text('tools/diagnose-v41.ps1')
make=text('Makefile')
readme=text('README.md')
v40=text('tools/verify_v40_loyalty_membership.py')

check('V41 Flyway migration exists', bool(mig))
check('V41 adds priority, read_at and archived_at', all(x in mig for x in ['priority VARCHAR(12)','read_at TIMESTAMPTZ','archived_at TIMESTAMPTZ']))
check('V41 priority is constrained to LOW NORMAL HIGH', "priority IN ('LOW','NORMAL','HIGH')" in mig)
check('Legacy read rows are backfilled with read_at', 'SET read_at = created_at' in mig and 'is_read = TRUE' in mig)
check('V41 adds loyalty and waitlist preferences with safe TRUE defaults', 'loyalty_enabled BOOLEAN NOT NULL DEFAULT TRUE' in mig and 'waitlist_enabled BOOLEAN NOT NULL DEFAULT TRUE' in mig)
check('V41 indexes active notification inbox', 'idx_notification_user_active_created' in mig and 'archived_at IS NULL' in mig)
check('V41 indexes archived notification inbox', 'idx_notification_user_archived_created' in mig and 'archived_at IS NOT NULL' in mig)
check('V41 indexes high-priority unread notifications', 'idx_notification_user_high_unread' in mig and "priority = 'HIGH'" in mig)

check('UserNotification maps readAt and archivedAt', 'readAt' in entity and 'archivedAt' in entity and '@Column(name="read_at")' in entity and '@Column(name="archived_at")' in entity)
check('UserNotification maps V41 priority', '@Column(nullable=false,length=12) private String priority' in entity and 'if(priority==null)priority="NORMAL"' in entity)
check('NotificationPreference maps loyalty and waitlist flags', 'loyaltyEnabled' in pref and 'waitlistEnabled' in pref)
check('New preference flags default enabled in entity', 'if(loyaltyEnabled==null)loyaltyEnabled=true' in pref and 'if(waitlistEnabled==null)waitlistEnabled=true' in pref)

check('Notification DTO exposes priority and archive/read timestamps', all(x in dtos for x in ['String priority','Instant readAt','boolean archived','Instant archivedAt']))
check('Notification summary exposes unread high-priority and archived counts', 'highPriorityUnreadCount' in dtos and 'archivedCount' in dtos)
check('Preference response exposes loyalty and waitlist flags', 'loyaltyEnabled' in dtos and 'waitlistEnabled' in dtos)
check('Preference update keeps new flags nullable for old-client compatibility', 'Boolean loyaltyEnabled,Boolean waitlistEnabled' in dtos and '@NotNull Boolean loyaltyEnabled' not in dtos)

check('Repository separates active and archived inbox queries', 'ArchivedAtIsNullOrderByCreatedAtDesc' in repo and 'ArchivedAtIsNotNullOrderByArchivedAtDesc' in repo)
check('Browser feed excludes archived notifications', 'findTop20ByUserIdAndArchivedAtIsNullAndCreatedAtAfterOrderByCreatedAtAsc' in repo)
check('Unread summary excludes archived notifications', 'ArchivedAtIsNullAndReadFalse' in repo)
check('High-priority unread summary has dedicated repository count', 'ArchivedAtIsNullAndReadFalseAndPriority' in repo)
check('Archived count has dedicated repository count', 'ArchivedAtIsNotNull' in repo)
check('Native dedupe insert persists priority', 'insert into user_notification' in repo and ':priority' in repo and 'on conflict (user_id,dedupe_key)' in repo)
check('Mark-all-read persists readAt timestamp', 'n.readAt=coalesce(n.readAt,:now)' in repo)

check('Notification service lists ACTIVE and ARCHIVED separately', '"ARCHIVED".equalsIgnoreCase(view)' in svc and 'findTop100ByUserIdAndInAppVisibleTrueAndArchivedAtIsNotNullOrderByArchivedAtDesc' in svc)
check('Notification service summary excludes archived and counts HIGH', 'new NotificationSummary' in svc and '"HIGH"' in svc and 'countByUserIdAndInAppVisibleTrueAndArchivedAtIsNotNull' in svc)
check('Read operation sets readAt only when first read', 'if(!Boolean.TRUE.equals(n.getRead()))' in svc and 'n.setReadAt(Instant.now())' in svc)
check('Archive and unarchive operations are owner-scoped', 'NotificationResponse archive' in svc and 'NotificationResponse unarchive' in svc and 'owned(id,uid)' in svc)
check('Archive timestamp is durable', 'n.setArchivedAt(Instant.now())' in svc and 'n.setArchivedAt(null)' in svc)
check('Old-client preference update preserves omitted V41 flags', 'if(req.loyaltyEnabled()!=null)' in svc and 'if(req.waitlistEnabled()!=null)' in svc)
check('Notification categories split LOYALTY from GENERAL', 'return "LOYALTY"' in svc and 't.startsWith("LOYALTY")' in svc and 't.startsWith("BIRTHDAY")' in svc)
check('Notification categories split WAITLIST from BOOKING', 't.startsWith("WAITLIST")' in svc and 'return "WAITLIST"' in svc)
check('Waitlist and loyalty category preferences are independently enforced', 'case "LOYALTY"' in svc and 'getLoyaltyEnabled' in svc and 'case "WAITLIST"' in svc and 'getWaitlistEnabled' in svc)
check('Waitlist notifications are HIGH priority', 't.startsWith("WAITLIST")' in svc and 'return "HIGH"' in svc)
check('Final showtime reminder is HIGH priority', 'SHOWTIME_REMINDER_30M' in svc and 'return "HIGH"' in svc)
check('Promotion traffic can be LOW priority', 't.startsWith("PROMOTION")' in svc and 'return "LOW"' in svc)
check('Notification createOnce remains DB-deduplicated', 'repo.insertOnce' in svc and 'dedupeKey is required' in svc)

check('Notification API supports view parameter', '@RequestParam(defaultValue="ACTIVE") String view' in controller)
check('Notification API exposes archive endpoint', '/{id}/archive' in controller and 's.archive' in controller)
check('Notification API exposes unarchive endpoint', '/{id}/unarchive' in controller and 's.unarchive' in controller)
check('Existing notification read, test, preferences and delete endpoints remain', all(x in controller for x in ['/read','/test','/preferences','@DeleteMapping']))

check('Booking repository limits reminder scan to upcoming unchecked tickets', 'findUpcomingForReminder' in booking_repo and 'join showtime s on s.id=b.showtime_id' in booking_repo and 'b.checked_in_at is null' in booking_repo)
check('Booking service retains legacy reminder entrypoint for compatibility', 'public void sendReminderIfDue(UUID bookingId)' in booking and 'sendEngagementRemindersIfDue(bookingId)' in booking)
check('Booking service has configurable 3h and final reminder windows', 'showtimeReminderHours' in booking and 'showtimeFinalReminderMinutes' in booking)
check('Booking reminders skip checked-in tickets', 'b.getCheckedInAt()!=null' in booking)
check('3-hour showtime reminder uses createOnce dedupe', 'SHOWTIME_REMINDER_3H' in booking and '"SHOWTIME_REMINDER_3H:"+b.getId()' in booking and 'notifications.createOnce' in booking)
check('30-minute showtime reminder uses separate createOnce dedupe', 'SHOWTIME_REMINDER_30M' in booking and '"SHOWTIME_REMINDER_30M:"+b.getId()' in booking)
check('Final reminder marks legacy reminderSent for compatibility', 'b.setReminderSent(true)' in booking)
check('Showtime reminder job scans with configurable delay and horizon', 'showtime-reminder-scan-ms' in reminder_job and 'showtime-reminder-hours' in reminder_job and 'findUpcomingForReminder' in reminder_job)
check('Showtime reminder job invokes V41 engagement reminder service', 'sendEngagementRemindersIfDue' in reminder_job)

check('Loyalty service has V41 engagement sweep', 'public int engagementSweep()' in loyalty)
check('Loyalty engagement sweep uses configured expiring-soon window', 'now.plus(expiringSoonDays,ChronoUnit.DAYS)' in loyalty)
check('Loyalty expiring-soon alert is deduped', 'LOYALTY_EXPIRING_SOON' in loyalty and '"LOYALTY_EXPIRING:"+entry.getKey()+":"+day' in loyalty)
check('Birthday reward availability alert is timezone aware', 'BIRTHDAY_REWARD_AVAILABLE' in loyalty and 'LocalDate.now(ZoneId.of("Asia/Ho_Chi_Minh"))' in loyalty)
check('Birthday alert excludes already-claimed current-year reward', 'Objects.equals(u.getBirthdayRewardYear(),today.getYear())' in loyalty)
check('Birthday alert is deduped per member/year', '"BIRTHDAY_REWARD:"+u.getId()+":"+today.getYear()' in loyalty)
check('Scheduled loyalty job runs expiry and engagement sweeps', 'loyalty.expireSweep();loyalty.engagementSweep();' in loyalty_job)

check('Application config exposes V41 showtime reminder settings', all(x in app for x in ['SHOWTIME_REMINDER_HOURS','SHOWTIME_FINAL_REMINDER_MINUTES','SHOWTIME_REMINDER_SCAN_MS']))
check('Example env documents V41 reminder settings', all(x in env for x in ['SHOWTIME_REMINDER_HOURS=3','SHOWTIME_FINAL_REMINDER_MINUTES=30','SHOWTIME_REMINDER_SCAN_MS=60000']))
check('Docker compose forwards V41 reminder settings', all(x in compose for x in ['SHOWTIME_REMINDER_HOURS','SHOWTIME_FINAL_REMINDER_MINUTES','SHOWTIME_REMINDER_SCAN_MS']))
check('Loyalty expiring-soon configuration remains explicit', 'LOYALTY_EXPIRING_SOON_DAYS=30' in env and 'expiring-soon-days' in app)

check('Frontend notification type exposes priority and archive state', all(x in types for x in ['priority:"LOW"|"NORMAL"|"HIGH"','archived:boolean','archivedAt?:string','readAt?:string']))
check('Frontend preference type exposes loyalty and waitlist flags', 'loyaltyEnabled:boolean' in types and 'waitlistEnabled:boolean' in types)
check('Notification UI identifies itself as V41', 'CINEBOOKING · V41' in ui)
check('Notification UI has Active and Archived views', 'notifications-active-tab' in ui and 'notifications-archived-tab' in ui and 'Hộp thư' in ui and 'Đã lưu trữ' in ui)
check('Notification UI exposes archive/restore control', 'notification-archive-toggle' in ui and 'Khôi phục' in ui and 'Lưu trữ' in ui)
check('Notification UI visually marks HIGH priority', 'n.priority==="HIGH"' in ui and 'ƯU TIÊN' in ui)
check('Notification UI filters WAITLIST and LOYALTY independently', "['WAITLIST','Waitlist']" in ui and "['LOYALTY','Loyalty']" in ui)
check('Notification UI exposes loyalty preference toggle', 'toggle("loyaltyEnabled"' in ui and 'Loyalty & thành viên' in ui)
check('Notification UI exposes waitlist preference toggle', 'toggle("waitlistEnabled"' in ui and '💺 Waitlist' in ui)
check('Notification UI sends V41 preference fields to API', 'loyaltyEnabled:next.loyaltyEnabled' in ui and 'waitlistEnabled:next.waitlistEnabled' in ui)
check('Notification UI loads archive view through server API', '`/notifications?view=${nextView}`' in ui)

check('V41 Playwright journey exists', bool(e2e))
check('V41 E2E creates a real authenticated test notification', '/api/notifications/test' in e2e and 'created.status' in e2e)
check('V41 E2E verifies unread summary state', '/api/notifications/summary' in e2e and 'unreadCount' in e2e)
check('V41 E2E archives notification through UI', 'notification-archive-toggle' in e2e and 'notifications-archived-tab' in e2e)
check('V41 E2E restores notification through UI', 'Khôi phục' in e2e and 'notifications-active-tab' in e2e)
check('V41 E2E verifies final active notification is read', 'restored?.read' in e2e and 'toBe(true)' in e2e)
check('V41 E2E checks new loyalty/waitlist preference labels', '🏆 Loyalty & thành viên' in e2e and '💺 Waitlist' in e2e)
check('V41 E2E uses browser-context API requests instead of navigation-sensitive page.evaluate fetches', 'context.request.fetch' in e2e and 'authResponse.json()' in e2e and 'page.evaluate' not in e2e)

check('Integration test expects Flyway V41 or newer', any(f'isEqualTo("{v}")' in integration for v in range(41,100)) and bool(re.search(r'flywayMigratesRealPostgresToV[4-9][0-9]*', integration)))
check('Integration test validates V41 notification columns', 'notificationV41Columns' in integration and "('priority','read_at','archived_at')" in integration)
check('Integration test validates V41 preference columns', 'notificationV41PreferenceColumns' in integration and "('loyalty_enabled','waitlist_enabled')" in integration)
check('Integration test covers notification dedupe', 'notificationV41ArchiveAndPrioritySummaryStayConsistent' in integration and 'assertThat(duplicate).isFalse()' in integration)
check('Integration test covers WAITLIST HIGH priority', 'category()).isEqualTo("WAITLIST")' in integration and 'priority()).isEqualTo("HIGH")' in integration)
check('Integration test covers archive summary semantics', 'archived.archivedCount()).isEqualTo(1)' in integration and 'archived.unreadCount()).isZero()' in integration)
check('Integration test covers unarchive and read semantics', 'notifications.unarchive' in integration and 'notifications.read' in integration)

check('Main CI source regression is V41 or newer', bool(re.search(r'V26-V(?:4[1-9]|[5-9][0-9])(?:\.\d+)? source regression',ci)))
check('Main CI runs V40 and V41 verifiers', 'verify_v40_loyalty_membership.py' in ci and 'verify_v41_notification_engagement.py' in ci)
check('Standalone RC defaults to V41-or-newer candidate', bool(re.search(r'default: "v(?:4[1-9]|[5-9][0-9])\.\d+\.\d+-rc\.1"',rc)) and bool(re.search(r'cinebooking_v(?:4[1-9]|[5-9][0-9])_rc_\$\{\{ github\.run_id \}\}',rc)))
check('Standalone RC E2E label includes V41', 'V39 + V40 + V41' in rc)
check('Stable release defaults to V41-or-newer', bool(re.search(r'default: "(?:4[1-9]|[5-9][0-9])\.\d+\.\d+"',release)) and bool(re.search(r'cinebooking_v(?:4[1-9]|[5-9][0-9])_release_\$\{\{ github\.run_id \}\}',release)) and bool(re.search(r'v(?:4[1-9]|[5-9][0-9])-release-test-secret',release)))
check('V40 verifier is forward-compatible with V41 lifecycle', 'V40-or-newer candidate' in v40 and 'V40-or-newer' in v40)
check('V41 diagnostics chains V40 then V41 verifier', 'diagnose-v40.ps1' in diag and 'verify_v41_notification_engagement.py' in diag)
check('Makefile exposes V41 verify and diagnose', 'verify-v41:' in make and 'diagnose-v41:' in make)
check('README documents V41 notification feature', 'V41 - Notification Center & Engagement Automation 2.0' in readme)
check('README documents V41 migration and APIs', 'V41__notification_engagement_2.sql' in readme and '/api/notifications/{id}/archive' in readme)
check('README documents V41 release lifecycle', 'v41.0.0-rc.1' in readme and 'v41.0.0' in readme and '9 Playwright Chromium journeys' in readme)

ignored={'.git','node_modules','.next','target','playwright-report','test-results'}
markdown=[p for p in ROOT.rglob('*.md') if not any(part in ignored for part in p.parts)]
check('source still contains exactly one README.md', len(markdown)==1 and markdown[0].resolve()==(ROOT/'README.md').resolve())
check('destructive volume reset remains blocked', 'destructive volume reset is disabled' in make and '@exit 1' in make)
check('real payment gateway credentials remain blank in example env', re.search(r'^VNPAY_HASH_SECRET=\s*$',env,re.M) and re.search(r'^MOMO_SECRET_KEY=\s*$',env,re.M))
check('example env keeps only safe JWT placeholder', 'JWT_SECRET=change-this-to-a-long-random-secret-at-least-32-characters' in env)
check('V41 migration does not modify old Flyway files', 'ALTER TABLE user_notification' in mig and 'ALTER TABLE notification_preference' in mig)

passed=sum(ok for _,ok in checks); total=len(checks)
print(f"\nV41 verification: {passed}/{total} checks passed")
if passed!=total:
    print('Failed checks:')
    for name,ok in checks:
        if not ok: print(' - '+name)
    sys.exit(1)
