from pathlib import Path
import re
import sys

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name, ok):
    ok=bool(ok);checks.append((name,ok));print(('PASS' if ok else 'FAIL')+': '+name)

migration=text('backend/src/main/resources/db/migration/V37__payment_gateway_hardening.sql')
payment=text('backend/src/main/java/com/cinebooking/domain/Payment.java')
status=text('backend/src/main/java/com/cinebooking/domain/PaymentStatus.java')
repo=text('backend/src/main/java/com/cinebooking/payment/PaymentRepository.java')
attempts=text('backend/src/main/java/com/cinebooking/payment/PaymentAttemptService.java')
service=text('backend/src/main/java/com/cinebooking/payment/PaymentService.java')
controller=text('backend/src/main/java/com/cinebooking/payment/PaymentController.java')
vnpay=text('backend/src/main/java/com/cinebooking/payment/VnPayGateway.java')
momo=text('backend/src/main/java/com/cinebooking/payment/MomoGateway.java')
crypto=text('backend/src/main/java/com/cinebooking/payment/CryptoUtil.java')
webhook_entity=text('backend/src/main/java/com/cinebooking/domain/PaymentWebhookEvent.java')
webhook_repo=text('backend/src/main/java/com/cinebooking/payment/PaymentWebhookEventRepository.java')
admin_service=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentService.java')
admin_controller=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentController.java')
expiry=text('backend/src/main/java/com/cinebooking/payment/PaymentExpiryJob.java')
app=text('backend/src/main/resources/application.yml')
compose=text('docker-compose.yml')
env=text('.env.example')
types=text('frontend/lib/types.ts')
booking_page=text('frontend/app/booking/[showtimeId]/page.tsx')
result_page=text('frontend/app/payment/result/page.tsx')
history_page=text('frontend/app/payments/page.tsx')
admin_page=text('frontend/app/admin/payments/page.tsx')
header=text('frontend/components/Header.tsx')
e2e=text('frontend/e2e/booking-flow.spec.ts')
it=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
diag=text('tools/diagnose-v37.ps1')
make=text('Makefile')
readme=text('README.md')

check('V37 migration exists', bool(migration))
check('migration separates payer ownership from ticket ownership', 'payer_user_id UUID REFERENCES app_user(id)' in migration and 'COALESCE(b.purchaser_user_id, b.user_id)' in migration and 'ALTER COLUMN payer_user_id SET NOT NULL' in migration)
check('migration adds client payment idempotency key', 'client_idempotency_key' in migration and 'uq_payment_booking_client_idempotency' in migration)
check('migration separates merchant order and provider transaction metadata', all(x in migration for x in ['provider_order_id','merchant_request_id','provider_created_at']))
check('migration adds provider result and expiry timestamps', all(x in migration for x in ['provider_response_code','provider_message','expires_at','failed_at','updated_at','last_webhook_at']))
check('migration creates exactly-once webhook ledger', 'CREATE TABLE payment_webhook_event' in migration and 'uq_payment_webhook_provider_event' in migration)
check('payment entity maps payer and V37 metadata', all(x in payment for x in ['payerUserId','clientIdempotencyKey','providerOrderId','merchantRequestId','providerCreatedAt','providerResponseCode','providerMessage','expiresAt','failedAt','lastWebhookAt']))
check('payment lifecycle includes review and expiry', all(x in status for x in ['PENDING','SUCCESS','FAILED','EXPIRED','REVIEW','REFUNDED']))
check('payment repository supports payer history and row locking', 'findByPayerUserIdOrderByCreatedAtDesc' in repo and 'PESSIMISTIC_WRITE' in repo and 'findByIdForUpdate' in repo)
check('payment-start claim locks booking and records payer', 'findByIdForUpdate' in attempts and 'setPayerUserId(userId)' in attempts)
check('payment-start replays same booking idempotency key', 'findByBookingIdAndClientIdempotencyKey' in attempts and 'return new StartClaim(p,booking,true)' in attempts)
check('payment-start rejects key reuse across providers', 'Idempotency-Key đã được dùng với cổng thanh toán khác' in attempts)
check('payment controller accepts Idempotency-Key header', '@RequestHeader(value="Idempotency-Key",required=false)' in controller)
check('frontend sends payment Idempotency-Key for new and resumed payment', booking_page.count('"Idempotency-Key":paymentKey(') >= 2)
check('frontend maintains a separate payment retry key from booking creation key', 'paymentKeysRef' in booking_page and 'checkoutKeyRef' in booking_page and 'function paymentKey' in booking_page)
check('MoMo create uses persisted merchant request/order IDs', 'getMerchantRequestId()' in momo and 'getProviderOrderId()' in momo)
check('MoMo create request uses documented HMAC SHA256 canonical fields', 'HmacSHA256' in momo and 'accessKey=' in momo and '&requestType=captureWallet' in momo)
check('MoMo HTTP calls allow at least 30 seconds', 'timeout(Duration.ofSeconds(35))' in momo)
check('MoMo query endpoint and signed request are implemented', 'MOMO_QUERY_URL' in app and 'public QueryResult query(Payment payment)' in momo and 'URI.create(queryUrl)' in momo)
# explicit query shape check without syntax tricks
check('MoMo query signature contains orderId partnerCode requestId', '"accessKey="+accessKey+"&orderId="+payment.getProviderOrderId()+"&partnerCode="+partnerCode+"&requestId="+requestId' in momo)
check('MoMo IPN signature is verified before canonical mutation', 'verifyIpn' in momo and 'if(!signatureValid){' in service and 'rejectedWebhookKey("signature",payloadHash)' in service)
check('MoMo amount is checked before success', 'validMomoAmount' in service and service.index('validMomoAmount') < service.index('if(result==0)'))
check('MoMo non-final result codes remain pending', 'Set.of(7000,7002,9000)' in service)
check('VNPay checkout uses HMAC SHA512', 'HmacSHA512' in vnpay and 'vnp_SecureHash' in vnpay)
check('VNPay amount uses x100 representation', 'movePointRight(2)' in vnpay)
check('VNPay checkout expiry follows booking payment window', 'booking.getExpiresAt()' in vnpay and 'vnp_ExpireDate' in vnpay)
check('VNPay return/IPN checksum verification exists', 'public boolean verify' in vnpay and 'copy.remove("vnp_SecureHash")' in vnpay)
check('VNPay QueryDr is implemented with response signature verification', 'vnp_Command","querydr"' in vnpay and 'vnp_TransactionDate' in vnpay and 'responseHash' in vnpay and 'signatureValid' in vnpay)
check('VNPay amount is checked before success', 'validVnPayAmount' in service and service.index('validVnPayAmount') < service.index('if("00".equals(resultCode)'))
check('VNPay ambiguous reverse/refund states go to manual review', 'Set.of("04","05","06")' in service and 'PaymentStatus.REVIEW' in service)
check('browser return handlers are verify-only', 'vnPayReturn' in service and 'momoReturn' in service and 'Return verified' in service)
check('MoMo browser result no longer posts to IPN endpoint', '/payments/momo/return' in result_page and '/payments/momo/ipn' not in result_page)
check('payment result page polls authenticated backend state after redirect verification', '/checkout' in result_page and 'api<PaymentCheckout>' in result_page and 'server-to-server' in result_page)
check('webhook event claim is atomic under duplicate delivery', 'ON CONFLICT (provider, event_key) DO NOTHING' in webhook_repo)
check('invalid webhook signatures cannot poison canonical event idempotency keys', service.count('rejectedWebhookKey("signature",payloadHash)') >= 2 and service.count('rejectedWebhookKey("amount",payloadHash)') >= 2)
check('MoMo duplicate delivery replays the recorded webhook response', 'previousMomoResponse' in service and 'findByProviderAndEventKey("MOMO",eventKey)' in service)
check('webhook payload hash and signature validity are recorded', 'payload_hash' in migration and 'signature_valid' in migration and 'CryptoUtil.sha256' in service)
check('crypto utility uses constant-time signature comparison', 'MessageDigest.isEqual' in crypto or 'constantTimeEquals' in crypto)
check('late gateway success is diverted to REVIEW', 'Gateway reported success after booking became' in service and 'PaymentStatus.REVIEW' in service)
check('failed real gateway attempt leaves booking retry window open', 'VNPAY transaction status "+transactionStatus,false' in service and 'MoMo payment failed")),false' in service)
check('expired payment releases pending booking and seats', 'bookingService.cancelPending(locked.getBookingId(),BookingStatus.EXPIRED)' in service and '@Scheduled' in expiry)
check('payer history is independent of current transferred ticket owner', 'findByPayerUserIdOrderByCreatedAtDesc' in service and 'getPayerUserId()' in service)
check('payment checkout access is payer-owned', 'Không có quyền xem giao dịch thanh toán này' in service and 'userId.equals(p.getPayerUserId())' in service)
check('customer payment history API exists', '@GetMapping("/history")' in controller and 'service.history' in controller)
check('provider availability API exists', '@GetMapping("/providers")' in controller and 'ProviderAvailability' in text('backend/src/main/java/com/cinebooking/payment/PaymentDtos.java'))
check('booking UI disables unconfigured real gateways', 'providerAvailability' in booking_page and 'chưa cấu hình' in booking_page and 'disabled={!providerReady' in booking_page)
check('customer payment history page exists', 'Lịch sử thanh toán' in history_page and '/payments/history' in history_page and 'Cần đối soát' in history_page)
check('admin payment operations API exists', '/api/admin/payments' in admin_controller and '@PostMapping("/{id}/reconcile")' in admin_controller)
check('admin reconciliation supports VNPay and MoMo query APIs', 'vnPay.query(p,ip)' in admin_service and 'momo.query(p)' in admin_service)
check('admin reconciliation rejects VNPay invalid query signature', 'query trả về chữ ký không hợp lệ' in admin_service)
check('admin payment operations UI exists', 'Đối soát thanh toán' in admin_page and '/admin/payments/' in admin_page and 'Webhook / IPN' in admin_page)
check('navigation exposes customer and admin payment centers', 'href="/payments"' in header and 'href="/admin/payments"' in header)
check('application config exposes mock toggle and gateway create/query URLs', all(x in app for x in ['PAYMENT_MOCK_ENABLED','VNPAY_PAYMENT_URL','VNPAY_QUERY_URL','MOMO_CREATE_URL','MOMO_QUERY_URL']))
check('Compose passes gateway URLs and mock toggle to both backend replicas', all(x in compose for x in ['PAYMENT_MOCK_ENABLED','VNPAY_PAYMENT_URL','VNPAY_QUERY_URL','MOMO_CREATE_URL','MOMO_QUERY_URL']) and 'environment: *backend_env' in compose)
check('example env contains gateway URLs but no real credentials', all(x in env for x in ['VNPAY_PAYMENT_URL=','VNPAY_QUERY_URL=','MOMO_CREATE_URL=','MOMO_QUERY_URL=']) and re.search(r'^VNPAY_HASH_SECRET=\s*$',env,re.M) and re.search(r'^MOMO_SECRET_KEY=\s*$',env,re.M))
check('Testcontainers expects Flyway V37 and webhook schema', 'isEqualTo("37")' in it and 'paymentV37Columns' in it and 'payment_webhook_event' in it)
check('Testcontainers covers idempotent payment claim and payer ownership', 'paymentStartClaimIsIdempotentAndKeepsPayerOwnership' in it and 'second.replayed()).isTrue()' in it and 'getPayerUserId()' in it)
check('Playwright covers V37 customer payment history', 'V37 payment history shows the successful payer-owned transaction' in e2e and 'Lịch sử thanh toán' in e2e)
check('V37 payment history E2E scopes status/provider to the visible payment card', 'const paymentCard = page.locator("article").filter({ hasText: "Hành Trình Sao Hỏa" }).first();' in e2e and 'paymentCard.getByText("SUCCESS", { exact: true })' in e2e and 'paymentCard.getByText("MOCK", { exact: true })' in e2e)
check('Playwright covers V37 admin payment operations page', '/admin/payments' in e2e and 'Đối soát thanh toán' in e2e)
check('main CI runs V37 verifier', 'python3 tools/verify_v37_payment_gateway.py' in ci and 'V26-V37 source regression' in ci)
check('standalone RC defaults to V37 candidate and includes V37 journey', 'default: "v37.0.0-rc.1"' in rc and 'V36 + V37' in rc)
check('stable-release workflow defaults to V37', 'default: "37.0.0"' in release and 'cinebooking_v37_release_${{ github.run_id }}' in release)
check('V37 diagnostics chains V36 and verifier', 'diagnose-v36.ps1' in diag and 'verify_v37_payment_gateway.py' in diag)
check('Makefile exposes V37 verify and diagnose', 'verify-v37:' in make and 'diagnose-v37:' in make)
check('README documents V37 payment hardening and release lifecycle', 'V37 - Payment Gateway Production Ready' in readme and 'v37.0.0-rc.1' in readme and 'GitHub Release' in readme)
ignored={'.git','node_modules','.next','target','playwright-report','test-results'}
markdown=[p for p in ROOT.rglob('*.md') if not any(part in ignored for part in p.parts)]
check('source still contains exactly one README.md', len(markdown)==1 and markdown[0].resolve()==(ROOT/'README.md').resolve())
check('reset safety remains blocked', 'destructive volume reset is disabled' in make and '@exit 1' in make)

failed=[n for n,ok in checks if not ok]
print(f'\n{len(checks)-len(failed)}/{len(checks)} checks passed')
if failed:
    print('Failed checks:')
    for n in failed: print(' -',n)
    sys.exit(1)
