from pathlib import Path
import re,sys
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,ok):
    ok=bool(ok);checks.append((name,ok));print(('PASS' if ok else 'FAIL')+': '+name)

mig=text('backend/src/main/resources/db/migration/V42__financial_ledger_reconciliation.sql')
entry=text('backend/src/main/java/com/cinebooking/domain/FinancialLedgerEntry.java')
line=text('backend/src/main/java/com/cinebooking/domain/FinancialLedgerLine.java')
run_entity=text('backend/src/main/java/com/cinebooking/domain/FinancialReconciliationRun.java')
issue_entity=text('backend/src/main/java/com/cinebooking/domain/FinancialReconciliationIssue.java')
entry_repo=text('backend/src/main/java/com/cinebooking/finance/FinancialLedgerEntryRepository.java')
line_repo=text('backend/src/main/java/com/cinebooking/finance/FinancialLedgerLineRepository.java')
run_repo=text('backend/src/main/java/com/cinebooking/finance/FinancialReconciliationRunRepository.java')
issue_repo=text('backend/src/main/java/com/cinebooking/finance/FinancialReconciliationIssueRepository.java')
dtos=text('backend/src/main/java/com/cinebooking/finance/FinanceDtos.java')
svc=text('backend/src/main/java/com/cinebooking/finance/FinancialLedgerService.java')
ctl=text('backend/src/main/java/com/cinebooking/finance/AdminFinanceController.java')
job=text('backend/src/main/java/com/cinebooking/finance/FinancialReconciliationJob.java')
payment=text('backend/src/main/java/com/cinebooking/payment/PaymentService.java')
refund=text('backend/src/main/java/com/cinebooking/operations/RefundService.java')
payment_repo=text('backend/src/main/java/com/cinebooking/payment/PaymentRepository.java')
lot_repo=text('backend/src/main/java/com/cinebooking/commerce/LoyaltyPointLotRepository.java')
app=text('backend/src/main/resources/application.yml')
compose=text('docker-compose.yml')
env=text('.env.example')
types=text('frontend/lib/types.ts')
ui=text('frontend/app/admin/finance/page.tsx')
admin=text('frontend/app/admin/page.tsx')
e2e=text('frontend/e2e/financial-ledger.spec.ts')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
diag=text('tools/diagnose-v42.ps1')
make=text('Makefile')
readme=text('README.md')
v41=text('tools/verify_v41_notification_engagement.py')
v40=text('tools/verify_v40_loyalty_membership.py')

check('V42 Flyway migration exists',bool(mig))
check('V42 creates immutable ledger entry table','CREATE TABLE financial_ledger_entry' in mig and 'event_key VARCHAR(180) NOT NULL UNIQUE' in mig)
check('V42 creates double-entry ledger line table','CREATE TABLE financial_ledger_line' in mig and "direction IN ('DEBIT','CREDIT')" in mig)
check('V42 ledger uses positive VND monetary lines','amount NUMERIC(14,2) NOT NULL' in mig and 'amount > 0' in mig and "currency = 'VND'" in mig)
check('V42 ledger event types are constrained',"PAYMENT_CAPTURED" in mig and "REFUND_SETTLED" in mig and 'ck_financial_ledger_event_type' in mig)
check('V42 ledger entry indexes cover occurred payment booking',all(x in mig for x in ['idx_financial_ledger_entry_occurred','idx_financial_ledger_entry_payment','idx_financial_ledger_entry_booking']))
check('V42 ledger line indexes cover entry and account','idx_financial_ledger_line_entry' in mig and 'idx_financial_ledger_line_account' in mig)
check('V42 blocks UPDATE and DELETE on ledger entry and line','v42_block_financial_ledger_mutation' in mig and 'BEFORE UPDATE OR DELETE ON financial_ledger_entry' in mig and 'BEFORE UPDATE OR DELETE ON financial_ledger_line' in mig)
check('V42 database enforces deferred balance check','v42_assert_financial_entry_balanced' in mig and 'DEFERRABLE INITIALLY DEFERRED' in mig and 'debit_total <> credit_total' in mig)
check('V42 backfills historical successful captures',"p.status IN ('SUCCESS','REFUNDED','REVIEW')" in mig and "'PAYMENT_CAPTURE:' || p.id" in mig and "'V42_BACKFILL'" in mig)
check('V42 backfills historical refunds',"p.status='REFUNDED'" in mig and "'REFUND:' || p.id" in mig and 'p.refunded_amount' in mig)
check('V42 migration validates backfill balance before enabling runtime ledger','V42 backfill produced an unbalanced financial ledger entry' in mig and 'GROUP BY entry_id' in mig)
check('V42 backfill creates payment clearing debit and captured-funds credit','PAYMENT_CLEARING:' in mig and "'DEBIT', p.amount" in mig and "'CUSTOMER_FUNDS_CAPTURED', 'CREDIT'" in mig)
check('V42 backfill creates refunded-funds debit and clearing credit',"'CUSTOMER_FUNDS_REFUNDED', 'DEBIT'" in mig and "'CREDIT', p.refunded_amount" in mig)
check('V42 creates reconciliation run table','CREATE TABLE financial_reconciliation_run' in mig and 'run_key VARCHAR(120) NOT NULL UNIQUE' in mig)
check('V42 reconciliation status is constrained',"status IN ('RUNNING','CLEAN','ISSUES','FAILED')" in mig)
check('V42 reconciliation stores payment refund loyalty metrics',all(x in mig for x in ['payment_amount','ledger_capture_amount','refund_amount','ledger_refund_amount','loyalty_users_checked','loyalty_mismatch_count','issue_count']))
check('V42 creates reconciliation issue table','CREATE TABLE financial_reconciliation_issue' in mig and 'issue_type VARCHAR(50)' in mig)
check('V42 issue severity and status are constrained',"severity IN ('INFO','WARNING','CRITICAL')" in mig and "status IN ('OPEN','RESOLVED')" in mig)
check('V42 indexes reconciliation runs and open issues','idx_financial_reconciliation_run_date' in mig and 'idx_financial_reconciliation_issue_open' in mig)

check('FinancialLedgerEntry entity maps immutable event metadata',all(x in entry for x in ['@Table(name="financial_ledger_entry")','eventKey','eventType','bookingId','paymentId','occurredAt']))
check('FinancialLedgerLine entity maps account direction amount currency',all(x in line for x in ['@Table(name="financial_ledger_line")','accountCode','direction','BigDecimal amount','currency']))
check('Reconciliation run entity maps run key and daily totals',all(x in run_entity for x in ['runKey','businessDate','ledgerCaptureAmount','ledgerRefundAmount','loyaltyMismatchCount']))
check('Reconciliation issue entity maps resolution lifecycle',all(x in issue_entity for x in ['issueType','severity','expectedValue','actualValue','resolvedAt','resolvedBy']))

check('Ledger repository exposes event-key lookup','findByEventKey' in entry_repo)
check('Ledger repository has unbounded daily reconciliation query','findByOccurredAtGreaterThanEqualAndOccurredAtLessThanOrderByOccurredAtAsc' in entry_repo)
check('Ledger repository limits dashboard display separately','findTop200ByOccurredAtGreaterThanEqualAndOccurredAtLessThanOrderByOccurredAtDesc' in entry_repo)
check('Ledger repository claims event with ON CONFLICT','insertOnce' in entry_repo and 'on conflict (event_key) do nothing' in entry_repo)
check('Ledger line repository loads lines in batches','findByEntryIdIn' in line_repo)
check('Finance service chunks large ledger line fetches','i+=1000' in svc and 'ids.subList' in svc and 'findByEntryIdIn(batch)' in svc)
check('Reconciliation run repository claims scheduled run with ON CONFLICT','insertOnce' in run_repo and 'on conflict (run_key) do nothing' in run_repo)
check('Reconciliation run repository exposes latest date and recent runs','findFirstByBusinessDateOrderByStartedAtDesc' in run_repo and 'findTop30ByOrderByStartedAtDesc' in run_repo)
check('Issue repository exposes run and open issue views','findByRunIdOrderByCreatedAtAsc' in issue_repo and 'findTop200ByStatusOrderByCreatedAtDesc' in issue_repo)

check('Finance DTO exposes ledger lines and entries','LedgerLineView' in dtos and 'LedgerEntryView' in dtos)
check('Finance DTO exposes reconciliation issue and run','ReconciliationIssueView' in dtos and 'ReconciliationRunView' in dtos)
check('Finance dashboard exposes daily net and operational evidence',all(x in dtos for x in ['capturedAmount','refundedAmount','netAmount','ledgerEntries','openIssues']))

check('Finance service records payment capture with deterministic event key','"PAYMENT_CAPTURE:"+payment.getId()' in svc and 'PAYMENT_CAPTURED' in svc)
check('Payment capture posts clearing debit and captured-funds credit','"PAYMENT_CLEARING:"+providerAccount' in svc and '"CUSTOMER_FUNDS_CAPTURED"' in svc)
check('Finance service records refund with deterministic event key','"REFUND:"+payment.getId()' in svc and 'REFUND_SETTLED' in svc)
check('Refund posts refunded-funds debit and clearing credit','"CUSTOMER_FUNDS_REFUNDED"' in svc and '"PAYMENT_CLEARING:"+providerAccount' in svc)
check('Zero-value payments can record event without invalid zero lines','if(amount.signum()==0)return' in svc)
check('Finance service validates Java-side debit credit equality','debit.compareTo(credit)!=0' in svc and 'Unbalanced financial ledger event' in svc)
check('Finance provider account code is normalized','replaceAll("[^A-Z0-9_]","_")' in svc and 'substring(0,50)' in svc)
check('Manual reconciliation uses unique run key','"MANUAL:"+UUID.randomUUID()' in svc)
check('Scheduled reconciliation uses deterministic daily run key','"AUTO:"+day' in svc)
check('Scheduled duplicate reconciliation returns existing run','if(claimed==0)return runs.findByRunKey(runKey)' in svc)
check('Business day uses Asia Ho Chi Minh timezone','ZoneId.of("Asia/Ho_Chi_Minh")' in svc)
check('Reconciliation includes SUCCESS REFUNDED and paid REVIEW captures','List.of(PaymentStatus.SUCCESS,PaymentStatus.REFUNDED,PaymentStatus.REVIEW)' in svc)
check('Reconciliation checks missing payment ledger events','PAYMENT_LEDGER_MISSING' in svc)
check('Reconciliation checks payment amount mismatch','PAYMENT_LEDGER_AMOUNT_MISMATCH' in svc)
check('Reconciliation checks missing refund ledger events','REFUND_LEDGER_MISSING' in svc)
check('Reconciliation checks refund amount mismatch','REFUND_LEDGER_AMOUNT_MISMATCH' in svc)
check('Reconciliation checks daily capture totals','CAPTURE_TOTAL_MISMATCH' in svc)
check('Reconciliation checks daily refund totals','REFUND_TOTAL_MISMATCH' in svc)
check('Loyalty reconciliation compares user balance with point lots','sumRemainingPoints' in svc and 'LOYALTY_BALANCE_MISMATCH' in svc)
check('Reconciliation status is CLEAN only with no issues','found.isEmpty()?"CLEAN":"ISSUES"' in svc)
check('Finance issue resolution records actor and audit','FINANCE_ISSUE_RESOLVE' in svc and 'setResolvedBy(actor)' in svc)
check('Manual finance reconciliation writes audit evidence','FINANCE_RECONCILE' in svc)

check('Payment repository supports business-day captured payment query','findByPaidAtGreaterThanEqualAndPaidAtLessThanAndStatusIn' in payment_repo)
check('Payment repository supports business-day refund query','findByRefundedAtGreaterThanEqualAndRefundedAtLessThanAndStatus' in payment_repo)
check('Loyalty lot repository exposes authoritative remaining-points sum','sumRemainingPoints' in lot_repo and 'sum(remaining_points)' in lot_repo)

check('Payment service injects financial ledger','FinancialLedgerService finance' in payment)
check('Payment SUCCESS writes capture ledger','finance.recordPaymentCapture(p,b)' in payment)
check('Payment SUCCESS replay self-heals idempotent ledger','PaymentStatus.SUCCESS' in payment and 'finance.recordPaymentCapture(p,bookingService.entity' in payment)
check('Late gateway success REVIEW also writes capture ledger',payment.count('finance.recordPaymentCapture(p,current)')>=2)
check('Refund service injects financial ledger','FinancialLedgerService finance' in refund)
check('Refund finalization writes refund ledger after payment save','payments.save(p);\n        finance.recordRefund(p,b);' in refund)

check('Admin finance API exposes dashboard','@RequestMapping("/api/admin/finance")' in ctl and '@GetMapping' in ctl)
check('Admin finance API exposes manual reconcile','/reconcile' in ctl and 'service.reconcile' in ctl)
check('Admin finance API exposes issue resolve','/issues/{id}/resolve' in ctl and 'service.resolveIssue' in ctl)
check('Finance daily job exists',bool(job) and '@Scheduled' in job)
check('Finance daily job runs at Asia Ho Chi Minh timezone','zone="Asia/Ho_Chi_Minh"' in job)
check('Finance daily job reconciles previous business day','minusDays(1)' in job and 'reconcileScheduled' in job)
check('Finance daily job supports safe disable flag','auto-reconcile-enabled' in job and 'if(!enabled)return' in job)

check('Application config exposes finance auto reconcile','FINANCE_AUTO_RECONCILE_ENABLED' in app and 'auto-reconcile-enabled' in app)
check('Application config exposes finance daily close cron','FINANCE_DAILY_CLOSE_CRON' in app and 'daily-close-cron' in app)
check('Example env documents safe V42 finance defaults','FINANCE_AUTO_RECONCILE_ENABLED=true' in env and 'FINANCE_DAILY_CLOSE_CRON=0 10 1 * * *' in env)
check('Docker forwards V42 finance settings','FINANCE_AUTO_RECONCILE_ENABLED' in compose and 'FINANCE_DAILY_CLOSE_CRON' in compose)

check('Frontend types expose financial dashboard','FinancialDashboard' in types and 'FinancialReconciliationRun' in types)
check('Frontend types expose ledger and issue contracts','FinancialLedgerEntry' in types and 'FinancialReconciliationIssue' in types)
check('Finance UI identifies V42','CINEBOOKING · V42' in ui)
check('Finance UI exposes business date and reconcile controls','finance-business-date' in ui and 'finance-reconcile' in ui)
check('Finance UI exposes captured refunded net KPIs',all(x in ui for x in ['finance-captured','finance-refunded','finance-net']))
check('Finance UI exposes latest run status','finance-run-status' in ui)
check('Finance UI renders immutable ledger evidence','finance-ledger-section' in ui and 'finance-ledger-entry' in ui and 'PAYMENT_CAPTURED' not in ui)
check('Finance UI renders reconciliation issues and clean state','finance-issues-section' in ui and 'finance-clean-state' in ui and 'finance-issue' in ui)
check('Admin dashboard links to finance operations','href="/admin/finance"' in admin and 'Financial Ledger' in admin)

check('V42 Playwright journey exists',bool(e2e))
check('V42 E2E creates its own customer and booking','v42-finance-' in e2e and 'Hành Trình Sao Hỏa' in e2e)
check('V42 E2E completes MOCK payment','Giả lập thành công' in e2e and '/api/payments/history' in e2e)
check('V42 E2E captures concrete payment id','paymentId' in e2e and 'PAYMENT_CAPTURE:${payment!.paymentId}' in e2e)
check('V42 E2E verifies double-entry account names','DEBIT PAYMENT_CLEARING:MOCK' in e2e and 'CREDIT CUSTOMER_FUNDS_CAPTURED' in e2e)
check('V42 E2E runs daily reconciliation through UI','finance-reconcile' in e2e)
check('V42 E2E requires CLEAN reconciliation','finance-run-status' in e2e and 'toHaveText("CLEAN"' in e2e)
check('V42 E2E verifies no open issue for run','finance-clean-state' in e2e)

check('Integration test expects Flyway latest V42','isEqualTo("42")' in integration and 'flywayMigratesRealPostgresToV42FinancialLedgerSchemaAndDemoCatalog' in integration)
check('Integration test validates four V42 tables','financialV42Tables' in integration and 'financial_ledger_entry' in integration and 'financial_reconciliation_issue' in integration)
check('Integration test validates immutable and balance triggers','financialV42Triggers' in integration and 'trg_v42_financial_ledger_balanced' in integration)
check('Integration test disables scheduled finance job','app.finance.auto-reconcile-enabled=false' in integration)
check('Integration test covers ledger idempotency','financialV42LedgerIsIdempotentBalancedAndReconcilesCleanly' in integration and 'finance.recordPaymentCapture(payment,booking);\n        finance.recordPaymentCapture(payment,booking);' in integration)
check('Integration test proves one entry and two lines','assertThat(entryCount).isEqualTo(1)' in integration and 'assertThat(lineCount).isEqualTo(2)' in integration)
check('Integration test proves debit equals credit','assertThat(credit).isEqualByComparingTo(debit)' in integration)
check('Integration test requires clean reconciliation','assertThat(run.status()).isEqualTo("CLEAN")' in integration and 'assertThat(run.issueCount()).isZero()' in integration)
check('Integration test covers scheduled run idempotency','reconcileScheduled(previous)' in integration and 'assertThat(autoReplay.id()).isEqualTo(autoFirst.id())' in integration and '"AUTO:"+previous' in integration)

check('Main CI source regression upgraded to V42','V26-V42 source regression' in ci)
check('Main CI runs V41 and V42 verifiers','verify_v41_notification_engagement.py' in ci and 'verify_v42_financial_ledger.py' in ci)
check('Standalone RC defaults to V42','default: "v42.0.0-rc.1"' in rc and 'cinebooking_v42_rc_${{ github.run_id }}' in rc)
check('Standalone RC browser label includes V42','V40 + V41 + V42' in rc)
check('Stable release defaults to V42','default: "42.0.0"' in release and 'cinebooking_v42_release_${{ github.run_id }}' in release and 'v42-release-test-secret' in release)
check('V41 verifier is forward-compatible with V42','V41-or-newer candidate' in v41 and 'V41-or-newer' in v41)
check('V40 verifier is forward-compatible beyond V41','V40-or-newer candidate' in v40 and 'range(40,100)' in v40)
check('V42 diagnostics chains V41 and V42 verifier','diagnose-v41.ps1' in diag and 'verify_v42_financial_ledger.py' in diag)
check('Makefile exposes V42 verify and diagnose','verify-v42:' in make and 'diagnose-v42:' in make)
check('README documents V42 finance feature','V42 - Financial Ledger & Reconciliation' in readme)
check('README documents V42 migration and API','V42__financial_ledger_reconciliation.sql' in readme and '/api/admin/finance/reconcile' in readme)
check('README documents V42 release lifecycle','v42.0.0-rc.1' in readme and 'v42.0.0' in readme and '10 Playwright Chromium journeys' in readme)

ignored={'.git','node_modules','.next','target','playwright-report','test-results'}
markdown=[p for p in ROOT.rglob('*.md') if not any(part in ignored for part in p.parts)]
check('source still contains exactly one README.md',len(markdown)==1 and markdown[0].resolve()==(ROOT/'README.md').resolve())
check('destructive volume reset remains blocked','destructive volume reset is disabled' in make and '@exit 1' in make)
check('real gateway credentials remain blank in example env',re.search(r'^VNPAY_HASH_SECRET=\s*$',env,re.M) and re.search(r'^MOMO_SECRET_KEY=\s*$',env,re.M))
check('example env keeps safe JWT placeholder','JWT_SECRET=change-this-to-a-long-random-secret-at-least-32-characters' in env)
check('V42 adds new migration instead of editing history','V42__financial_ledger_reconciliation.sql' in readme and 'CREATE TABLE financial_ledger_entry' in mig)

passed=sum(ok for _,ok in checks);total=len(checks)
print(f"\nV42 verification: {passed}/{total} checks passed")
if passed!=total:
    print('Failed checks:')
    for name,ok in checks:
        if not ok:print(' - '+name)
    sys.exit(1)
