from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]

def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''

def check(name,cond):
    ok=bool(cond); checks.append((name,ok)); print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

service=text('backend/src/main/java/com/cinebooking/risk/FraudRiskService.java')
dtos=text('backend/src/main/java/com/cinebooking/risk/FraudRiskDtos.java')
controller=text('backend/src/main/java/com/cinebooking/risk/AdminFraudRiskController.java')
security=text('backend/src/main/java/com/cinebooking/config/SecurityConfig.java')
audit=text('backend/src/main/java/com/cinebooking/audit/AuditService.java')
page=text('frontend/app/admin/risk/page.tsx')
types=text('frontend/lib/types.ts')
admin=text('frontend/app/admin/page.tsx')
header=text('frontend/components/Header.tsx')
e2e=text('frontend/e2e/fraud-risk-intelligence-v61.spec.ts')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v61.ps1')
readme=text('README.md')

check('V61 DTO file exists', bool(dtos))
check('V61 service file exists', bool(service))
check('V61 controller file exists', bool(controller))
check('Risk DTO exposes rules', 'record RiskRule' in dtos and 'maxPoints' in dtos)
check('Risk DTO exposes evidence signals', 'record RiskSignal' in dtos and 'evidence' in dtos and 'window' in dtos)
check('Risk DTO exposes customer score', 'record RiskCustomer' in dtos and 'riskScore' in dtos and 'riskLevel' in dtos)
check('Risk DTO exposes all primary evidence counts', all(x in dtos for x in ['bookings30m','failedPayments24h','paymentAttempts24h','voucherRedemptions24h','refunds30d','securityAlerts7d','failedLogins1h','distinctLoginIps24h']))
check('Risk DTO exposes manual disposition', 'disposition' in dtos and 'DispositionRequest' in dtos and 'DispositionResult' in dtos)
check('Risk summary exposes queue levels', all(x in dtos for x in ['watchCustomers','highRiskCustomers','criticalCustomers']))
check('Risk summary exposes scoring version', 'scoringVersion' in dtos)

check('Risk service is Spring service', '@Service' in service and 'class FraudRiskService' in service)
check('Risk service uses existing database via JdbcTemplate', 'JdbcTemplate' in service)
check('Risk service reads only USER accounts', "WHERE u.role='USER'" in service)
check('Risk score is capped at 100', 'Math.min(100' in service)
check('Risk scoring version is explicit', 'V61_RULESET_1' in service)
check('Risk levels are deterministic', all(x in service for x in ['"CRITICAL"','"HIGH"','"MEDIUM"','"LOW"']))
check('Booking velocity uses 30 minute window', "INTERVAL '30 minutes'" in service and 'BOOKING_VELOCITY' in service)
check('Booking velocity has three explainable thresholds', all(x in service for x in ['r.bookings30m >= 6','r.bookings30m >= 4','r.bookings30m >= 3']))
check('Payment failures use 24 hour window', "INTERVAL '24 hours'" in service and 'PAYMENT_FAILURES' in service)
check('Payment failures use FAILED status', "status='FAILED'" in service)
check('Payment failure scoring has three thresholds', all(x in service for x in ['r.failedPayments24h >= 5','r.failedPayments24h >= 3','r.failedPayments24h >= 2']))
check('Payment attempt volume is separate signal', 'PAYMENT_ATTEMPTS' in service and 'paymentAttempts24h' in service)
check('Voucher redemption velocity is measured', 'voucher_redemption' in service and 'VOUCHER_VELOCITY' in service)
check('Refund concentration uses refunded_at not fabricated status', 'refunded_at' in service and 'REFUND_PATTERN' in service)
check('Refund concentration uses 30 day window', "INTERVAL '30 days'" in service)
check('Security alerts are consumed as evidence', 'security_alert' in service and 'SECURITY_RISK' in service)
check('Security maximum risk is bounded by historical alert risk', 'MAX(risk_score)' in service and 'maxSecurityRisk7d' in service)
check('Security alert volume is separate explainable signal', 'SECURITY_ALERT_VOLUME' in service)
check('Login failure burst reads audit history', "action='LOGIN_FAILED'" in service and 'LOGIN_FAILURES' in service)
check('Login IP diversity reads successful and failed auth', "action IN ('LOGIN_FAILED','LOGIN_SUCCESS')" in service and 'IP_DIVERSITY' in service)
check('Distinct IP count ignores blank addresses', "ip_address IS NOT NULL AND ip_address<>''" in service)
check('Risk scoring preserves exact signal points', 'signals.stream().mapToInt(RiskSignal::points).sum()' in service)
check('Risk queue sorts highest score first', 'comparingInt(RiskCustomer::riskScore).reversed()' in service)
check('Risk queue uses privacy-friendly customer reference', 'CUS-' in service and 'substring(0, 8)' in service)
check('Risk queue does not infer identity from IP', 'distinctLoginIps24h' in service and 'deviceFingerprint' not in service)

check('Disposition set is explicit allowed set', all(x in service for x in ['CLEARED','REVIEW','CHALLENGE','BLOCK_RECOMMENDED']))
check('UNREVIEWED cannot be submitted as manual action', '"UNREVIEWED".equals(normalized)' in service)
check('Disposition is limited to customer role', 'user.getRole() != Role.USER' in service)
check('Disposition records existing audit log', 'audit.record(actorEmail, "RISK_DISPOSITION_SET", "RISK_CUSTOMER"' in service)
check('Disposition note is sanitized', 'sanitizeNote' in service and 'replaceAll' in service)
check('Disposition note is length bounded', 'clean.length() <= 400' in service)
check('Latest disposition is reconstructed from audit history', "al.action='RISK_DISPOSITION_SET'" in service and "al.entity_type='RISK_CUSTOMER'" in service)
check('V61 service never disables user account', 'setAccountEnabled' not in service)
check('V61 service never mutates booking status', 'setStatus' not in service)
check('V61 service never mutates payment status', 'PaymentStatus' not in service)
check('V61 service has no automatic block method', not re.search(r'auto.*block|block.*auto',service,re.I))

check('Risk controller is under admin risk namespace', '@RequestMapping("/api/admin/risk")' in controller)
check('Risk controller exposes scorecard GET', '@GetMapping("/scorecard")' in controller)
check('Risk controller exposes manual disposition POST', '@PostMapping("/users/{userId}/disposition")' in controller)
check('Disposition captures authenticated actor', 'authentication.getName()' in controller)
check('Disposition captures forwarded client IP', 'X-Forwarded-For' in controller)
check('Security config makes risk ADMIN-only', '.requestMatchers("/api/admin/risk/**").hasRole("ADMIN")' in security)
check('Risk endpoint is before generic admin rule', security.find('/api/admin/risk/**') < security.find('/api/admin/**'))
check('Existing audit service remains durable DB-backed', 'logs.save(l)' in audit)

check('Frontend V61 page exists', bool(page))
check('Frontend page is V61 branded', 'Fraud & Risk Intelligence · V61' in page)
check('Frontend page has stable root test id', 'data-testid="fraud-risk-v61"' in page)
check('Frontend summary test id exists', 'fraud-risk-summary-v61' in page)
check('Frontend rule engine test id exists', 'fraud-risk-engine-v61' in page)
check('Frontend customer queue test id exists', 'fraud-risk-customers-v61' in page)
check('Frontend explains no ML claim', 'no machine-learning claim' in page)
check('Frontend explains no automatic blocking', 'no automatic blocking' in page)
check('Frontend says risk score is decision support', 'risk score is decision support' in page)
check('Frontend clarifies BLOCK_RECOMMENDED is not enforcement', 'BLOCK_RECOMMENDED is a review disposition only' in page)
check('Frontend restricts UI to ADMIN', 'profile.role!=="ADMIN"' in page)
check('Frontend reads risk scorecard API', 'api<FraudRiskScorecardV61>("/admin/risk/scorecard")' in page)
check('Frontend posts manual disposition API', '/admin/risk/users/${userId}/disposition' in page)
check('Frontend provides all four manual dispositions', all(x in page for x in ['CLEARED','REVIEW','CHALLENGE','BLOCK_RECOMMENDED']))
check('Frontend renders exact evidence per signal', 's.evidence' in page and 's.points' in page)
check('Frontend renders customer risk level and score', 'c.riskScore' in page and 'c.riskLevel' in page)
check('Frontend does not claim AI fraud detection', 'AI detected fraud' not in page)

check('Frontend V61 types exist', all(x in types for x in ['FraudRiskRuleV61','FraudRiskSignalV61','FraudRiskCustomerV61','FraudRiskSummaryV61','FraudRiskScorecardV61']))
check('Frontend types enumerate four risk levels', all(x in types for x in ['"LOW"','"MEDIUM"','"HIGH"','"CRITICAL"']))
check('Frontend types enumerate manual dispositions', all(x in types for x in ['"CLEARED"','"REVIEW"','"CHALLENGE"','"BLOCK_RECOMMENDED"']))
check('Admin dashboard links V61', '/admin/risk' in admin and 'Fraud & Risk V61' in admin)
check('Header drawer links V61', '/admin/risk' in header and 'Fraud & Risk V61' in header)

check('V61 browser E2E exists', bool(e2e))
check('V61 E2E logs in as admin', 'admin-v29@cine.local' in e2e and '/login' in e2e)
check('V61 E2E visits risk page', 'page.goto("/admin/risk")' in e2e)
check('V61 E2E checks summary', 'fraud-risk-summary-v61' in e2e)
check('V61 E2E checks transparent rules', 'Transparent scoring rules' in e2e and 'V61_RULESET_1' in e2e)
check('V61 E2E checks no automatic blocking language', 'no automatic blocking' in e2e)
check('V61 E2E checks customer queue', 'fraud-risk-customers-v61' in e2e)
check('V61 E2E rejects AI fraud claim', 'not.toContain("AI detected fraud")' in e2e)

check('CI source regression covers V61 or later', bool(re.search(r'V26-V(6[1-9]|[7-9][0-9]) source regression', ci)))
check('CI runs V61 verifier', 'python3 tools/verify_v61_fraud_risk_intelligence.py' in ci)
check('RC defaults to V61 or later RC1', bool(re.search(r'default: "v(6[1-9]|[7-9][0-9])\.0\.0-rc\.1"', rc)))
check('RC compose project is V61 or later', bool(re.search(r'cinebooking_v(6[1-9]|[7-9][0-9])_rc_\$\{\{ github\.run_id \}\}', rc)))
check('RC runs V61 verifier', 'python3 tools/verify_v61_fraud_risk_intelligence.py' in rc)
check('RC browser label includes V61', '+ V60 + V61' in rc)
check('Stable defaults to 61.0.0 or later', bool(re.search(r'default: "(6[1-9]|[7-9][0-9])\.0\.0"', release)))
check('Stable compose project is V61 or later', bool(re.search(r'cinebooking_v(6[1-9]|[7-9][0-9])_release_\$\{\{ github\.run_id \}\}', release)))
check('Stable runs V61 verifier', 'python3 tools/verify_v61_fraud_risk_intelligence.py' in release)
check('Makefile exposes verify-v61', 'verify-v61:' in make and 'verify_v61_fraud_risk_intelligence.py' in make)
check('Makefile exposes diagnose-v61', 'diagnose-v61:' in make)
check('V61 diagnose script exists', bool(diagnose) and 'verify_v61_fraud_risk_intelligence.py' in diagnose)

check('README current release is V61 or later', bool(re.search(r'# CineBooking Pro V(6[1-9]|[7-9][0-9])', readme)) and bool(re.search(r'Current release:\*\* V(6[1-9]|[7-9][0-9])', readme)))
check('README documents V61 risk section', '## V61 - Fraud & Risk Intelligence' in readme)
check('README documents no black-box model', 'black-box fraud model' in readme)
check('README documents all evidence domains', all(x in readme for x in ['booking velocity','payment failures/attempts','voucher redemption velocity','refund concentration','security-alert risk','login failure bursts','distinct login IPs']))
check('README documents manual dispositions', all(x in readme for x in ['CLEARED','REVIEW','CHALLENGE','BLOCK_RECOMMENDED']))
check('README documents audit action', 'RISK_DISPOSITION_SET' in readme and 'RISK_CUSTOMER' in readme)
check('README says no auto account disable', 'does not disable the account automatically' in readme)
check('README documents V61 APIs', '/api/admin/risk/scorecard' in readme and '/api/admin/risk/users/{userId}/disposition' in readme)
check('README preserves 57 public table contract', '57 public tables' in readme and 'Flyway latest: V52' in readme)
check('README documents V61 release tags', 'v61.0.0-rc.1' in readme and 'v61.0.0' in readme)

migrations=list((ROOT/'backend/src/main/resources/db/migration').glob('V61__*.sql'))
check('V61 adds no Flyway migration', len(migrations)==0)
check('V61 adds no new JPA entity', not (ROOT/'backend/src/main/java/com/cinebooking/domain/FraudRiskCase.java').exists())
check('V61 derives state from existing audit log', 'audit_log' in service and 'RISK_DISPOSITION_SET' in service)

passed=sum(1 for _,ok in checks if ok)
print(f"V61 verification: {passed}/{len(checks)} checks passed")
if passed!=len(checks):
    raise SystemExit(1)
