from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]

def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''

def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

service=text('backend/src/main/java/com/cinebooking/payment/PaymentProductionReadinessService.java')
payment=text('backend/src/main/java/com/cinebooking/payment/PaymentService.java')
vnpay=text('backend/src/main/java/com/cinebooking/payment/VnPayGateway.java')
momo=text('backend/src/main/java/com/cinebooking/payment/MomoGateway.java')
admin_service=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentService.java')
admin_controller=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentController.java')
dtos=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentDtos.java')
webhook_repo=text('backend/src/main/java/com/cinebooking/payment/PaymentWebhookEventRepository.java')
app_yml=text('backend/src/main/resources/application.yml')
compose=text('docker-compose.yml')
env_example=text('.env.example')
page=text('frontend/app/admin/payments/page.tsx')
types=text('frontend/lib/types.ts')
admin=text('frontend/app/admin/page.tsx')
header=text('frontend/components/Header.tsx')
e2e=text('frontend/e2e/payment-production-v60.spec.ts')
booking_e2e=text('frontend/e2e/booking-flow.spec.ts')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v60.ps1')
readme=text('README.md')
v59verify=text('tools/verify_v59_realtime_operations_4.py')

check('V60 production readiness service exists', bool(service))
check('Readiness service is a Spring service', '@Service' in service and 'class PaymentProductionReadinessService' in service)
check('Production guard defaults enabled', '@Value("${app.payment.production-guard-enabled:true}")' in service)
check('Readiness evaluates MOCK VNPay and MoMo', all(x in service for x in ['mockReadiness()','remote("VNPAY"','remote("MOMO"']))
check('Readiness does not expose credential values', all(x not in service for x in ['hashSecret','secretKey','accessKey','tmnCode','partnerCode']))
check('Production readiness requires configured credentials', 'if (!configured) blockers.add("Chưa cấu hình merchant credentials")' in service)
check('Production mode requires HTTPS checkout endpoint', 'requirePublicHttps("Checkout endpoint"' in service)
check('Production mode requires HTTPS query endpoint', 'requirePublicHttps("Query endpoint"' in service)
check('Production mode requires HTTPS return URL', 'requirePublicHttps("Return URL"' in service)
check('Production mode requires HTTPS IPN URL', 'requirePublicHttps("IPN URL"' in service)
check('Production readiness blocks localhost callbacks', 'isLocalHost(uri.getHost())' in service and 'localhost' in service)
check('Sandbox callbacks are warnings not production-ready claims', 'Gateway đang ở sandbox; chưa phải production traffic' in service)
check('Production-ready flag requires configured production and no blockers', 'configured && production && blockers.isEmpty()' in service)
check('Production guard fail-closes unsafe production checkout', 'production guard chặn checkout' in service and 'HttpStatus.SERVICE_UNAVAILABLE' in service)
check('MOCK is explicitly non-production', 'MOCK chỉ dành cho local/CI' in service and 'Không phải gateway production' in service)

check('Application config exposes production guard', 'production-guard-enabled: ${PAYMENT_PRODUCTION_GUARD_ENABLED:true}' in app_yml)
check('Compose passes production guard without hardcoded secret', 'PAYMENT_PRODUCTION_GUARD_ENABLED: ${PAYMENT_PRODUCTION_GUARD_ENABLED:-true}' in compose)
check('Env example documents production guard', 'PAYMENT_PRODUCTION_GUARD_ENABLED=true' in env_example)
check('VNPay defaults remain sandbox', 'sandbox.vnpayment.vn' in app_yml)
check('MoMo defaults remain sandbox', 'test-payment.momo.vn' in app_yml)
check('No merchant credentials are added to source env example', re.search(r'^VNPAY_HASH_SECRET=\s*$',env_example,re.M) and re.search(r'^MOMO_SECRET_KEY=\s*$',env_example,re.M))

check('VNPay injects configured IPN URL used by readiness', '@Value("${app.payment.vnpay.ipn-url}") private String ipnUrl;' in vnpay)
check('VNPay exposes only safe endpoint metadata for readiness', all(x in vnpay for x in ['public String paymentUrl()','public String queryUrl()','public String returnUrl()','public String ipnUrl()']))
check('MoMo exposes only safe endpoint metadata for readiness', all(x in momo for x in ['public String createUrl()','public String queryUrl()','public String redirectUrl()','public String ipnUrl()']))
check('VNPay merchant identity validates vnp_TmnCode', 'merchantMatches' in vnpay and 'vnp_TmnCode' in vnpay and 'constantTimeEquals(actual,tmnCode)' in vnpay)
check('MoMo merchant identity validates partnerCode', 'merchantMatches' in momo and 'partnerCode' in momo and 'constantTimeEquals(actual,partnerCode)' in momo)
check('Merchant comparison requires configured gateway', 'if(!configured()) return false;' in vnpay and 'if(!configured()) return false;' in momo)

check('Payment service injects production readiness guard', 'PaymentProductionReadinessService productionReadiness' in payment)
check('Provider availability invokes production readiness guard', 'productionReadiness.ensureAllowed(provider)' in payment)
check('V60 preserves explicit provider credential checks', 'VNPay chưa được cấu hình merchant credentials' in payment and 'MoMo chưa được cấu hình merchant credentials' in payment)
check('VNPay IPN still verifies signature first', 'boolean signatureValid=vnPay.verify(params)' in payment)
check('MoMo IPN still verifies signature first', 'boolean signatureValid=momo.verifyIpn(params)' in payment)
check('VNPay IPN validates merchant identity', 'if(!vnPay.merchantMatches(params))' in payment and 'INVALID_MERCHANT' in payment)
check('MoMo IPN validates merchant identity', 'if(!momo.merchantMatches(params))' in payment and 'INVALID_MERCHANT' in payment)
check('VNPay return validates merchant identity', 'merchantValid=signatureValid&&vnPay.merchantMatches(params)' in payment)
check('MoMo return validates merchant identity', 'merchantValid=signatureValid&&momo.merchantMatches(params)' in payment)
check('Return callbacks remain read-only views', 'public PaymentReturnResponse vnPayReturn' in payment and 'public PaymentReturnResponse momoReturn' in payment and 'returnView' in payment)
check('Amount validation remains enforced for VNPay', 'validVnPayAmount' in payment and 'INVALID_AMOUNT' in payment)
check('Amount validation remains enforced for MoMo', 'validMomoAmount' in payment and 'INVALID_AMOUNT' in payment)

check('Webhook claim distinguishes NEW DUPLICATE CONFLICT', 'enum WebhookClaim { NEW, DUPLICATE, CONFLICT }' in payment)
check('Webhook DB claim still uses unique provider/event key insert', 'ON CONFLICT (provider, event_key) DO NOTHING' in webhook_repo)
check('Duplicate callback compares stored payload hash', 'existing.getPayloadHash(),payloadHash' in payment and 'WebhookClaim.DUPLICATE' in payment)
check('Different payload under same event key becomes conflict', 'WebhookClaim.CONFLICT' in payment and 'Replay payload mismatch' in payment)
check('Replay conflict does not call finishWebhook before rejection', 'recordReplayConflict' in payment and 'return Map.of("RspCode","97","Message","Replay payload mismatch")' in payment)
check('Replay conflict is durable in payment timeline', 'WEBHOOK_REPLAY_CONFLICT' in payment and 'PAYLOAD_MISMATCH' in payment)
check('Replay conflict states payment is not changed', 'trạng thái payment không được thay đổi' in payment)
check('Identical VNPay duplicate reuses prior merchant response', 'WebhookClaim.DUPLICATE)return previousVnPayResponse(eventKey)' in payment)
check('Identical MoMo duplicate reuses prior merchant response', 'WebhookClaim.DUPLICATE)return previousMomoResponse(eventKey)' in payment)
check('Invalid signature callbacks remain auditable', payment.count('INVALID_SIGNATURE')>=2 and payment.count('WEBHOOK_REJECTED')>=4)
check('Invalid merchant callbacks remain auditable', payment.count('INVALID_MERCHANT')>=2)

check('Admin DTO exposes safe gateway readiness contract', 'record GatewayReadiness' in dtos and 'checkoutHost' in dtos and 'ipnHost' in dtos)
check('Admin DTO exposes overall production readiness', 'record ProductionReadiness' in dtos and 'allRemoteProductionReady' in dtos)
check('Admin payment dashboard embeds readiness', 'ProductionReadiness readiness' in dtos)
check('Admin payment service injects readiness service', 'PaymentProductionReadinessService productionReadiness' in admin_service)
check('Admin dashboard includes readiness snapshot', 'productionReadiness.snapshot()' in admin_service)
check('Admin service exposes readiness endpoint model', 'public ProductionReadiness productionReadiness()' in admin_service)
check('Admin controller exposes production readiness endpoint', '@GetMapping("/production-readiness")' in admin_controller)
check('Production readiness endpoint remains under admin payments RBAC', '@RequestMapping("/api/admin/payments")' in admin_controller)

check('Frontend V60 readiness types exist', all(x in types for x in ['PaymentGatewayReadinessV60','PaymentProductionReadinessV60','readiness:PaymentProductionReadinessV60']))
check('Admin payment page is branded V60', 'Payment Production · V60' in page and 'Payment Production Readiness · V60' in page)
check('Admin payment page renders readiness panel', 'data-testid="payment-production-readiness-v60"' in page)
check('Admin payment page renders gateway-specific readiness cards', 'payment-readiness-${g.provider.toLowerCase()}-v60' in page)
check('Admin payment page displays production guard state', 'Production guard' in page and 'data.readiness.guardEnabled' in page)
check('Admin payment page displays production overall state', 'payment-production-overall-v60' in page and 'CHƯA SẴN SÀNG PRODUCTION' in page)
check('Admin payment page states secrets are not displayed', 'Không hiển thị secret' in page)
check('Admin payment page explains webhook replay policy', 'event-key/payload replay consistency' in page and 'payload khác cùng event key bị từ chối' in page)
check('Admin dashboard links Payment Production V60', '/admin/payments' in admin and 'Payment Production V60' in admin)
check('Header exposes Payment Production V60', header.count('/admin/payments')>=2 and header.count('Payment Production V60')>=2)

check('V60 Playwright journey exists', 'V60 admin sees production gateway readiness without exposing secrets' in e2e)
check('V60 Playwright authenticates admin', 'E2E_ADMIN_EMAIL' in e2e and 'E2E_ADMIN_PASSWORD' in e2e)
check('V60 Playwright checks production readiness panel', 'payment-production-readiness-v60' in e2e)
check('V60 Playwright checks VNPay readiness', 'payment-readiness-vnpay-v60' in e2e)
check('V60 Playwright checks MoMo readiness', 'payment-readiness-momo-v60' in e2e)
check('V60 Playwright checks honest unconfigured CI state', 'NOT CONFIGURED' in e2e and 'CHƯA SẴN SÀNG PRODUCTION' in e2e)
check('V60 Playwright rejects secret labels in rendered UI', all(x in e2e for x in ['not.toContain("VNPAY_HASH_SECRET")','not.toContain("MOMO_SECRET_KEY")','not.toContain("MOMO_ACCESS_KEY")']))
check('Provider availability never renders credential environment-key names', all(x not in payment for x in ['VNPAY_HASH_SECRET','MOMO_SECRET_KEY','MOMO_ACCESS_KEY','VNPAY_TMN_CODE','MOMO_PARTNER_CODE']))
check('Legacy booking flow follows current V60 payment UI contract', 'Thanh toán production & đối soát' in booking_e2e and 'Payment Production · V60' in booking_e2e and 'Payment Operations · V47' not in booking_e2e and 'Đối soát thanh toán' not in booking_e2e)
check('V60 Playwright does not call live gateway', 'vnpayment.vn' not in e2e and 'momo.vn' not in e2e)

ci_match=re.search(r'name:\s*V26-V(\d+) source regression',ci)
check('Main CI source regression extends through V60', bool(ci_match) and int(ci_match.group(1))>=60)
check('Main CI runs V60 source gate', 'Verify V60 Payment Production 4.0' in ci and 'verify_v60_payment_production_4.py' in ci)
check('RC default remains V60-or-newer', bool(re.search(r'default: "v(?:60|6[1-9]|[7-9][0-9])\.0\.0-rc\.1"',rc)))
check('RC compose namespace remains V60-or-newer', bool(re.search(r'cinebooking_v(?:60|6[1-9]|[7-9][0-9])_rc_',rc)))
check('RC runs V60 source gate', 'Verify V60 source gate' in rc and 'verify_v60_payment_production_4.py' in rc)
check('RC browser gate label includes V60', '+ V60' in rc)
check('Stable default remains 60.0.0-or-newer', bool(re.search(r'default: "(?:60|6[1-9]|[7-9][0-9])\.0\.0"',release)))
check('Stable compose namespace remains V60-or-newer', bool(re.search(r'cinebooking_v(?:60|6[1-9]|[7-9][0-9])_release_',release)))
check('Stable release runs V60 source gate', 'Verify V60 source gate' in release and 'verify_v60_payment_production_4.py' in release)
check('V59 verifier is forward compatible with V60 release metadata', 'V59 or later' in v59verify and "'+ V59' in rc" in v59verify)
check('Makefile exposes V60 lifecycle', all(x in make for x in ['verify-v60:','diagnose-v60:','verify-seed-demo-v60:','check-seed-demo-v60:','verify-reference-v60:','audit-realistic-data-v60:']))
check('V60 diagnostics chains payment V59 V60 and realistic data gates', all(x in diagnose for x in ['verify_v47_payment_gateway_operations.py','verify_v59_realtime_operations_4.py','verify_v60_payment_production_4.py','verify_realistic_data_57.py','V60 source diagnostics passed.']))

check('README preserves V60 documentation under V60-or-newer release', '## V60 - Payment Production 4.0' in readme and bool(re.search(r'^# CineBooking Pro V(?:60|6[1-9]|[7-9][0-9])$',readme,re.M)))
check('README history contains V60 row', '**V60**' in readme and 'webhook replay-conflict protection' in readme)
check('README documents V60 readiness endpoint', 'GET /api/admin/payments/production-readiness' in readme)
check('README documents HTTPS production guard', 'PAYMENT_PRODUCTION_GUARD_ENABLED=true' in readme and 'return URL HTTPS public' in readme and 'IPN URL HTTPS public' in readme)
check('README documents merchant identity validation', 'vnp_TmnCode / partnerCode' in readme)
check('README documents replay conflict behavior', 'WEBHOOK_REPLAY_CONFLICT' in readme and 'Replay payload mismatch' in readme)
check('README documents no-schema 57-table contract', 'V60 không tạo Flyway migration mới' in readme and '= 57 public tables' in readme)
check('README documents V60 release tags', 'v60.0.0-rc.1' in readme and 'v60.0.0' in readme)
check('No V60 Flyway migration was added', not any((ROOT/'backend/src/main/resources/db/migration').glob('V60__*.sql')))

# The browser suite should gain exactly the V60 declaration while keeping all previous journeys.
playwright_tests=0
for f in (ROOT/'frontend/e2e').glob('*.spec.ts'):
    playwright_tests += len(re.findall(r'\btest\s*\(', f.read_text(encoding='utf-8')))
check('Playwright suite declares at least 28 journeys after V60', playwright_tests>=28)

passed=sum(ok for _,ok in checks)
print(f"\nV60 verification: {passed}/{len(checks)} checks passed")
raise SystemExit(0 if passed==len(checks) else 1)
