from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]

def text(path):
    p=ROOT/path
    return p.read_text(encoding='utf-8') if p.exists() else ''

checks=[]
def check(name, ok):
    checks.append((name,bool(ok)))
    print(('PASS' if ok else 'FAIL')+': '+name)

service=text('backend/src/main/java/com/cinebooking/pricing/DynamicPricingIntelligenceService.java')
pricing=text('backend/src/main/java/com/cinebooking/pricing/PricingService.java')
dtos=text('backend/src/main/java/com/cinebooking/pricing/PricingDtos.java')
controller=text('backend/src/main/java/com/cinebooking/pricing/AdminPricingController.java')
booking_repo=text('backend/src/main/java/com/cinebooking/booking/BookingRepository.java')
booking_seat_repo=text('backend/src/main/java/com/cinebooking/booking/BookingSeatRepository.java')
seat_repo=text('backend/src/main/java/com/cinebooking/seat/SeatRepository.java')
seat_service=text('backend/src/main/java/com/cinebooking/seat/SeatService.java')
app_yml=text('backend/src/main/resources/application.yml')
env_example=text('.env.example')
page=text('frontend/app/admin/pricing/page.tsx')
types=text('frontend/lib/types.ts')
admin=text('frontend/app/admin/page.tsx')
header=text('frontend/components/Header.tsx')
e2e=text('frontend/e2e/dynamic-pricing-v62.spec.ts')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v62.ps1')
readme=text('README.md')

check('V62 intelligence service exists', bool(service))
check('V62 strategy version explicit', 'V62_RULESET_1' in service)
check('V62 service is Spring service', '@Service' in service)
check('V62 reads booking-seat repository', 'BookingSeatRepository' in service)
check('V62 reads booking repository', 'BookingRepository' in service)
check('V62 reads seat repository', 'SeatRepository' in service)
check('V62 measures active seat reservations', 'countActiveByShowtimeId' in service)
check('V62 measures sellable seats', 'countSellableByAuditoriumId' in service)
check('V62 excludes BLOCKED seats from denominator', "seat_type <> 'BLOCKED'" in seat_repo)
check('V62 measures booking attempts in 30m', 'countByShowtimeIdAndCreatedAtAfter' in service and '30 * 60L' in service)
check('Booking repository exposes recent showtime count', 'countByShowtimeIdAndCreatedAtAfter' in booking_repo)
check('V62 lead time derives from actual showtime start', 'Duration.between(now, showtime.getStartTime())' in service)
check('V62 occupancy is bounded to 100', '.min(BigDecimal.valueOf(100))' in service)
check('V62 automation can be disabled by config', 'app.pricing.intelligence.enabled' in service)
check('V62 discount bound is configurable', 'app.pricing.intelligence.max-discount-percent' in service)
check('V62 surcharge bound is configurable', 'app.pricing.intelligence.max-surcharge-percent' in service)
check('V62 config bounds discount safely', 'Math.max(0, Math.min(50, maxDiscountPercent))' in service)
check('V62 config bounds surcharge safely', 'Math.max(0, Math.min(100, maxSurchargePercent))' in service)
check('V62 default automatic discount floor is 10', '${app.pricing.intelligence.max-discount-percent:10}' in service)
check('V62 default automatic surcharge ceiling is 25', '${app.pricing.intelligence.max-surcharge-percent:25}' in service)
check('V62 low occupancy gives small discount', 'occupancy.compareTo(BigDecimal.valueOf(30)) < 0) return -3' in service)
check('V62 high occupancy gives +6', 'occupancy.compareTo(BigDecimal.valueOf(70)) >= 0) return 6' in service)
check('V62 peak occupancy gives +12', 'occupancy.compareTo(BigDecimal.valueOf(85)) >= 0) return 12' in service)
check('V62 warm demand gives +3', 'attempts30m >= 3) return 3' in service)
check('V62 hot demand gives +6', 'attempts30m >= 6) return 6' in service)
check('V62 seven-day early booking gives -4', 'BigDecimal.valueOf(168)) >= 0) return -4' in service)
check('V62 within 24h gives +3', 'BigDecimal.valueOf(24)) <= 0) return 3' in service)
check('V62 within 6h gives +5', 'BigDecimal.valueOf(6)) <= 0) return 5' in service)
check('V62 applies lower/upper automatic guard', 'Math.max(-maxDiscountPercent, Math.min(maxSurchargePercent, raw))' in service)
check('V62 returns all three explainable signals', all(x in service for x in ['"OCCUPANCY"','"DEMAND_VELOCITY"','"LEAD_TIME"']))
check('V62 signal evidence is human-readable', all(x in service for x in ['"Mức lấp đầy"','"Tốc độ nhu cầu"','"Thời gian tới suất chiếu"']))
check('V62 simulation is calculation only', 'simulate(DynamicPricingSimulationRequest request)' in service and 'save(' not in service)
check('V62 simulation does not call booking create', 'BookingService' not in service)
check('V62 strategy documents manual/additive policy', 'manual admin rules remain explicit and additive' in service)
check('V62 strategy documents historical snapshot', 'booking_seat.price stores the final historical snapshot' in service)

check('Pricing DTO exposes strategy response', 'DynamicPricingStrategyResponse' in dtos)
check('Pricing DTO exposes simulator request', 'DynamicPricingSimulationRequest' in dtos)
check('Pricing DTO validates occupancy 0-100', '@DecimalMin("0") @DecimalMax("100") BigDecimal occupancyRate' in dtos)
check('Pricing DTO validates nonnegative demand', '@Min(0) @Max(10000) Integer bookingAttempts30m' in dtos)
check('Pricing DTO validates positive reference price', '@DecimalMin("1")' in dtos and 'referencePrice' in dtos)
check('Quote response separates manual adjustment', 'manualDynamicAdjustment' in dtos)
check('Quote response separates intelligence adjustment', 'intelligenceAdjustment' in dtos)
check('Quote response exposes intelligence percent', 'intelligencePercent' in dtos)
check('Quote response exposes occupancy', 'occupancyRate' in dtos and 'activeSeatReservations' in dtos and 'sellableSeats' in dtos)
check('Quote response exposes demand velocity', 'bookingAttempts30m' in dtos)
check('Quote response exposes lead time', 'leadTimeHours' in dtos)
check('Quote response exposes strategy version', 'strategyVersion' in dtos)
check('Quote response exposes explainable signals', 'List<DynamicPricingSignal> intelligenceSignals' in dtos)

check('PricingService injects V62 intelligence', 'DynamicPricingIntelligenceService intelligence' in pricing)
check('PricingService snapshots market once per context', 'intelligence.snapshot(showtime,auditorium)' in pricing)
check('PricingService evaluates automatic price on before value', 'intelligence.evaluate(context.market(),before)' in pricing)
check('Manual rule remains independently calculated', 'manualDynamic=manualDynamic.add(amount)' in pricing)
check('Automatic adjustment is additive to manual', 'manualDynamic.add(automatic.adjustmentAmount())' in pricing)
check('Final historical quote remains nonnegative', '.max(BigDecimal.ZERO).setScale(0,RoundingMode.HALF_UP)' in pricing)
check('PricingService returns V62 strategy version', 'DynamicPricingIntelligenceService.STRATEGY_VERSION' in pricing)
check('Pricing context carries market snapshot', 'DynamicPricingIntelligenceService.MarketSnapshot market' in pricing)
check('PriceQuote carries both manual and automatic components', all(x in pricing for x in ['manualDynamicAdjustment','intelligenceAdjustment','intelligencePercent','intelligenceSignals']))

check('Admin pricing exposes strategy GET', '@GetMapping("/strategy")' in controller)
check('Admin pricing exposes simulator POST', '@PostMapping("/simulate")' in controller)
check('Admin pricing simulator is validated', '@Valid @RequestBody DynamicPricingSimulationRequest' in controller)
check('Admin pricing keeps existing preview', '@PostMapping("/preview")' in controller)

check('Application config enables V62 by default', 'PRICING_INTELLIGENCE_ENABLED:true' in app_yml)
check('Application config exposes discount guard', 'PRICING_INTELLIGENCE_MAX_DISCOUNT_PERCENT:10' in app_yml)
check('Application config exposes surcharge guard', 'PRICING_INTELLIGENCE_MAX_SURCHARGE_PERCENT:25' in app_yml)
check('Env example documents V62 enable flag', 'PRICING_INTELLIGENCE_ENABLED=true' in env_example)
check('Env example documents V62 bounds', 'PRICING_INTELLIGENCE_MAX_DISCOUNT_PERCENT=10' in env_example and 'PRICING_INTELLIGENCE_MAX_SURCHARGE_PERCENT=25' in env_example)

check('Seat map includes V62 explainable labels', 'V62 " + x.label()' in seat_service)
check('Seat map includes only nonzero V62 signals', '.filter(x->x.adjustmentPercent()!=0)' in seat_service)
check('Seat map still uses real quote price', 'quote.finalPrice()' in seat_service and 'quote.dynamicAdjustment()' in seat_service)

check('Frontend V62 pricing page exists', bool(page))
check('Frontend is branded Dynamic Pricing 4.0', 'Dynamic Pricing 4.0' in page)
check('Frontend V62 root test id exists', 'data-testid="dynamic-pricing-v62"' in page)
check('Frontend strategy test id exists', 'dynamic-pricing-strategy-v62' in page)
check('Frontend simulator test id exists', 'dynamic-pricing-simulator-v62' in page)
check('Frontend simulator result test id exists', 'dynamic-pricing-simulation-result-v62' in page)
check('Frontend reads strategy API', 'api<DynamicPricingStrategyV62>("/admin/pricing/strategy")' in page)
check('Frontend posts simulator API', 'api<DynamicPricingSimulationV62>("/admin/pricing/simulate"' in page)
check('Frontend explicitly says simulator does not write DB', 'không ghi database' in page)
check('Frontend renders automation bounds', 'strategy.maxDiscountPercent' in page and 'strategy.maxSurchargePercent' in page)
check('Frontend renders occupancy market snapshot', 'quote.occupancyRate' in page and 'quote.activeSeatReservations' in page and 'quote.sellableSeats' in page)
check('Frontend renders booking velocity snapshot', 'quote.bookingAttempts30m' in page)
check('Frontend renders lead time snapshot', 'quote.leadTimeHours' in page)
check('Frontend separates manual price component', 'quote.manualDynamicAdjustment' in page)
check('Frontend separates intelligence component', 'quote.intelligenceAdjustment' in page and 'quote.intelligencePercent' in page)
check('Frontend renders explainable signals', 'quote.intelligenceSignals.map' in page and 's.evidence' in page)
check('Frontend keeps manual rule editor', 'Tạo quy tắc giá' in page and '/admin/pricing/rules' in page)
check('Frontend V62 types exist', all(x in types for x in ['DynamicPricingSignalV62','DynamicPricingStrategyV62','DynamicPricingSimulationV62']))
check('Frontend quote type includes V62 fields', all(x in types for x in ['manualDynamicAdjustment','intelligenceAdjustment','occupancyRate','bookingAttempts30m','leadTimeHours','strategyVersion']))
check('Admin dashboard links V62 pricing', '/admin/pricing' in admin and 'Dynamic Pricing V62' in admin)
check('Header links V62 pricing', '/admin/pricing' in header and 'Dynamic Pricing V62' in header)

check('V62 browser E2E exists', bool(e2e))
check('V62 E2E logs in as admin', 'admin-v29@cine.local' in e2e and 'page.goto("/login")' in e2e)
check('V62 E2E visits pricing page', 'page.goto("/admin/pricing")' in e2e)
check('V62 E2E checks strategy version', 'V62_RULESET_1' in e2e)
check('V62 E2E checks guard bounds', '"-10%"' in e2e and '"+25%"' in e2e)
check('V62 E2E uses no-write simulator', 'không ghi database' in e2e)
check('V62 E2E checks deterministic +12 scenario', 'toContainText("+12%")' in e2e)
check('V62 E2E checks all three signal labels', all(x in e2e for x in ['Mức lấp đầy','Tốc độ nhu cầu','Thời gian tới suất chiếu']))

check('CI source regression renamed through V62', 'V26-V62 source regression' in ci)
check('CI runs V62 verifier', 'python3 tools/verify_v62_dynamic_pricing_4.py' in ci)
check('RC defaults to V62 RC1', 'default: "v62.0.0-rc.1"' in rc)
check('RC compose project is V62', 'cinebooking_v62_rc_${{ github.run_id }}' in rc)
check('RC runs V62 verifier', 'python3 tools/verify_v62_dynamic_pricing_4.py' in rc)
check('RC browser label includes V62', '+ V61 + V62)' in rc)
check('Stable defaults to 62.0.0', 'default: "62.0.0"' in release)
check('Stable compose project is V62', 'cinebooking_v62_release_${{ github.run_id }}' in release)
check('Stable runs V62 verifier', 'python3 tools/verify_v62_dynamic_pricing_4.py' in release)
check('Makefile exposes verify-v62', 'verify-v62:' in make and 'verify_v62_dynamic_pricing_4.py' in make)
check('Makefile exposes diagnose-v62', 'diagnose-v62:' in make)
check('V62 diagnose script exists', bool(diagnose) and 'verify_v62_dynamic_pricing_4.py' in diagnose)

check('README current release is V62', '# CineBooking Pro V62' in readme and 'Current release:** V62' in readme)
check('README documents V62 section', '## V62 - Dynamic Pricing 4.0' in readme)
check('README documents three real-data signals', all(x in readme for x in ['Occupancy realtime','Demand velocity','Lead time']))
check('README documents automation bounds', 'PRICING_INTELLIGENCE_MAX_DISCOUNT_PERCENT' in readme and 'PRICING_INTELLIGENCE_MAX_SURCHARGE_PERCENT' in readme)
check('README documents manual rule independence', 'Manual pricing rule V18 vẫn cộng độc lập' in readme)
check('README documents historical booking price snapshot', 'booking_seat.price' in readme)
check('README documents V62 APIs', all(x in readme for x in ['/api/admin/pricing/strategy','/api/admin/pricing/simulate','/api/admin/pricing/preview']))
check('README preserves 57 public table contract', '57 public tables' in readme and 'Flyway latest: V52' in readme)
check('README documents V62 release tags', 'v62.0.0-rc.1' in readme and 'v62.0.0' in readme)

migrations=list((ROOT/'backend/src/main/resources/db/migration').glob('V62__*.sql'))
check('V62 adds no Flyway migration', len(migrations)==0)
check('V62 adds no synthetic pricing entity', not (ROOT/'backend/src/main/java/com/cinebooking/domain/DynamicPricingSnapshot.java').exists())
check('V62 reuses existing operational tables', all(x in readme for x in ['booking','booking_seat','seat','showtime','pricing_rule']))
check('Playwright declarations reach 30 journeys', sum(1 for _ in (ROOT/'frontend/e2e').glob('*.spec.ts')) == 30)

passed=sum(1 for _,ok in checks if ok)
print(f"V62 verification: {passed}/{len(checks)} checks passed")
if passed!=len(checks):
    print('Failed checks:')
    for name,ok in checks:
        if not ok: print(' - '+name)
    raise SystemExit(1)
