from pathlib import Path
import re
import sys

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name, cond):
    cond=bool(cond);checks.append((name,cond));print(f"[ {'OK' if cond else 'FAIL'} ] {name}")

migration=text('backend/src/main/resources/db/migration/V47__payment_gateway_operations_2.sql')
payment=text('backend/src/main/java/com/cinebooking/domain/Payment.java')
event=text('backend/src/main/java/com/cinebooking/domain/PaymentEvent.java')
status=text('backend/src/main/java/com/cinebooking/domain/PaymentStatus.java')
attempt=text('backend/src/main/java/com/cinebooking/payment/PaymentAttemptService.java')
service=text('backend/src/main/java/com/cinebooking/payment/PaymentService.java')
controller=text('backend/src/main/java/com/cinebooking/payment/PaymentController.java')
admin_service=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentService.java')
admin_controller=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentController.java')
job=text('backend/src/main/java/com/cinebooking/payment/PaymentReconciliationJob.java')
rules=text('backend/src/main/java/com/cinebooking/payment/PaymentRetryRules.java')
rules_test=text('backend/src/test/java/com/cinebooking/payment/PaymentRetryRulesTest.java')
dtos=text('backend/src/main/java/com/cinebooking/payment/PaymentDtos.java')
admin_dtos=text('backend/src/main/java/com/cinebooking/payment/AdminPaymentDtos.java')
repo=text('backend/src/main/java/com/cinebooking/payment/PaymentRepository.java')
event_repo=text('backend/src/main/java/com/cinebooking/payment/PaymentEventRepository.java')
event_service=text('backend/src/main/java/com/cinebooking/payment/PaymentEventService.java')
booking=text('frontend/app/booking/[showtimeId]/page.tsx')
history=text('frontend/app/payments/page.tsx')
admin_page=text('frontend/app/admin/payments/page.tsx')
types=text('frontend/lib/types.ts')
e2e=text('frontend/e2e/booking-flow.spec.ts')
app=text('backend/src/main/resources/application.yml')
env=text('.env.example')
compose=text('docker-compose.yml')
it=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
readme=text('README.md')
seed=text('tools/seed-demo-50-tables-10-rows.sql')

check('V47 migration adds payment attempt lineage', all(x in migration for x in ['attempt_no','retry_of_payment_id','uq_payment_booking_attempt_no','idx_payment_retry_parent']))
check('V47 migration adds cancellation and reconciliation metadata', all(x in migration for x in ['cancelled_at','last_reconciled_at','next_reconcile_at','reconciliation_failures','last_reconcile_message','idx_payment_reconcile_due']))
check('V47 migration creates append-only payment_event timeline', 'CREATE TABLE payment_event' in migration and 'idx_payment_event_payment_created' in migration and 'idx_payment_event_type_created' in migration)
check('V47 migration backfills honest migration events', 'MIGRATED_TO_V47' in migration and "'MIGRATION'" in migration and 'Payment row upgraded to V47 attempt lineage and event timeline' in migration)
check('Payment entity maps V47 lineage and reconciliation fields', all(x in payment for x in ['attemptNo','retryOfPaymentId','cancelledAt','lastReconciledAt','nextReconcileAt','reconciliationFailures','lastReconcileMessage']))
check('PaymentEvent entity maps append-only event records', '@Table(name="payment_event"' in event and all(x in event for x in ['eventType','actorType','fromStatus','toStatus','detailsJson']))
check('Payment status includes CANCELLED', 'CANCELLED' in status)
check('Payment repository exposes attempt sequencing and due reconciliation queries', all(x in repo for x in ['maxAttemptNo','findDueForReconciliation','countByNextReconcileAtIsNotNullAndNextReconcileAtLessThanEqual']))
check('Payment event repository exposes chronological timeline', 'PaymentEventRepository' in event_repo and 'findByPaymentIdOrderByCreatedAtAsc' in event_repo)
check('Payment event service records and reads durable timeline', 'events.save' in event_service and 'timeline' in event_service)
check('Attempt service allocates deterministic per-booking attempt numbers', 'maxAttemptNo' in attempt and 'return (max==null?0:max)+1' in attempt)
check('Attempt service creates retry lineage and next attempt number', 'setRetryOfPaymentId' in attempt and 'setAttemptNo' in attempt and 'nextAttempt' in attempt and 'PaymentStatus.CANCELLED' in attempt)
check('Retry rules only allow FAILED/CANCELLED before booking expiry', 'PaymentStatus.FAILED' in rules and 'PaymentStatus.CANCELLED' in rules and 'bookingExpiresAt.isAfter(now)' in rules)
check('Retry rules explicitly block REVIEW', 'reviewCannotRetryBecauseChargeMayHaveSucceeded' in rules_test and 'PaymentStatus.REVIEW' in rules_test)
check('Retry/cancel rule unit tests cover five V47 cases', rules_test.count('@Test') >= 5 and 'expiredBookingCannotRetry' in rules_test)
check('Payment service creates event timeline for create retry cancel success and review', all(x in service for x in ['PAYMENT_CREATED','PAYMENT_RETRY_CREATED','PAYMENT_CANCELLED','PAYMENT_SUCCEEDED','PAYMENT_REVIEW_REQUIRED']))
check('Customer cancellation keeps booking alive instead of cancelling booking', 'booking vẫn được giữ đến khi hết hạn' in service and 'p.setStatus(PaymentStatus.CANCELLED)' in service)
check('Payment service exposes safe retry flow', 'public PaymentStartResponse retry(' in service and 'attempts.retry' in service and 'ensureProviderAvailable' in service)
check('Provider readiness hides unconfigured real gateways', 'new ProviderAvailability("VNPAY"' in service and 'vnPay.configured(),vnPay.configured()' in service and 'new ProviderAvailability("MOMO"' in service and 'momo.configured(),momo.configured()' in service)
check('Provider readiness keeps local MOCK honest', 'Thanh toán nội bộ (MOCK)' in service and 'mockEnabled' in service and 'Sẵn sàng cho local/CI' in service)
check('Payment controller exposes retry cancel and timeline endpoints', '@PostMapping("/{paymentId}/retry")' in controller and '@PostMapping("/{paymentId}/cancel")' in controller and '@GetMapping("/{paymentId}/timeline")' in controller)
check('V47 DTOs carry attempt lineage provider readiness and timeline', all(x in dtos for x in ['RetryPaymentRequest','attemptNo','retryOfPaymentId','ProviderAvailability','PaymentEventItem']))
check('Admin service supports manual and due-batch reconciliation', 'reconcileDue' in admin_service and 'setReconciliationFailures' in admin_service and 'setNextReconcileAt' in admin_service)
check('Admin controller exposes payment timeline and reconcile-due', '/{id}/timeline' in admin_controller and '/reconcile-due' in admin_controller)
check('Admin DTOs include provider readiness and batch reconciliation', 'BatchReconciliationResult' in admin_dtos and 'PaymentTimelineAdmin' in admin_dtos and 'providers' in admin_dtos)
check('Automatic reconciliation job is feature-flagged', 'PaymentReconciliationJob' in job and 'app.payment.reconcile.auto-enabled:false' in job and 'reconcileDue' in job)
check('Automatic reconciliation defaults OFF in app env and compose', 'PAYMENT_AUTO_RECONCILE_ENABLED:false' in app and 'PAYMENT_AUTO_RECONCILE_ENABLED=false' in env and 'PAYMENT_AUTO_RECONCILE_ENABLED: ${PAYMENT_AUTO_RECONCILE_ENABLED:-false}' in compose)
check('Checkout renders only enabled provider options', 'providerReady("MOCK")' in booking and 'providerReady("VNPAY")' in booking and 'providerReady("MOMO")' in booking and 'Thanh toán nội bộ (MOCK)' in booking and '!providerReady(provider)' in booking)
check('Customer Payment Center supports cancel retry and timeline', 'Payment Center · V47' in history and 'Hủy lần thanh toán' in history and 'Thử lại thanh toán' in history and 'Xem timeline' in history)
check('Admin Payment Operations shows readiness attempts due reconcile and timeline', ('Payment Operations · V47' in admin_page or 'Payment Production · V60' in admin_page) and 'Attempt' in admin_page and 'Due reconcile' in admin_page and 'Đối soát giao dịch đến hạn' in admin_page and 'Timeline' in admin_page)
check('Frontend V47 types include provider readiness timeline and batch results', all(x in types for x in ['PaymentProviderAvailability','PaymentEventItem','PaymentBatchReconciliationResult','attemptNo','retryOfPaymentId']))
check('Booking E2E verifies V47 payment timeline', ('Payment Operations · V47' in e2e or 'Payment Production · V60' in e2e) and 'Xem timeline' in e2e and 'PAYMENT_SUCCEEDED' in e2e)
check('Dedicated V47 E2E covers failed retry cancel retry success lineage', all(x in text('frontend/e2e/payment-operations-v47.spec.ts') for x in ['Lần #1','FAILED','Lần #2','CANCELLED','PAYMENT_CANCELLED','Lần #3','PAYMENT_RETRY_CREATED','PAYMENT_SUCCEEDED']))
check('Testcontainers expects Flyway V47 or newer and payment_event schema', bool(re.search(r'isEqualTo\("(?:4[7-9]|[5-9][0-9])"\)',it)) and 'payment_event' in it and 'idx_payment_reconcile_due' in it and 'uq_payment_booking_attempt_no' in it)
check('V47 reference seed covers payment_event without fake VNPay/MoMo history', 'INSERT INTO payment_event' in seed and 'PAYMENT_HISTORY_IMPORTED' in seed and 'V47_REFERENCE_SYNC' in seed and "'MOCK'" in seed)
check('V47 50-table verifier exists and is wired', Path(ROOT/'tools/verify_seed_demo_50.py').exists() and 'Seed V47 50-table realistic-data verification' in text('tools/verify_seed_demo_50.py'))
check('Main CI includes V47 source gate in V47-or-newer regression', bool(re.search(r'V26-V(?:4[7-9]|[5-9][0-9]) source regression',ci)) and 'verify_v47_payment_gateway_operations.py' in ci and ('verify_seed_demo_50.py' in ci or 'verify_seed_demo_52.py' in ci))
check('Standalone RC defaults to V47-or-newer candidate and keeps V47 gate', bool(re.search(r'default: "v(?:4[7-9]|[5-9][0-9])\.0\.0-rc\.1"',rc)) and 'verify_v47_payment_gateway_operations.py' in rc)
check('Stable release defaults to V47-or-newer and keeps V47 gate', bool(re.search(r'default: "(?:4[7-9]|[5-9][0-9])\.0\.0"',release)) and bool(re.search(r'cinebooking_v(?:4[7-9]|[5-9][0-9])_release_\$\{\{ github\.run_id \}\}',release)) and 'verify_v47_payment_gateway_operations.py' in release)
check('Makefile exposes V47 verify diagnose seed and reference targets', all(x in make for x in ['verify-v47:','diagnose-v47:','seed-demo-v47:','check-seed-demo-v47:','verify-reference-v47:','seed-reference-v47:']))
check('V47 diagnostics chains V46 V47 and 50-table seed', all(x in text('tools/diagnose-v47.ps1') for x in ['verify_v46_security_account_protection.py','verify_v47_payment_gateway_operations.py','verify_seed_demo_50.py','V47 source diagnostics passed.']))
check('README preserves V47 Payment Gateway & Operations 2.0 history', 'V47 - Payment Gateway & Operations 2.0' in readme and 'v47.0.0-rc.1' in readme)

passed=sum(1 for _,v in checks if v);total=len(checks)
print(f"\nV47 verification: {passed}/{total} checks passed")
if passed!=total:
    print('Failed checks:')
    for label,val in checks:
        if not val: print(' -',label)
sys.exit(0 if passed==total else 1)
