from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name, cond):
    ok=bool(cond); checks.append((name,ok)); print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

migration=text('backend/src/main/resources/db/migration/V51__analytics_forecasting_3.sql')
dtos=text('backend/src/main/java/com/cinebooking/analytics/AnalyticsDtos.java')
service=text('backend/src/main/java/com/cinebooking/analytics/AnalyticsForecastingService.java')
admin=text('backend/src/main/java/com/cinebooking/analytics/AdminAnalyticsService.java')
controller=text('backend/src/main/java/com/cinebooking/analytics/AdminAnalyticsController.java')
job=text('backend/src/main/java/com/cinebooking/analytics/AnalyticsSnapshotJob.java')
yml=text('backend/src/main/resources/application.yml')
env=text('.env.example')
compose=text('docker-compose.yml')
types=text('frontend/lib/types.ts')
ui=text('frontend/app/admin/analytics/page.tsx')
e2e=text('frontend/e2e/analytics-forecasting-v51.spec.ts')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
seed=text('tools/seed-demo-56-tables-10-rows.sql')
seed_verify=text('tools/verify_seed_demo_56.py')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v51.ps1')
readme=text('README.md')

check('V51 migration creates branch-specific concession cost basis', 'CREATE TABLE cinema_concession_cost_basis' in migration and 'uq_cinema_concession_cost_basis' in migration)
check('V51 cost basis is constrained to nonnegative explicit source values', 'unit_cost NUMERIC(12,2) NOT NULL CHECK (unit_cost >= 0)' in migration and "source IN ('MANUAL','REFERENCE','IMPORT')" in migration)
check('V51 migration creates durable analytics snapshots', 'CREATE TABLE analytics_snapshot' in migration and 'uq_analytics_snapshot_period' in migration)
check('V51 snapshots support DAILY WEEKLY MONTHLY only', all(x in migration for x in ["'DAILY'","'WEEKLY'","'MONTHLY'",'ck_analytics_snapshot_period_kind']))
check('V51 snapshot schema keeps concession cost and gross margin nullable as a pair', 'concession_cost NUMERIC(14,2)' in migration and 'gross_margin NUMERIC(14,2)' in migration and 'ck_analytics_snapshot_cost_pair' in migration)
check('V51 snapshot schema stores forecast algorithm and next-7-day value', 'forecast_next_7d' in migration and "DEFAULT 'V51-WEEKDAY-WEIGHTED-MA-1'" in migration)
check('V51 migration indexes branch cost and snapshot reads', all(x in migration for x in ['idx_cinema_concession_cost_basis_product','idx_analytics_snapshot_cinema_period','idx_analytics_snapshot_generated']))
check('V51 forecasting algorithm version is explicit', 'public static final String FORECAST_ALGORITHM = "V51-WEEKDAY-WEIGHTED-MA-1"' in service)
check('V51 forecast uses same-weekday four-week weighted moving average', 'target.minusWeeks(week)' in service and 'week <= 4' in service and 'int weight = 5 - week' in service and 'List.of(jdbcTime(historyStart), jdbcTime(historyEnd))' in service)
check('V51 forecast returns seven future points', 'offset <= 7' in service and 'new RevenueForecast(FORECAST_ALGORITHM' in service)
check('V51 period comparison uses equal windows and JDBC-safe TIMESTAMPTZ bindings', 'PeriodStats current = periodStats(currentStart, now, cinemaId)' in service and 'PeriodStats previous = periodStats(previousStart, currentStart, cinemaId)' in service and 'instant.atOffset(ZoneOffset.UTC)' in service and 'new Object[]{jdbcStart, jdbcEnd' in service)
check('V51 period comparison reports revenue bookings tickets and occupancy deltas', all(x in dtos for x in ['revenueDeltaPct','bookingsDeltaPct','ticketsDeltaPct','occupancyDeltaPoints']))
check('V51 margin computes branch concession cost coverage', 'costed_units' in service and 'costCoverageRate' in dtos and 'cinema_concession_cost_basis cb' in service)
check('Unknown concession cost remains NULL instead of silently becoming zero', 'Unknown cost stays NULL' in service and 'BigDecimal concessionCost = units == costed' in service and ': null;' in service)
check('Gross margin is withheld when concession cost coverage is incomplete', 'BigDecimal grossMargin = concessionCost == null ? null' in service and 'grossMarginRate' in dtos)
check('V51 cost-basis API can clear unknown cost by deleting the branch row', 'request.unitCost() == null' in service and 'delete from cinema_concession_cost_basis' in service)
check('V51 cost-basis API validates nonnegative values', 'request.unitCost().signum() < 0' in service and 'Giá vốn không được âm' in service)
check('V51 cost-basis upsert records MANUAL source and actor', "source='MANUAL'" in service and 'updated_by' in service and 'updatedBy' in service)
check('Admin analytics exposes GET branch cost basis', '@GetMapping("/cost-basis")' in controller and 'forecastingService.costBasis(cinemaId)' in controller)
check('Admin analytics exposes authenticated PUT branch cost basis', '@PutMapping("/cost-basis")' in controller and 'Authentication authentication' in controller and 'updateCostBasis(request, actor)' in controller)
check('V51 adds auditorium-level revenue occupancy analytics', 'public List<AuditoriumPerformance> auditoriumPerformance' in service and 'AUDITORIUM REVENUE' in ui)
check('Admin dashboard composes the V51 forecasting bundle without removing legacy analytics', 'AnalyticsForecastingService.V51Bundle v51 = forecasting.bundle(days, cinemaId)' in admin and 'v51.auditoriumPerformance()' in admin and 'v51.snapshots()' in admin)
check('Analytics DTO Dashboard appends V51 fields', all(x in dtos for x in ['PeriodComparison periodComparison','RevenueForecast forecast','MarginSummary margin','List<AuditoriumPerformance> auditoriumPerformance','List<ConcessionCostBasis> concessionCostBasis','List<AnalyticsSnapshot> snapshots']))
check('Analytics DTO retains backward-compatible constructor for V42/V43 export callers', 'Backward-compatible constructor retained for V42/V43 export tests' in dtos and 'public Dashboard(' in dtos)
check('V51 scheduler is transactional and configurable', '@Scheduled(fixedDelayString = "${app.analytics.snapshot-scan-ms:900000}")' in job and '@Transactional' in job and 'snapshot-enabled:true' in job)
check('V51 scheduler coordinates replicas with FOR UPDATE SKIP LOCKED', 'for update skip locked' in job.lower() and 'select id from cinema order by id' in job.lower())
check('V51 snapshot capture writes DAILY WEEKLY and MONTHLY closed periods', all(x in service for x in ['captureSnapshot(cinemaId, "DAILY"','captureSnapshot(cinemaId, "WEEKLY"','captureSnapshot(cinemaId, "MONTHLY"']))
check('V51 snapshot persistence is idempotent by conflict key', 'on conflict(cinema_id,period_kind,period_start) do update set' in service)
check('Runtime configuration exposes analytics snapshot feature flag and interval', 'snapshot-enabled:' in yml and 'snapshot-scan-ms:' in yml and 'ANALYTICS_SNAPSHOT_ENABLED' in env and 'ANALYTICS_SNAPSHOT_SCAN_MS' in env)
check('Both backend replicas inherit V51 snapshot environment settings', 'ANALYTICS_SNAPSHOT_ENABLED:' in compose and 'ANALYTICS_SNAPSHOT_SCAN_MS:' in compose and 'backend-2' in compose)
check('Frontend types include nullable V51 margin and branch cost contracts', 'AnalyticsMarginSummary' in types and 'concessionCost:number|null' in types and 'unitCost:number|null' in types)
check('Frontend types include period forecast auditorium and snapshot contracts', all(x in types for x in ['AnalyticsPeriodComparison','AnalyticsRevenueForecast','AnalyticsAuditoriumPerformance','AnalyticsSnapshot']))
check('V51 analytics UI identifies Analytics & Forecasting 3.0 and algorithm', 'V51 · ANALYTICS & FORECASTING 3.0' in ui and 'V51-WEEKDAY-WEIGHTED-MA-1' in ui)
check('V51 UI renders period comparison and seven-day forecast', 'data-testid="period-comparison-v51"' in ui and 'data-testid="forecast-v51"' in ui and 'Dự báo 7 ngày tới' in ui)
check('V51 UI clearly preserves NULL/unknown cost semantics', 'NULL / Chưa biết' in ui and 'không tự biến thành 0' in ui and 'Chưa đủ cost basis' in ui)
check('V51 UI supports branch cost editing and clearing by blank value', 'data-testid="cost-basis-v51"' in ui and 'raw===""?null:Number(raw)' in ui and 'Lưu cost' in ui)
check('V51 UI renders auditorium performance and scheduled snapshots', 'data-testid="auditorium-performance-v51"' in ui and 'data-testid="analytics-snapshots-v51"' in ui and 'Snapshot DAILY / WEEKLY / MONTHLY' in ui)
check('V43 Excel/CSV export labels remain forward-compatible in V51 UI', 'Xuất CSV theo từng bảng' in ui and 'Xuất Excel chi tiết' in ui and 'một file CSV UTF-8 riêng cho từng bảng' in ui and 'worksheet riêng' in ui)
check('Dedicated V51 Playwright covers forecast NULL cost and scheduler evidence', all(x in e2e for x in ['V51 admin analytics forecasts revenue and preserves unknown concession cost','period-comparison-v51','V51-WEEKDAY-WEIGHTED-MA-1','NULL / Chưa biết','FOR UPDATE ... SKIP LOCKED','Lưu cost']))
check('Integration test retains V51 schema coverage on V51-or-newer Flyway', 'analyticsV51Tables' in integration and 'cinema_concession_cost_basis' in integration and 'analytics_snapshot' in integration and (('assertThat(latest).isEqualTo("51")' in integration and 'isGreaterThanOrEqualTo(56)' in integration) or ('assertThat(latest).isEqualTo("52")' in integration and 'isGreaterThanOrEqualTo(57)' in integration)))
check('Integration test validates both V51 tables columns and indexes', all(x in integration for x in ['analyticsV51Tables','analyticsV51CostColumns','analyticsV51SnapshotColumns','analyticsV51Indexes','cinema_concession_cost_basis','analytics_snapshot']))
check('V51 realistic seed covers both new tables and algorithm marker', 'seed51:cost-basis:' in seed and 'seed51:analytics-snapshot:' in seed and 'V51-WEEKDAY-WEIGHTED-MA-1' in seed and 'Quick verification of all 56 tables' in seed)
check('V51 56-table verifier is wired for 42 checks and both new tables', 'cinema_concession_cost_basis' in seed_verify and 'analytics_snapshot' in seed_verify and 'Seed V51 56-table realistic-data verification' in seed_verify)
check('CI and release workflows retain V50 gates and add V51 gates', all('verify_v50_recommendation_intelligence_2.py' in x and 'verify_v51_analytics_forecasting_3.py' in x and 'verify_seed_demo_56.py' in x for x in [ci,rc,release]))
check('V51 release gate remains present in V51-or-newer release defaults', ('v51.0.0-rc.1' in rc or 'v52.0.0-rc.1' in rc) and ('cinebooking_v51_rc_' in rc or 'cinebooking_v52_rc_' in rc) and ('default: "51.0.0"' in release or 'default: "52.0.0"' in release) and ('cinebooking_v51_release_' in release or 'cinebooking_v52_release_' in release))
check('Makefile diagnostics and README expose complete V51 lifecycle', all(x in make for x in ['verify-v51:','diagnose-v51:','seed-demo-v51:','verify-reference-v51:']) and 'verify_v51_analytics_forecasting_3.py' in diagnose and 'V51 - Analytics & Forecasting 3.0' in readme and 'V51__analytics_forecasting_3.sql' in readme)

passed=sum(ok for _,ok in checks)
print(f"\nV51 verification: {passed}/{len(checks)} checks passed")
raise SystemExit(0 if passed==len(checks) else 1)
