from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

hold=text('backend/src/main/java/com/cinebooking/seat/SeatHoldService.java')
service=text('backend/src/main/java/com/cinebooking/seat/SeatService.java')
engine=text('backend/src/main/java/com/cinebooking/seat/SeatRecommendationEngine.java')
dtos=text('backend/src/main/java/com/cinebooking/seat/SeatDtos.java')
controller=text('backend/src/main/java/com/cinebooking/seat/SeatController.java')
unit=text('backend/src/test/java/com/cinebooking/seat/SeatRecommendationEngineTest.java')
pricing=text('backend/src/main/java/com/cinebooking/pricing/PricingService.java')
page=text('frontend/app/booking/[showtimeId]/page.tsx')
types=text('frontend/lib/types.ts')
e2e=text('frontend/e2e/booking-seat-intelligence-v57.spec.ts')
v39e2e=text('frontend/e2e/seat-map-ux.spec.ts')
v39verify=text('tools/verify_v39_seat_map_ux.py')
v56verify=text('tools/verify_v56_customer_value_rfm.py')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v57.ps1')
readme=text('README.md')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
seed_verify=text('tools/verify_seed_demo_57.py')

check('V57 is a no-schema Booking & Seat Intelligence release', not any((ROOT/'backend/src/main/resources/db/migration').glob('V57__*.sql')))
check('V52 remains latest Flyway migration under V57', (ROOT/'backend/src/main/resources/db/migration/V52__pwa_mobile_experience_3.sql').exists() and 'assertThat(latest).isEqualTo("52")' in integration)
check('V57 keeps the 57-table data contract', 'Final verification enumerates all 57 pgAdmin tables' in seed_verify and 'pwa_device' in seed_verify)
check('V56 verifier is forward-compatible with V57 source namespace', 'Release compose project namespaces remain V56-or-newer' in v56verify and 'max(rc_namespaces)>=56' in v56verify)

check('Seat map exposes server clock and absolute hold expiry', all(x in dtos for x in ['serverEpochMs','holdExpiresAtEpochMs','SeatMapResponse']))
check('Hold response exposes server clock and absolute hold expiry', 'HoldResponse(boolean acquired, long ttlSeconds, long serverEpochMs' in dtos and 'holdExpiresAtEpochMs' in dtos)
check('V57 suggestion contract exposes dynamic price and score breakdown', all(x in dtos for x in ['dynamicAdjustment','centerScore','rowScore','orphanSafetyScore','qualityLabel']))
check('Seat controller preserves seat map suggestion validation and hold APIs', all(x in controller for x in ['@GetMapping("/seats")','@GetMapping("/seat-suggestions")','@PostMapping("/selection-validation")','@PostMapping("/holds")','@DeleteMapping("/holds")']))

check('Redis hold acquisition is atomic across every requested seat', "for i,key in ipairs(KEYS) do" in hold and "if owner and owner ~= ARGV[1] then return 0 end" in hold and hold.count("for i,key in ipairs(KEYS) do") >= 3)
check('Redis hold TTL is written atomically in milliseconds', "redis.call('set', key, ARGV[1], 'PX', ARGV[2])" in hold and 'Duration.ofSeconds(ttlSeconds).toMillis()' in hold)
check('Hold release only deletes keys owned by the same user', "if redis.call('get', key) == ARGV[1] then" in hold and "redis.call('del', key)" in hold)
check('V57 reads server-authoritative Redis PTTL in milliseconds', 'remainingMillis' in hold and 'TimeUnit.MILLISECONDS' in hold)
check('V57 keeps second-level compatibility alongside millisecond expiry', 'getExpire(redisKey, TimeUnit.SECONDS)' in hold and 'remainingMillis' in hold)

check('Seat map derives hold expiry from server time and Redis PTTL', all(x in service for x in ['long now = System.currentTimeMillis()','remainingMs = holds.remainingMillis','expiresAt = remainingMs <= 0 ? 0 : now + remainingMs']))
check('Successful hold returns a concrete server expiry epoch', 'remainingMs = holds.remainingMillis(showtimeId,unique,userId)' in service and 'new HoldResponse(true, holds.ttlSeconds(), now, expiresAt, unique)' in service)
check('Seat service enforces configured maximum group size', 'count > maxSelectableSeats' in service and 'unique.size() > maxSelectableSeats' in service)
check('Seat service rejects blocked and already reserved seats before hold', 'SeatType.BLOCKED' in service and 'findReservedSeatIds(showtimeId)' in service)
check('Seat service validates orphan-seat policy before atomic hold', 'SelectionValidationResponse validation = recommendations.validate(current,unique)' in service and service.index('recommendations.validate(current,unique)') < service.index('holds.acquire(showtimeId, unique, userId)'))
check('Seat map price comes from PricingService quote rather than fabricated UI math', 'PricingService.PricingContext pricingContext=pricing.contextFor(showtime)' in service and 'pricing.quote(pricingContext,s)' in service)
check('Seat map exposes real dynamic adjustment and applied pricing rule names', 'quote.dynamicAdjustment()' in service and 'quote.appliedRules().stream().map' in service)
check('Pricing engine keeps dynamic rule application deterministic', 'findByActiveTrueOrderByPriorityDescCreatedAtAsc' in pricing and 'finalPrice=before.add(dynamic)' in pricing)

check('V57 recommendation considers only contiguous AVAILABLE groups', 'isContiguousAvailable(group)' in engine and 'if (!"AVAILABLE".equals(s.status())) return false' in engine and 'b.seatNumber()==a.seatNumber()+1' in engine)
check('V57 recommendation protects against new single-seat orphan gaps', 'Set<String> before = orphanCodes' in engine and 'Set<String> after = orphanCodes' in engine and 'after.removeAll(before)' in engine)
check('V57 does not punish pre-existing single-seat gaps', 'never punish a customer for a pre-existing single gap' in engine and 'doesNotPunishPreExistingSingleGap' in unit)
check('V57 best-seat ranking includes transparent center and row scores', 'centerScore = clamp' in engine and 'rowScore = clamp' in engine)
check('V57 orphan-safe candidates receive explicit safety score', 'int orphanSafetyScore = 100' in engine)
check('V57 preserves accessible inventory in recommendation scoring', 'accessible*120' in engine and 'preserve accessible inventory' in engine)
check('V57 gives a small transparent VIP quality preference', 'vip*8' in engine)
check('V57 suggestion sums the exact dynamic adjustment of selected seats', 'map(SeatResponse::dynamicAdjustment).reduce(BigDecimal.ZERO, BigDecimal::add)' in engine)
check('V57 recommendation labels BEST GREAT GOOD deterministically', all(x in engine for x in ['"BEST"','"GREAT"','"GOOD"']) and 'score >= 975' in engine)
check('V57 suggestion reason names contiguous center and orphan safety', all(x in engine for x in ['V57 · Hàng','ghế liền nhau','gần trung tâm','không tạo ghế trống đơn']))
check('V57 recommendation sorts score descending with stable price/code tie breakers', 'Comparator.comparingInt(SeatSuggestion::score).reversed()' in engine and '.thenComparing(SeatSuggestion::totalPrice)' in engine)
check('Seat recommendation unit test asserts score breakdown and orphan safety', 'centerScore()' in unit and 'orphanSafetyScore()' in unit and 'qualityLabel()' in unit)

check('Frontend seat-map type exposes server clock and expiry', all(x in types for x in ['serverEpochMs:number','holdExpiresAtEpochMs:number']))
check('Frontend suggestion type exposes V57 ranking and dynamic price fields', all(x in types for x in ['dynamicAdjustment:number','centerScore:number','rowScore:number','orphanSafetyScore:number','qualityLabel']))
check('Booking page carries V57 roadmap marker', 'BOOKING & SEAT INTELLIGENCE · V57' in page and 'booking-seat-intelligence-v57' in page)
check('Booking page supports group-size best-seat suggestions', 'Số người cần xếp ghế' in page and '/seat-suggestions?count=${partySize}' in page and 'Ghế đẹp nhất cho cả nhóm' in page)
check('Booking page displays transparent recommendation score', 'suggestion.score' in page and 'suggestion.centerScore' in page)
check('Booking page displays orphan-seat safety score', 'suggestion.orphanSafetyScore' in page and 'Không ghế lẻ' in page)
check('Booking page describes and displays real dynamic pricing', 'Giá động thật được hiển thị trước khi giữ ghế' in page and 'suggestion.dynamicAdjustment' in page and 'pricingRules' in page)
check('Booking page synchronizes client clock against server epoch', 'setServerClockOffset' in page and '(m.serverEpochMs||Date.now())-Date.now()' in page)
check('Booking page drives realtime countdown from absolute server expiry', 'holdExpiresAt-(Date.now()+serverClockOffset)' in page and 'setInterval(tick,250)' in page)
check('Booking page resynchronizes active holds with Redis-backed map', 'setInterval(()=>load().catch(()=>{}),15000)' in page)
check('Booking page still subscribes to realtime seat-map WebSocket events', '/topic/showtimes/${showtimeId}/seats' in page and 'Seat map updated live' in page)
check('Booking page exposes V57 countdown test hook', 'seat-hold-countdown-v57' in page and 'Đếm ngược giữ ghế realtime đồng bộ máy chủ' in page)
check('Booking page consumes server hold expiry from hold response', 'holdExpiresAtEpochMs:number' in page and 'setHoldExpiresAt(r.holdExpiresAtEpochMs' in page)
check('Booking page clears expiry when release/cancel/checkout ends hold', page.count('setHoldExpiresAt(0)') >= 4)

check('V57 Playwright journey exists with roadmap title', 'V57 Booking & Seat Intelligence ranks best adjacent seats' in e2e)
check('V57 Playwright validates recommendation score breakdown', all(x in e2e for x in ['centerScore','rowScore','orphanSafetyScore','qualityLabel','dynamicAdjustment']))
check('V57 Playwright validates realtime absolute hold expiry', 'holdExpiresAtEpochMs' in e2e and 'serverEpochMs' in e2e and 'seat-hold-countdown-v57' in e2e)
check('V57 Playwright validates a second client receives 409 contention', 'secondContext' in e2e and 'expect(secondHold.status).toBe(409)' in e2e)
check('V57 Playwright verifies losing client sees seats HELD', 'toHaveAttribute("title", /HELD/)' in e2e)
check('Existing V39 atomic race journey remains present', 'V39 smart seat suggestion and atomic contention guard' in v39e2e)
check('Existing V39 verifier still covers orphan and atomic hold semantics', 'Recommendation engine avoids new single-seat gaps' in v39verify and 'Atomic Redis multi-seat acquire remains intact' in v39verify)

ci_match=re.search(r'name:\s*V26-V(\d+) source regression',ci)
check('Main CI extends source regression through V57', bool(ci_match) and int(ci_match.group(1))>=57)
check('Main CI runs V57 Booking & Seat Intelligence gate', 'verify_v57_booking_seat_intelligence.py' in ci and 'Verify V57 Booking & Seat Intelligence 3.0' in ci)
rc_versions=[int(v) for v in re.findall(r'default: "v(\d+)\.0\.0-rc\.1"',rc)]
check('Standalone RC defaults to V57-or-newer', bool(rc_versions) and max(rc_versions)>=57)
check('Standalone RC uses a V57-or-newer compose namespace', any(int(v)>=57 for v in re.findall(r'cinebooking_v(\d+)_rc_',rc)))
check('Standalone RC runs the V57 source gate', 'Verify V57 source gate' in rc and 'verify_v57_booking_seat_intelligence.py' in rc)
check('Standalone RC browser gate names V57 journey coverage', '+ V56 + V57)' in rc)
release_versions=[int(v) for v in re.findall(r'default: "(\d+)\.0\.0"',release)]
check('Stable release defaults to V57-or-newer', bool(release_versions) and max(release_versions)>=57)
check('Stable release uses a V57-or-newer compose namespace', any(int(v)>=57 for v in re.findall(r'cinebooking_v(\d+)_release_',release)))
check('Stable release runs V57 source gate before RC E2E', 'Verify V57 source gate' in release and 'verify_v57_booking_seat_intelligence.py' in release)
check('Makefile exposes V57 verify diagnose and unchanged 57-table lifecycle', all(x in make for x in ['verify-v57:','diagnose-v57:','verify-seed-demo-v57:','check-seed-demo-v57:','verify-reference-v57:','seed-reference-v57:']))
check('V57 diagnostics chain V39 V56 V57 and 57-table verifier', all(x in diagnose for x in ['verify_v39_seat_map_ux.py','verify_v56_customer_value_rfm.py','verify_v57_booking_seat_intelligence.py','verify_seed_demo_57.py','V57 source diagnostics passed.']))

current_match=re.search(r'^# CineBooking Pro V(\d+)',readme,re.M)
check('README identifies current V57 Booking & Seat Intelligence release', bool(current_match) and int(current_match.group(1))>=57 and 'V57 - Booking & Seat Intelligence 3.0' in readme)
check('README version history includes the roadmap-correct V57 row', '**V57**' in readme and 'best-seat ranking, contiguous groups, orphan-seat guard' in readme)
check('README documents all six requested V57 roadmap capabilities', all(x in readme for x in ['Ghế đẹp nhất','Nhóm ghế liền nhau','Tránh ghế trống đơn','Seat hold countdown realtime','Chống tranh ghế nhiều client','Dynamic seat pricing']))
check('README states V57 is no-schema and keeps 57 public tables', 'V57 không tạo migration Flyway mới' in readme and '57 public tables' in readme)
check('README release lifecycle defaults to V57 RC1 and stable', 'v57.0.0-rc.1' in readme and 'v57.0.0' in readme)

passed=sum(ok for _,ok in checks)
print(f"\nV57 verification: {passed}/{len(checks)} checks passed")
raise SystemExit(0 if passed==len(checks) else 1)
