from pathlib import Path
import sys,re
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

migration=text('backend/src/main/resources/db/migration/V48__multi_cinema_concession_inventory_2.sql')
inv_entity=text('backend/src/main/java/com/cinebooking/domain/CinemaConcessionInventory.java')
price_entity=text('backend/src/main/java/com/cinebooking/domain/CinemaConcessionPrice.java')
movement=text('backend/src/main/java/com/cinebooking/domain/InventoryMovement.java')
inv_repo=text('backend/src/main/java/com/cinebooking/commerce/CinemaConcessionInventoryRepository.java')
price_repo=text('backend/src/main/java/com/cinebooking/commerce/CinemaConcessionPriceRepository.java')
movement_repo=text('backend/src/main/java/com/cinebooking/commerce/InventoryMovementRepository.java')
service=text('backend/src/main/java/com/cinebooking/commerce/InventoryService.java')
commerce=text('backend/src/main/java/com/cinebooking/commerce/CommerceService.java')
controller=text('backend/src/main/java/com/cinebooking/commerce/AdminInventoryController.java')
public_controller=text('backend/src/main/java/com/cinebooking/commerce/CommerceController.java')
dtos=text('backend/src/main/java/com/cinebooking/commerce/InventoryDtos.java')
commerce_dtos=text('backend/src/main/java/com/cinebooking/commerce/CommerceDtos.java')
booking=text('backend/src/main/java/com/cinebooking/booking/BookingService.java')
admin_catalog=text('backend/src/main/java/com/cinebooking/movie/AdminCatalogService.java')
booking_ui=text('frontend/app/booking/[showtimeId]/page.tsx')
admin_ui=text('frontend/app/admin/inventory/page.tsx')
types=text('frontend/lib/types.ts')
e2e=text('frontend/e2e/inventory-operations-v48.spec.ts')
seed=text('tools/seed-demo-52-tables-10-rows.sql')
seed_verify=text('tools/verify_seed_demo_52.py')
ci=text('.github/workflows/ci.yml');rc=text('.github/workflows/release-candidate.yml');release=text('.github/workflows/release.yml')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
make=text('Makefile');readme=text('README.md')

check('V48 migration creates branch inventory table', 'CREATE TABLE cinema_concession_inventory' in migration and 'uq_branch_concession_inventory' in migration)
check('V48 branch inventory has stock reserved threshold target and active state', all(x in migration for x in ['stock_on_hand','stock_reserved','low_stock_threshold','target_stock','active BOOLEAN']))
check('V48 migration creates branch price table', 'CREATE TABLE cinema_concession_price' in migration and 'uq_branch_concession_price' in migration)
check('V48 migration adds cinema and reference key to movement ledger', 'ADD COLUMN cinema_id' in migration and 'ADD COLUMN reference_key' in migration)
check('V48 movement constraint allows waste and transfers', all(x in migration for x in ["'WASTE'","'TRANSFER_OUT'","'TRANSFER_IN'","'LOYALTY_REWARD'"]))
check('V48 migration backfills branch inventory and pricing', 'CROSS JOIN concession_product' in migration and 'v48:branch-inventory:' in migration and 'v48:branch-price:' in migration)
check('V48 migration backfills historical booking movement cinema', 'UPDATE inventory_movement im' in migration and 'JOIN auditorium a' in migration)
check('Branch inventory entity maps V48 table', '@Table(name="cinema_concession_inventory"' in inv_entity and all(x in inv_entity for x in ['cinemaId','productId','stockOnHand','stockReserved','targetStock']))
check('Branch price entity maps V48 table', '@Table(name="cinema_concession_price"' in price_entity and all(x in price_entity for x in ['cinemaId','productId','price','active']))
check('Movement entity maps branch and reference metadata', 'private UUID cinemaId' in movement and 'private String referenceKey' in movement)
check('Branch inventory repository exposes pessimistic checkout locks', 'PESSIMISTIC_WRITE' in inv_repo and 'findForUpdate' in inv_repo and 'findTransferRowsForUpdate' in inv_repo)
check('Branch price repository exposes branch product lookup', 'findByCinemaIdAndProductId' in price_repo)
check('Movement repository exposes branch-scoped history', 'findTop200ByCinemaIdOrderByCreatedAtDesc' in movement_repo and 'findTop200ByCinemaIdAndProductIdOrderByCreatedAtDesc' in movement_repo)
check('Inventory service exposes branch dashboard', 'List<InventoryBranchOverview> branches()' in service and 'InventorySummary summary(UUID cinemaId)' in service)
check('Inventory service supports RESTOCK SET and WASTE', all(x in service for x in ['"RESTOCK"','"SET"','"WASTE"','Không thể ghi hao hụt vượt số lượng khả dụng']))
check('Inventory service supports atomic branch transfer', 'InventoryTransferResponse transfer' in service and 'findTransferRowsForUpdate' in service and 'TRANSFER_OUT' in service and 'TRANSFER_IN' in service)
check('Inventory transfer never consumes reserved booking stock', 'available(from)<req.quantity()' in service and 'stockReserved' in inv_entity)
check('Inventory service supports branch price override', 'BranchPriceResponse setPrice' in service and 'branchPrices.save' in service)
check('Booking inventory reservation is cinema scoped', 'reserveForBooking(UUID bookingId,UUID cinemaId' in service and 'lock(cinemaId,qty.keySet())' in service)
check('Sale release and refund resolve booking cinema', 'cinemaForBooking(bookingId)' in service and 'mutateBookingInventory' in service)
check('Loyalty reward consumes staff branch inventory', 'staffProfiles.findById(staff.getId())' in service and '"LOYALTY_REWARD"' in service)
check('Admin inventory API exposes branches transfer and prices', all(x in controller for x in ['/branches','/transfers','/prices','@RequestParam UUID cinemaId']))
check('Public product API accepts cinemaId', '@RequestParam(required=false) UUID cinemaId' in public_controller and 'publicProducts(cinemaId)' in public_controller)
check('Commerce catalog returns branch inventory and effective price', 'productDto(p,cinema' in commerce and 'CinemaConcessionPrice::getPrice' in commerce and 'CinemaConcessionInventory' in commerce)
check('New products get branch inventory and price rows', 'for(Cinema c:cinemas.findAllByOrderByNameAsc())' in commerce and 'branchInventory.save(bi)' in commerce and 'branchPrices.save(bp)' in commerce)
check('New cinemas provision existing concession inventory and prices', 'provisionCinema(UUID cinemaId)' in service and 'for(ConcessionProduct product:products.findAllByOrderBySortOrderAscNameAsc())' in service and 'branchInventory.save(inventory)' in service and 'branchPrices.save(price)' in service)
check('Cinema creation flushes branch before inventory provisioning', 'cinemas.saveAndFlush(c)' in admin_catalog and 'inventory.provisionCinema(saved.getId())' in admin_catalog)
check('V48 product save avoids reassigned-local lambda capture', 'final ConcessionProduct savedProduct=products.save(product);' in commerce and 'p=products.save(p)' not in commerce and 'savedProduct.getId()' in commerce)
check('Booking concessions use branch-specific price', 'buildConcessions(UUID bookingId,UUID cinemaId' in commerce and 'bc.setUnitPrice(unit)' in commerce)
check('Booking service resolves showtime cinema before concession build', 'auditoriums.findById(showtime.getAuditoriumId())' in booking and 'commerce.buildConcessions(b.getId(),cinemaId' in booking)
check('Booking service reserves inventory at same cinema', 'inventory.reserveForBooking(b.getId(),cinemaId,concessionRows)' in booking)
check('V48 DTOs expose target stock transfers prices and branch movement', all(x in dtos for x in ['targetStock','InventoryTransferRequest','BranchPriceRequest','referenceKey','cinemaName']))
check('Commerce DTO adds branch identity and base price metadata', all(x in commerce_dtos for x in ['cinemaId','cinemaName','basePrice','priceOverride']))
check('Booking UI requests concession catalog for showtime cinema', '/commerce/products?cinemaId=' in booking_ui and 's.cinemaId' in booking_ui and 'CINE FOOD · V48' in booking_ui)
check('Admin UI identifies V48 branch inventory operations', 'INVENTORY · V48' in admin_ui and 'Kho bắp nước theo rạp' in admin_ui)
check('Admin UI exposes branch selector stock warning and filters', 'inventory-cinema-select' in admin_ui and 'Sắp hết' in admin_ui and 'Hết hàng' in admin_ui)
check('Admin UI exposes restock set waste', all(x in admin_ui for x in ['+ Nhập','Kiểm kê','Hao hụt','Ghi sổ kho']))
check('Admin UI exposes branch price override and transfer', 'Giá theo rạp' in admin_ui and 'branch-price-save' in admin_ui and 'Điều chuyển giữa rạp' in admin_ui and 'inventory-transfer-button' in admin_ui)
check('Frontend types expose V48 branch inventory contracts', all(x in types for x in ['InventoryBranchOverview','InventoryTransfer','targetStock','TRANSFER_OUT','priceOverride']))
check('Dedicated V48 E2E covers restock waste branch price and transfer', all(x in e2e for x in ['V48 admin manages branch stock price waste and transfer','Số lượng hao hụt','Đã ghi nhận hao hụt','WASTE','branch-price-save','inventory-transfer-button','TRANSFER_OUT']))
check('V48 E2E creates a real second branch before transfer', all(x in e2e for x in ['/api/admin/cinemas','createCinema.status()).toBe(201)','AUTH_STORAGE_KEY','CineHub V48 Transfer']))
check('V48 seed covers 52 tables with branch stock and price', 'cinema_concession_inventory' in seed and 'cinema_concession_price' in seed and 'Quick verification of all 52 tables' in seed)
check('V48 seed keeps payment reference data MOCK only', "provider='MOCK'" in seed and 'seeded VNPAY/MOMO rows remain' in seed)
check('V48 52-table verifier passes realistic-data contract', 'Seed V48 52-table realistic-data verification' in seed_verify and 'All 50 seeded application tables' in seed_verify)
check('Integration test retains V48 schema coverage on V48-or-newer Flyway', ('isEqualTo("48")' in integration or 'isEqualTo("49")' in integration or 'isEqualTo("50")' in integration) and ('isGreaterThanOrEqualTo(52)' in integration or 'isGreaterThanOrEqualTo(53)' in integration or 'isGreaterThanOrEqualTo(54)' in integration) and 'inventoryV48Tables' in integration)
check('Main CI retains V48 source and 52-table gates in current regression', ('V26-V48 source regression' in ci or 'V26-V49 source regression' in ci or 'V26-V50 source regression' in ci) and 'verify_v48_concession_inventory_2.py' in ci and 'verify_seed_demo_52.py' in ci)
check('Standalone RC retains V48 gate in V48-or-newer candidate', ('v48.0.0-rc.1' in rc or 'v49.0.0-rc.1' in rc or 'v50.0.0-rc.1' in rc) and ('Verify V48 source gate' in rc or 'Verify V49 source gate' in rc or 'Verify V50 source gate' in rc) and 'verify_v48_concession_inventory_2.py' in rc)
check('Stable release retains V48 gate in V48-or-newer project', (('default: "48.0.0"' in release and 'cinebooking_v48_release_' in release) or ('default: "49.0.0"' in release and 'cinebooking_v49_release_' in release) or ('default: "50.0.0"' in release and 'cinebooking_v50_release_' in release)) and 'verify_v48_concession_inventory_2.py' in release)
check('Makefile exposes V48 verify diagnose seed and reference targets', all(x in make for x in ['verify-v48:','diagnose-v48:','seed-demo-v48:','verify-reference-v48:','seed-reference-v48:']))
check('README preserves V48 Concession & Inventory 2.0 history', 'V48 - Concession & Inventory 2.0' in readme and 'v48.0.0-rc.1' in readme and 'V48__multi_cinema_concession_inventory_2.sql' in readme)

passed=sum(v for _,v in checks);total=len(checks)
print(f"\nV48 verification: {passed}/{total} checks passed")
if passed!=total:
    print('Failed checks:')
    for n,v in checks:
        if not v: print(' -',n)
sys.exit(0 if passed==total else 1)
