from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(path): return (ROOT/path).read_text(encoding="utf-8")
def check(name,cond): checks.append((name,bool(cond)))

mig=text("backend/src/main/resources/db/migration/V43__staff_operations_2.sql")
svc=text("backend/src/main/java/com/cinebooking/staffops/StaffOperationsService.java")
ctl=text("backend/src/main/java/com/cinebooking/staffops/StaffOperationsController.java")
dtos=text("backend/src/main/java/com/cinebooking/staffops/StaffOpsDtos.java")
checkin=text("backend/src/main/java/com/cinebooking/operations/CheckInService.java")
logrepo=text("backend/src/main/java/com/cinebooking/operations/TicketCheckInLogRepository.java")
attrepo=text("backend/src/main/java/com/cinebooking/staffops/StaffAttendanceRepository.java")
pub=text("backend/src/main/java/com/cinebooking/websocket/StaffOperationsEventPublisher.java")
sub=text("backend/src/main/java/com/cinebooking/websocket/RedisStaffOperationsEventSubscriber.java")
redis=text("backend/src/main/java/com/cinebooking/config/RedisPubSubConfig.java")
ui=text("frontend/app/staff/operations/page.tsx")
gateui=text("frontend/app/staff/check-in/page.tsx")
types=text("frontend/lib/types.ts")
header=text("frontend/components/Header.tsx")
e2e=text("frontend/e2e/staff-operations.spec.ts")
readme=text("README.md")
ci=text(".github/workflows/ci.yml")
rc=text(".github/workflows/release-candidate.yml")
release=text(".github/workflows/release.yml")
make=text("Makefile")
diag=text("tools/diagnose-v43.ps1")
integration=text("backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java")

check("V43 migration creates shift handover table", all(x in mig for x in ["staff_shift_handover","uq_staff_handover_pending_attendance","PENDING","ACCEPTED"]))
check("V43 migration creates incident table and indexes", all(x in mig for x in ["staff_incident","idx_staff_incident_cinema_status_created","CRITICAL","RESOLVED"]))
check("Handover entity exists", (ROOT/"backend/src/main/java/com/cinebooking/domain/StaffShiftHandover.java").exists())
check("Incident entity exists", (ROOT/"backend/src/main/java/com/cinebooking/domain/StaffIncident.java").exists())
check("Operations DTOs expose live, handover and incident contracts", all(x in dtos for x in ["OperationsLiveSnapshot","HandoverCreateRequest","IncidentCreateRequest","IncidentResolveRequest"]))
check("Staff operations controller exposes live dashboard", '/live' in ctl and 'OperationsLiveSnapshot' in ctl)
check("Staff operations controller exposes handover lifecycle", all(x in ctl for x in ['/handovers','/handovers/{id}/accept','createHandover','acceptHandover']))
check("Staff operations controller exposes incident lifecycle", all(x in ctl for x in ['/incidents','/incidents/{id}/resolve','createIncident','resolveIncident']))
check("Operations service requires active attendance for handover", 'activeAttendance(from)' in svc and 'Bạn phải bắt đầu ca' in svc)
check("Handover is restricted to active same-cinema staff", 'Chỉ có thể bàn giao cho nhân viên đang hoạt động cùng rạp' in svc)
check("Incident resolution is Manager/Admin only", 'Role.MANAGER' in svc and 'Role.ADMIN' in svc and 'Chỉ Manager/Admin được đóng sự cố' in svc)
check("Live dashboard counts 5m/hour/today check-ins", all(x in svc for x in ['Duration.ofMinutes(5)','Duration.ofHours(1)','LocalDate.now(zone).atStartOfDay(zone)','countByCinemaIdAndCheckedInAtBetween']))
check("Ticket log repository supports cinema live metrics", all(x in logrepo for x in ['findTop20ByCinemaIdOrderByCheckedInAtDesc','countByCinemaIdAndCheckedInAtBetween']))
check("Attendance repository supports active-staff metric", 'countByCinemaIdAndCheckOutAtIsNull' in attrepo)
check("Check-in emits cross-replica operations event", 'StaffOperationsEventPublisher' in checkin and 'TICKET_CHECKED_IN' in checkin)
check("Redis publisher uses dedicated staff operations channel", 'cinebooking:staff-operations-events' in pub)
check("Redis subscriber broadcasts cinema-scoped WebSocket topic", '/topic/staff-operations/' in sub)
check("Redis config registers staff operations subscriber", 'StaffOperationsEventPublisher.CHANNEL' in redis and 'RedisStaffOperationsEventSubscriber' in redis)
check("V43 frontend has realtime operations page", all(x in ui for x in ['STAFF OPERATIONS 2.0 · V43','Trung tâm vận hành rạp realtime','@stomp/stompjs','/topic/staff-operations/']))
check("V43 frontend polls as WebSocket fallback", '15000' in ui and 'setInterval' in ui)
check("V43 frontend supports handover create/accept", all(x in ui for x in ['Tạo bàn giao','Nhận bàn giao','/staff/operations/handovers']))
check("V43 frontend supports incident create/resolve", all(x in ui for x in ['Ghi nhận sự cố','Đóng sự cố','/staff/operations/incidents']))
check("Frontend types include V43 contracts", all(x in types for x in ['StaffOperationsLive','StaffHandover','StaffIncident']))
check("Header links to realtime operations", '/staff/operations' in header and 'Vận hành realtime' in header)
check("Gate scanner adds local duplicate debounce", all(x in gateui for x in ['processingRef','lastScanRef','2500']))
check("Gate scanner still uses rear mobile camera", 'facingMode:{ideal:"environment"}' in gateui and 'width:{ideal:1280}' in gateui)
check("V43 Playwright covers incident create and resolve", all(x in e2e for x in ['V43 admin sees realtime staff operations','Ghi nhận sự cố','Đóng sự cố','RESOLVED']))
check("README retains V43 release history", '### V43 - Staff Operations 2.0' in readme and 'V43__staff_operations_2.sql' in readme)
check("README version history maps V43 migration", 'V43__staff_operations_2.sql' in readme)
check("Integration test retains V43 staff schema assertions", 'staffV43Tables' in integration and 'staffV43Indexes' in integration)
check("Integration test validates V43 staff tables and indexes", 'staffV43Tables' in integration and 'staffV43Indexes' in integration and 'staff_shift_handover' in integration and 'staff_incident' in integration)
check("Main CI retains V43 source gate", 'python3 tools/verify_v43_staff_operations.py' in ci and 'source regression' in ci)
check("Standalone RC retains V43 regression gate", 'python3 tools/verify_v43_staff_operations.py' in rc)
check("Stable release retains V43 regression gate", 'python3 tools/verify_v43_staff_operations.py' in release)
check("Stable release still publishes immutable GitHub Release", all(x in release for x in ['Create immutable RC tag','Publish stable tag and GitHub Release','gh release create "$STABLE_TAG"']))
check("Makefile exposes V43 verify/diagnose", 'verify-v43:' in make and 'diagnose-v43:' in make)
check("V43 diagnostics chains V42.1 and V43", 'verify_v42_1_analytics_export.py' in diag and 'verify_v43_staff_operations.py' in diag and 'v43.0.0-rc.N' in diag)

for name,ok in checks: print(f"[{' OK ' if ok else 'FAIL'}] {name}")
passed=sum(ok for _,ok in checks);total=len(checks)
print(f"\nV43 verification: {passed}/{total} checks passed")
if passed!=total:
    print("Failed checks:")
    for name,ok in checks:
        if not ok: print(" -",name)
    sys.exit(1)
