from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
checks = []


def text(rel: str) -> str:
    p = ROOT / rel
    return p.read_text(encoding="utf-8") if p.exists() else ""


def exists(rel: str) -> bool:
    return (ROOT / rel).exists()


def check(name: str, condition) -> None:
    ok = bool(condition)
    checks.append((name, ok))
    print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

migration = text("backend/src/main/resources/db/migration/V66__durable_seat_holds.sql")
entity = text("backend/src/main/java/com/cinebooking/domain/SeatHoldRecord.java")
repo = text("backend/src/main/java/com/cinebooking/seat/SeatHoldRepository.java")
seat_repo = text("backend/src/main/java/com/cinebooking/seat/SeatRepository.java")
holds = text("backend/src/main/java/com/cinebooking/seat/SeatHoldService.java")
audit_writer = text("backend/src/main/java/com/cinebooking/seat/SeatHoldAuditWriter.java")
expiry_job = text("backend/src/main/java/com/cinebooking/seat/SeatHoldExpiryJob.java")
ops_dtos = text("backend/src/main/java/com/cinebooking/seat/SeatOperationsDtos.java")
ops_service = text("backend/src/main/java/com/cinebooking/seat/AdminSeatOperationsService.java")
ops_controller = text("backend/src/main/java/com/cinebooking/seat/AdminSeatOperationsController.java")
seat_service = text("backend/src/main/java/com/cinebooking/seat/SeatService.java")
seat_dtos = text("backend/src/main/java/com/cinebooking/seat/SeatDtos.java")
booking_service = text("backend/src/main/java/com/cinebooking/booking/BookingService.java")
booking_controller = text("backend/src/main/java/com/cinebooking/booking/BookingController.java")
booking_seat_repo = text("backend/src/main/java/com/cinebooking/booking/BookingSeatRepository.java")
audit = text("backend/src/main/java/com/cinebooking/audit/AuditService.java")
events = text("backend/src/main/java/com/cinebooking/websocket/SeatEventPublisher.java")
security = text("backend/src/main/java/com/cinebooking/config/SecurityConfig.java")
app_yml = text("backend/src/main/resources/application.yml")
compose = text("docker-compose.yml")
env_example = text(".env.example")
itest = text("backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java")
frontend_types = text("frontend/lib/types.ts")
admin = text("frontend/app/admin/page.tsx")
ops_ui = text("frontend/app/admin/seat-operations/page.tsx")
booking_ui = text("frontend/app/booking/[showtimeId]/page.tsx")
e2e = text("frontend/e2e/booking-consistency-seat-locking-v66.spec.ts")
ci = text(".github/workflows/ci.yml")
rc = text(".github/workflows/release-candidate.yml")
release = text(".github/workflows/release.yml")
make = text("Makefile")
diagnose = text("tools/diagnose-v66.ps1")
readme = text("README.md")
v65verify = text("tools/verify_v65_observability_reliability.py")
https_verify = text("tools/verify_v65_local_https.py")
manual_checkin_verify = text("tools/verify_v65_manual_checkin_hotfix.py")
seed_sql = text("tools/seed-demo-57-tables-10-rows.sql")

# Files / release identity
check("V66 durable hold migration exists", bool(migration))
check("V66 seat hold entity exists", bool(entity))
check("V66 seat hold repository exists", bool(repo))
check("V66 expiry job exists", bool(expiry_job))
check("V66 admin operations DTOs exist", bool(ops_dtos))
check("V66 admin operations service exists", bool(ops_service))
check("V66 admin operations controller exists", bool(ops_controller))
check("V66 admin operations UI exists", bool(ops_ui))
check("V66 browser E2E exists", bool(e2e))
check("V66 diagnose script exists", bool(diagnose))
check("README current release is V66 or later", "Current release: **V66**" in readme or "Current release:** V66" in readme or "Current release:** V67" in readme)
check("README contains V66 section", "## V66 - Booking Consistency & Seat Locking 4.0" in readme)
check("V66 strategy version is explicit", "V66-BOOKING-CONSISTENCY-4" in ops_service and "V66-BOOKING-CONSISTENCY-4" in readme)

# Migration / durable invariant
check("seat_hold table is created", "CREATE TABLE IF NOT EXISTS seat_hold" in migration)
for col in ["showtime_id UUID NOT NULL", "seat_id UUID NOT NULL", "user_id UUID NOT NULL", "hold_token UUID NOT NULL", "expires_at TIMESTAMPTZ NOT NULL", "converted_booking_id UUID", "last_event VARCHAR(48)", "version BIGINT"]:
    check(f"seat_hold schema includes {col.split()[0]}", col in migration)
check("seat_hold showtime FK exists", "REFERENCES showtime(id)" in migration)
check("seat_hold seat FK exists", "REFERENCES seat(id)" in migration)
check("seat_hold user FK exists", "REFERENCES app_user(id)" in migration)
check("seat_hold converted booking FK exists", "REFERENCES booking(id)" in migration)
check("seat_hold state constraint exists", "ck_seat_hold_state" in migration)
for state in ["'HELD'", "'RELEASED'", "'EXPIRED'", "'CONVERTED'"]:
    check(f"seat_hold state allows {state}", state in migration)
check("seat_hold expiry constraint exists", "ck_seat_hold_expiry" in migration and "expires_at > created_at" in migration)
check("active seat hold has partial unique index", "CREATE UNIQUE INDEX IF NOT EXISTS uq_seat_hold_active" in migration and "WHERE state='HELD'" in migration)
for idx in ["idx_seat_hold_active_showtime", "idx_seat_hold_active_user", "idx_seat_hold_token", "idx_seat_hold_expiry_scan", "idx_seat_hold_recent"]:
    check(f"seat_hold index {idx} exists", idx in migration)
check("migration documents PostgreSQL authority", "durable authority" in migration.lower())
check("migration documents Redis mirror only", "redis remains a ttl mirror" in migration.lower())

# Entity / optimistic version
check("SeatHoldRecord maps seat_hold", '@Table(name="seat_hold")' in entity)
check("SeatHoldRecord uses UUID primary key", "@Id private UUID id" in entity)
check("SeatHoldRecord maps hold token", '@Column(name="hold_token",nullable=false)' in entity)
check("SeatHoldRecord maps expiry", '@Column(name="expires_at",nullable=false)' in entity)
check("SeatHoldRecord maps converted booking", '@Column(name="converted_booking_id")' in entity)
check("SeatHoldRecord has JPA version", "@Version" in entity)
check("SeatHoldRecord defaults state HELD", 'if(state==null)state="HELD"' in entity)
check("SeatHoldRecord defaults lifecycle event", 'SEAT_HOLD_CREATED' in entity)

# Cross-replica serialization
check("SeatRepository imports pessimistic lock", "LockModeType.PESSIMISTIC_WRITE" in seat_repo)
check("SeatRepository exposes deterministic FOR UPDATE equivalent", "findByIdInForUpdate" in seat_repo)
check("Seat lock query orders by UUID", "order by s.id" in seat_repo)
check("SeatHoldService normalizes and sorts seat IDs", ".distinct().sorted().toList()" in holds)
check("SeatHoldService locks requested seat rows", "lockSeatRows(ids);" in holds)
check("SeatHoldService validates all locked seats exist", "findByIdInForUpdate(ids).size()!=ids.size()" in holds)
check("Acquire expires stale holds under seat lock", "repository.expireRequested(showtimeId,ids,now)" in holds)
check("Acquire rechecks durable booking-seat reservations after lock", "bookingSeats.findReservedSeatIds(showtimeId)" in holds)
check("Acquire rejects already booked seat", "Có ghế đã được đặt bởi giao dịch khác" in holds)
check("Acquire reads active holds from PostgreSQL", "repository.findActiveForSeats(showtimeId,ids,now)" in holds)
check("Acquire rejects foreign durable owner", "Có ghế đang được người khác giữ" in holds)
check("Acquire writes durable hold rows before Redis", "repository.save(row)" in holds and "repository.flush()" in holds)
check("Acquire translates unique-index race to HTTP conflict", "catch(DataIntegrityViolationException ex)" in holds and "HttpStatus.CONFLICT" in holds)
check("Acquire names DB invariant in audit", "uq_seat_hold_active" in holds)
check("Hold authority is PostgreSQL with Redis mirror", 'AUTHORITY = "POSTGRESQL_WITH_REDIS_MIRROR"' in holds)
check("TTL is bounded 30-1800 seconds", "ttlSeconds<30 || ttlSeconds>1800" in holds)

# Redis is not authority
check("Redis writes happen through mirror function", "private boolean mirrorOne" in holds)
check("Redis mirror happens after commit on acquire", "afterCommit(()->{" in holds and "mirror(showtimeId,saved)" in holds)
check("Redis mirror stores bounded TTL", "TimeUnit.MILLISECONDS" in holds)
check("Redis value contains user and hold token", 'return row.getUserId()+"|"+row.getHoldToken()' in holds)
check("Redis write failure is swallowed and measured", "catch(Exception ex){redisFailureCounter.increment();return false;}" in holds)
check("Redis delete failure is swallowed and measured", "catch(Exception ex){redisFailureCounter.increment();}" in holds)
check("Redis health uses PING", "connection.ping()" in holds)
check("Redis connection uses try-with-resources", "try(org.springframework.data.redis.connection.RedisConnection connection" in holds)
check("Redis outage cannot replace durable ownership read", "opsForValue().get" not in holds)
check("Holder lookup comes from seat_hold repository", "List<SeatHoldRecord> active=repository.findActiveForSeats" in holds)
check("Read path does not transition expiry", "Read paths never transition state" in holds)
check("Reconcile can rebuild Redis from all active DB rows", "repository.findAllActive(now)" in holds and "mirrorOne(row.getShowtimeId(),row)" in holds)

# Lifecycle / audit / metrics
for metric in ["cinebooking.seat.hold.created", "cinebooking.seat.hold.refreshed", "cinebooking.seat.hold.conflicts", "cinebooking.seat.hold.released", "cinebooking.seat.hold.expired", "cinebooking.seat.hold.converted", "cinebooking.seat.hold.redis.failures"]:
    check(f"Metric {metric} exists", metric in holds)
for event in ["SEAT_HOLD_CREATED", "SEAT_HOLD_REFRESHED", "SEAT_HOLD_CONFLICT", "SEAT_HOLD_RELEASED", "SEAT_HOLD_EXPIRED", "SEAT_HOLD_CONVERTED"]:
    check(f"Lifecycle event {event} exists", event in holds or event in entity)
check("Seat-hold audit is REQUIRES_NEW", "Propagation.REQUIRES_NEW" in audit_writer)
check("Seat-hold audit uses SEAT_HOLD entity", '"SEAT_HOLD"' in audit_writer)
check("Audit signal stream includes seat hold events", 'action.startsWith("SEAT_HOLD_")' in audit)
check("Release transitions durable state", 'row.setState("RELEASED")' in holds)
check("Release records release timestamp", "row.setReleasedAt(now)" in holds)
check("Release clears Redis only after commit", "clearMirror(showtimeId,mine.stream()" in holds)
check("Convert transitions durable state", 'row.setState("CONVERTED")' in holds)
check("Convert links exact booking ID", "row.setConvertedBookingId(bookingId)" in holds)
check("Convert records converted event", 'row.setLastEvent("SEAT_HOLD_CONVERTED")' in holds)
check("Convert clears mirror after commit", "clearMirror(showtimeId,ids)" in holds)
check("Expiry transitions state conditionally", "repository.expireOne(row.getId(),now)==1" in holds)
check("Expiry native update leaves JPA @Version for managed flush", "WHERE id=:id AND state='HELD' AND expires_at<=:now" in repo and "UPDATE seat_hold SET state='EXPIRED',released_at=:now,last_event='SEAT_HOLD_EXPIRED'\n        WHERE id=:id" in repo)
check("Expiry records system audit", 'safeAuditSystem("SEAT_HOLD_EXPIRED"' in holds)

# Expiry scheduler
check("Expiry job is Spring component", "@Component" in expiry_job)
check("Expiry scan defaults to 5000ms", '${app.seat-hold.expiry-scan-ms:5000}' in expiry_job)
check("Expiry batch defaults to 200", '${app.seat-hold.expiry-batch-size:200}' in expiry_job)
check("Expiry batch is bounded", "Math.max(10,Math.min(batchSize,200))" in expiry_job)
check("Expiry publishes HOLD_EXPIRED realtime event", 'events.publish(showtimeId,"HOLD_EXPIRED",seatIds)' in expiry_job)
check("Expiry groups changed seats per showtime", "computeIfAbsent(row.getShowtimeId()" in expiry_job)

# Checkout / final booking invariant
check("Booking create is transactional", "@Transactional\n    public BookingCreateResult create" in booking_service)
check("Booking create requires durable hold ownership", "holds.ownsAll(showtime.getId(), seatIds, user.getId())" in booking_service)
check("Checkout still rechecks reserved booking seats", "bookingSeats.findReservedSeatIds(showtime.getId())" in booking_service)
check("Booking insert still catches DB seat race", "DataIntegrityViolationException" in booking_service)
check("Booking service documents final DB race protection", "unique index" in booking_service.lower())
check("Existing final booking-seat invariant remains", "uq_showtime_seat_active" in booking_seat_repo or "uq_showtime_seat_active" in booking_service)
check("Booking converts hold inside checkout transaction", "holds.convertToBooking(showtime.getId(), seatIds, user.getId(), b.getId())" in booking_service)
check("Booking no longer releases durable hold on success", "holds.release(showtime.getId(), seatIds, user.getId())" not in booking_service)
check("BOOKED_PENDING realtime event stays after commit", 'events.publish(showtime.getId(),"BOOKED_PENDING",seatIds)' in booking_service)
check("Idempotency-Key request header remains", 'Idempotency-Key' in booking_controller)
check("Booking service still normalizes idempotency key", "normalizeIdempotencyKey" in booking_service)
check("Booking service still detects idempotency fingerprint conflict", "requestFingerprint" in booking_service and "đã được dùng cho một nội dung đặt vé khác" in booking_service)

# Seat API contract
check("Seat map exposes holdAuthority", "String holdAuthority" in seat_dtos)
check("Hold response exposes holdToken", "UUID holdToken" in seat_dtos)
check("Hold response exposes durable authority", "String authority" in seat_dtos)
check("Seat map returns V66 authority", "SeatHoldService.AUTHORITY" in seat_service)
check("Hold endpoint delegates to durable acquire", "SeatHoldService.AcquireResult acquired = holds.acquire" in seat_service)
check("Hold endpoint returns durable hold token", "acquired.holdToken()" in seat_service)
check("Hold endpoint returns authority", "acquired.authority()" in seat_service)
check("Hold still publishes HELD realtime event", 'events.publish(showtimeId,"HELD",unique)' in seat_service)
check("Release still publishes RELEASED realtime event", 'events.publish(showtimeId,"RELEASED",seatIds)' in seat_service)

# Realtime degradation safety
check("SeatEventPublisher has logger", "LoggerFactory.getLogger" in events)
check("SeatEventPublisher catches Redis runtime failure", "catch(RuntimeException ex)" in events)
check("SeatEventPublisher logs degraded publish", "seat_event_publish_degraded" in events)
check("Realtime Redis failure does not rethrow", "throw ex" not in events)

# Admin observability/operations
check("Admin API namespace is /api/admin/seat-operations", '@RequestMapping("/api/admin/seat-operations")' in ops_controller)
check("Admin summary endpoint exists", '@GetMapping("/summary")' in ops_controller)
check("Admin hold history endpoint exists", '@GetMapping("/holds")' in ops_controller)
check("Admin reconcile endpoint exists", '@PostMapping("/reconcile")' in ops_controller)
check("Global /api/admin ADMIN guard remains", '.requestMatchers("/api/admin/**").hasRole("ADMIN")' in security)
check("Admin summary exposes Redis status", "boolean redisAvailable" in ops_dtos)
check("Admin summary exposes active holds", "long activeHolds" in ops_dtos)
check("Admin summary exposes expiring holds", "long expiringWithin60Seconds" in ops_dtos)
check("Admin summary exposes 24h conflicts", "long conflictsLast24Hours" in ops_dtos)
check("Admin hold item exposes user email", "String userEmail" in ops_dtos)
check("Admin hold item exposes converted booking", "UUID convertedBookingId" in ops_dtos)
check("Admin service uses V66 strategy", 'STRATEGY_VERSION="V66-BOOKING-CONSISTENCY-4"' in ops_service)
check("Admin summary counts live HELD rows", "state='HELD'" in ops_service and "expires_at>?" in ops_service)
check("Admin summary counts seat-hold conflicts from audit", "SEAT_HOLD_CONFLICT" in ops_service)
check("Admin service exposes reconcile", "public ReconcileResponse reconcile()" in ops_service)
check("Admin reconcile delegates to hold service", "holds.reconcile()" in ops_service)
check("Admin dashboard has V66 tile", "Seat Operations V66" in admin)
check("Admin dashboard tile has stable test id", 'data-testid="admin-seat-operations-v66"' in admin)
check("Admin dashboard tile links seat operations", 'href="/admin/seat-operations"' in admin)
check("Admin UI has V66 branding", "V66 · BOOKING CONSISTENCY & SEAT LOCKING 4.0" in ops_ui)
check("Admin UI shows durable authority", 'data-testid="seat-hold-authority-v66"' in ops_ui)
check("Admin UI shows Redis mirror status", 'data-testid="seat-redis-v66"' in ops_ui)
check("Admin UI shows active durable holds", 'data-testid="active-seat-holds-v66"' in ops_ui)
check("Admin UI shows lifecycle history", 'data-testid="seat-hold-history-v66"' in ops_ui)
check("Admin UI has reconcile action", 'data-testid="seat-reconcile-v66"' in ops_ui)
check("Admin UI refreshes automatically", "setInterval" in ops_ui and ("5_000" in ops_ui or "5000" in ops_ui))

# Customer booking UI
check("Frontend SeatMap type exposes holdAuthority", "holdAuthority?:" in frontend_types and "POSTGRESQL_WITH_REDIS_MIRROR" in frontend_types)
check("Frontend defines SeatHoldItemV66", "SeatHoldItemV66" in frontend_types)
check("Frontend defines SeatConsistencySummaryV66", "SeatConsistencySummaryV66" in frontend_types)
check("Frontend defines SeatReconcileResultV66", "SeatReconcileResultV66" in frontend_types)
check("Booking page accepts holdToken", "holdToken?:string" in booking_ui or "holdToken?: string" in booking_ui)
check("Booking page accepts authority", "authority?:string" in booking_ui or "authority?: string" in booking_ui)
check("Booking page has authority test id", 'data-testid="seat-hold-authority-v66"' in booking_ui)
check("Booking page explains PostgreSQL durable expiry", "PostgreSQL" in booking_ui)
check("Booking page explains Redis mirror", "Redis" in booking_ui and "mirror" in booking_ui.lower())
check("Booking page labels multi-replica protection", "chống double-booking đa replica" in booking_ui)

# E2E race proof
check("V66 E2E creates two independent users", "newUser(browser" in e2e and "second=await newUser" in e2e)
check("V66 E2E races hold calls concurrently", "Promise.all([" in e2e)
check("V66 E2E targets same seat pair", "pair.seatIds" in e2e)
check("V66 E2E expects exactly one 200 and one 409", "toEqual([200,409])" in e2e)
check("V66 E2E verifies durable authority", 'toBe("POSTGRESQL_WITH_REDIS_MIRROR")' in e2e)
check("V66 E2E verifies UUID hold token", "holdToken" in e2e and "36" in e2e)
check("V66 E2E verifies booking authority UI", 'getByTestId("seat-hold-authority-v66")' in e2e)
check("V66 E2E verifies Admin tile", 'getByTestId("admin-seat-operations-v66")' in e2e)
check("V66 E2E verifies Admin operations page", r"admin\/seat-operations" in e2e or "/admin/seat-operations" in e2e)
playwright_config = text("frontend/playwright.config.ts")
check("Playwright config reads local project env", 'parseEnvFile' in playwright_config and '../.env' in playwright_config and '.env' in playwright_config)
check("Playwright config maps ADMIN_EMAIL to E2E admin", 'process.env.E2E_ADMIN_EMAIL ||=' in playwright_config and 'localEnv.ADMIN_EMAIL' in playwright_config)
check("Playwright config maps ADMIN_PASSWORD to E2E admin", 'process.env.E2E_ADMIN_PASSWORD ||=' in playwright_config and 'localEnv.ADMIN_PASSWORD' in playwright_config)
check("Explicit E2E admin credentials keep priority", 'process.env.E2E_ADMIN_EMAIL ||=' in playwright_config and 'process.env.E2E_ADMIN_PASSWORD ||=' in playwright_config)
check("Playwright config has safe compose fallback", '"admin@cine.local"' in playwright_config and '"Admin@123"' in playwright_config)
check("V66 E2E consumes resolved E2E admin email", 'process.env.E2E_ADMIN_EMAIL||"admin@cine.local"' in e2e)
check("V66 E2E consumes resolved E2E admin password", 'process.env.E2E_ADMIN_PASSWORD||"Admin@123"' in e2e)
check("V66 E2E no longer uses stale V29 admin fallback", "admin-v29@cine.local" not in e2e and "V29SmokeOnly-ChangeMe" not in e2e)
check("V66 E2E reports explicit admin login failure context", "Admin login did not reach /admin" in e2e)
check("V66 E2E verifies active hold visibility", 'getByTestId("active-seat-holds-v66")' in e2e)
check("V66 E2E releases winning hold", 'method:"DELETE"' in e2e and "holds`" in e2e)

# Configuration
check("Application config has expiry scan setting", "expiry-scan-ms: ${SEAT_HOLD_EXPIRY_SCAN_MS:5000}" in app_yml)
check("Application config has expiry batch setting", "expiry-batch-size: ${SEAT_HOLD_EXPIRY_BATCH_SIZE:200}" in app_yml)
check(".env.example exposes expiry scan", "SEAT_HOLD_EXPIRY_SCAN_MS=5000" in env_example)
check(".env.example exposes expiry batch", "SEAT_HOLD_EXPIRY_BATCH_SIZE=200" in env_example)
check("Compose passes expiry scan to backend", "SEAT_HOLD_EXPIRY_SCAN_MS" in compose)
check("Compose passes expiry batch to backend", "SEAT_HOLD_EXPIRY_BATCH_SIZE" in compose)
check("V65 local HTTPS override remains documented", "docker-compose.https.yml" in readme)
check("V65 HTTPS verifier remains present", bool(https_verify))
check("Manual check-in V3 verifier remains present", bool(manual_checkin_verify))

# DB integration / data policy
check("Integration test expects Flyway >=66", "isGreaterThanOrEqualTo(66)" in itest or "isGreaterThanOrEqualTo(67)" in itest)
check("Integration test expects at least 58 public tables", "publicTables).isGreaterThanOrEqualTo(58)" in itest)
check("Integration test verifies seat_hold table", "seat_hold" in itest)
check("Integration test verifies active unique hold index", "uq_seat_hold_active" in itest)
check("V66 migration has no INSERT seed rows", "INSERT INTO seat_hold" not in migration.upper())
check("Realistic seed SQL does not create fake seat_hold rows", "insert into seat_hold" not in seed_sql.lower())
check("README documents 58 public tables", "58 public tables" in readme)
check("README preserves 57 seeded core-table policy", "57" in readme and "seat_hold" in readme)
check("README documents no fake V66 holds", "không seed" in readme.lower() and "seat_hold" in readme)

# V66 Admin runtime hotfix - JdbcTemplate/PgJDBC timestamp binding + honest UI state
check("Admin summary converts raw Instant JDBC args", "value instanceof Instant instant?Timestamp.from(instant):value" in ops_service)
check("Admin summary imports SQL Timestamp", "import java.sql.Timestamp;" in ops_service)
check("Admin summary count normalizes every JDBC arg", "Arrays.stream(args).map(this::jdbcArg).toArray()" in ops_service)
check("Admin UI exposes stable summary error test id", 'data-testid="seat-operations-error-v66"' in ops_ui)
check("Admin Redis status is UNKNOWN before summary loads", 'summary===null?"◌ UNKNOWN"' in ops_ui)
check("Admin UI does not falsely label missing summary as Redis degraded", 'Chưa tải được summary nên chưa thể kết luận trạng thái Redis.' in ops_ui)
check("V66 E2E requires Admin summary to load without error", 'getByTestId("seat-operations-error-v66")).toHaveCount(0)' in e2e)
check("V66 E2E rejects placeholder summary metrics", 'getByTestId("seat-consistency-summary-v66")).not.toContainText("—")' in e2e)

# Release / CI wiring
check("CI runs V66 verifier", "verify_v66_booking_consistency_seat_locking.py" in ci)
check("RC workflow runs V66 verifier", "verify_v66_booking_consistency_seat_locking.py" in rc)
check("Stable release workflow runs V66 verifier", "verify_v66_booking_consistency_seat_locking.py" in release)
check("RC default is v66.0.0-rc.1 or later", "v66.0.0-rc.1" in rc or "v67.0.0-rc.1" in rc)
check("Stable default is 66.0.0 or later", "66.0.0" in release or "67.0.0" in release)
check("RC compose namespace is V66 or later", "cinebooking_v66_rc_" in rc or "cinebooking_v67_rc_" in rc)
check("Release compose namespace is V66 or later", "cinebooking_v66_release_" in release or "cinebooking_v67_release_" in release)
check("Makefile exposes verify-v66", "verify-v66:" in make)
check("Makefile chains V65 HTTPS gate", "verify_v65_local_https.py" in make)
check("Makefile chains V66 verifier", "verify_v66_booking_consistency_seat_locking.py" in make)
check("Diagnose V66 runs V66 verifier", "verify_v66_booking_consistency_seat_locking.py" in diagnose)
check("Diagnose V66 states Flyway V66", "Flyway V66" in diagnose)
check("Diagnose V66 states 58 public tables", "58 public tables" in diagnose)
check("V65 verifier is forward compatible with >=65 releases", ">=65" in v65verify or "65" in v65verify)

# README runbook / rollout
check("README documents PostgreSQL authority model", "POSTGRESQL_WITH_REDIS_MIRROR" in readme)
check("README documents uq_seat_hold_active", "uq_seat_hold_active" in readme)
check("README documents existing booking-seat final invariant", "uq_showtime_seat_active" in readme)
check("README documents seat-hold TTL", "SEAT_HOLD_TTL_SECONDS" in readme)
check("README documents expiry scan", "SEAT_HOLD_EXPIRY_SCAN_MS" in readme)
check("README documents expiry batch", "SEAT_HOLD_EXPIRY_BATCH_SIZE" in readme)
check("README documents Admin V66 route", "/admin/seat-operations" in readme)
check("README documents V66 E2E", "booking-consistency-seat-locking-v66.spec.ts" in readme)
check("README documents V66 RC tag", "v66.0.0-rc.1" in readme)
check("README documents V66 stable tag", "v66.0.0" in readme)

passed = sum(1 for _, ok in checks if ok)
total = len(checks)
print(f"\nV66 verification: {passed}/{total} checks passed")
if passed != total:
    failed = [name for name, ok in checks if not ok]
    print("Failed checks:")
    for name in failed:
        print(f" - {name}")
    sys.exit(1)
