from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel):
    p=ROOT/rel
    return p.read_text(encoding='utf-8') if p.exists() else ''
def check(name,cond):
    ok=bool(cond);checks.append((name,ok));print(f"[ {'OK' if ok else 'FAIL'} ] {name}")

service=text('backend/src/main/java/com/cinebooking/retention/RetentionIntelligenceService.java')
dtos=text('backend/src/main/java/com/cinebooking/retention/RetentionIntelligenceDtos.java')
controller=text('backend/src/main/java/com/cinebooking/retention/AdminRetentionIntelligenceController.java')
security=text('backend/src/main/java/com/cinebooking/config/SecurityConfig.java')
page=text('frontend/app/admin/retention/page.tsx')
types=text('frontend/lib/types.ts')
header=text('frontend/components/Header.tsx')
admin=text('frontend/app/admin/page.tsx')
e2e=text('frontend/e2e/customer-retention-v55.spec.ts')
ci=text('.github/workflows/ci.yml')
rc=text('.github/workflows/release-candidate.yml')
release=text('.github/workflows/release.yml')
make=text('Makefile')
diagnose=text('tools/diagnose-v55.ps1')
readme=text('README.md')
integration=text('backend/src/test/java/com/cinebooking/integration/CineBookingIntegrationIT.java')
seed_verify=text('tools/verify_seed_demo_57.py')
v54verify=text('tools/verify_v54_performance_benchmarking.py')

check('V55 is a no-schema retention release', not (ROOT/'backend/src/main/resources/db/migration/V55__customer_retention_cohort_intelligence_3.sql').exists())
check('V52 remains latest Flyway migration under V55', (ROOT/'backend/src/main/resources/db/migration/V52__pwa_mobile_experience_3.sql').exists() and 'assertThat(latest).isEqualTo("52")' in integration)
check('V55 keeps the 57-table data contract', 'Final verification enumerates all 57 pgAdmin tables' in seed_verify and 'pwa_device' in seed_verify)
check('V54 verifier remains forward-compatible with V55 source', 'current-or-newer source' in v54verify and 'int(current_match.group(1))>=54' in v54verify)
check('Retention DTOs expose summary lifecycle cohort and daily contracts', all(x in dtos for x in ['RetentionScorecard','LifecycleSegment','CohortRetention','DailyRetention','repeatCustomerRate','revenuePerCustomer']))
check('Retention controller exposes cinema and scorecard endpoints', '@RequestMapping("/api/admin/retention")' in controller and '@GetMapping("/cinemas")' in controller and '@GetMapping("/scorecard")' in controller)
check('Security allows Manager/Admin into V55 before generic admin rule', '.requestMatchers("/api/admin/retention/**").hasAnyRole("MANAGER","ADMIN")' in security and security.index('/api/admin/retention/**') < security.index('/api/admin/**'))
check('V55 service restricts access to Manager/Admin', 'actor.getRole() != Role.ADMIN && actor.getRole() != Role.MANAGER' in service and 'Customer Retention Intelligence' in service)
check('Manager retention scope is locked to assigned cinema', 'Manager chỉ xem Customer Retention Intelligence của rạp mình' in service and 'managerCinema(actor)' in service)
check('Admin can use all-cinema or explicit cinema retention scope', 'actor.getRole() == Role.ADMIN' in service and 'requestedCinemaId' in service and 'Toàn hệ thống' in service)
check('V55 only supports deterministic 30 and 90 day windows', 'ALLOWED_PERIOD_DAYS = List.of(30, 90)' in service and 'validatePeriod(periodDays)' in service)
check('V55 uses Asia Ho Chi Minh business dates', 'ZoneId.of("Asia/Ho_Chi_Minh")' in service and 'LocalDate.now(BUSINESS_ZONE)' in service)
check('Retention excludes operator accounts from customer metrics', "u.role='USER'" in service and service.count("u.role='USER'") >= 4)
check('Retention attributes customer activity to original purchaser', 'b.purchaser_user_id customer_id' in service and 'purchaser_user_id' in page)
check('Retention customer activity uses confirmed bookings only', "b.status='CONFIRMED'" in service and 'b.confirmed_at is not null' in service)
check('V55 revenue uses successful payments only', "p.status='SUCCESS'" in service and "p.paid_at at time zone 'Asia/Ho_Chi_Minh'" in service)
check('Active customers are distinct purchaser rows in the selected window', 'period as (' in service and 'group by customer_id' in service and 'count(*) active_customers' in service)
check('New customers derive from first confirmed booking date', 'min(booking_date) first_date' in service and 'h.first_date>=?' in service)
check('Returning customers require a first purchase before the current window', 'h.first_date<?' in service and 'returning_customers' in service)
check('Repeat customers require at least two historical confirmed bookings', 'h.lifetime_bookings>=2' in service and 'repeat_customers' in service)
check('Repeat rate is derived and divide-by-zero safe', 'percentage(summary.repeatCustomers(), summary.activeCustomers())' in service and 'if (denominator <= 0) return 0.0' in service)
check('Revenue per customer and booking frequency are divide-by-zero safe', 'averageMoney(revenue, summary.activeCustomers())' in service and 'averageCount(summary.bookings(), summary.activeCustomers())' in service)
check('Lifecycle segmentation exposes five mutually described rule buckets', all(x in service for x in ['NEW_30D','ACTIVE_REPEAT','AT_RISK','DORMANT','LAPSED']) and all(x in page for x in ['không phải điểm churn','không phải dự đoán AI']))
check('Lifecycle thresholds use first and last confirmed booking dates', 'min(booking_date) first_date,max(booking_date) last_date' in service and 'activeCutoff' in service and 'riskCutoff' in service and 'dormantCutoff' in service)
check('V55 cohort retention requires a second booking within 30 days', 'c2.booking_date>h.first_date' in service and 'c2.booking_date<=h.first_date+30' in service)
check('V55 only exposes cohorts with a complete 30-day observation window', 'eligibleThrough = today.minusDays(30)' in service and 'cohortToExclusive = eligibleThrough.plusDays(1)' in service)
check('Cohorts group acquisition by first-booking month', "date_trunc('month',h.first_date)::date as cohort_month" in service and 'acquired_customers' in service)
check('Daily retention classifies new and returning customers from first dates', 'f.first_date=c.booking_date' in service and 'f.first_date<c.booking_date' in service)
check('Daily revenue SQL uses safe metric_date alias', 'as metric_date' in service and 'getObject("metric_date", LocalDate.class)' in service and not re.search(r'\)\s+day[, ]',service,re.I))
check('Daily series zero-fills missing calendar dates', 'for (LocalDate day = from; day.isBefore(toExclusive); day = day.plusDays(1))' in service and 'getOrDefault(day' in service)
check('V55 retention service is read-only', 'jdbc.update(' not in service and 'jdbc.batchUpdate(' not in service and 'jdbc.execute(' not in service)
check('V55 uses unambiguous two-argument RowMapper callbacks', service.count('(rs, rowNum) ->') >= 5 and '(RowCallbackHandler)' not in service)
check('Frontend V55 page exposes retention source marker', 'Customer Retention & Cohort Intelligence · V55' in page and 'retention-intelligence-v55' in page)
check('Frontend supports Admin cinema filter and Manager fixed branch scope', 'retention-cinema-filter-v55' in page and 'profile.role==="MANAGER"' in page and 'me?.role==="ADMIN"' in page)
check('Frontend supports 30 and 90 day retention windows', 'retention-period-v55' in page and '<option value={30}>30 ngày</option>' in page and '<option value={90}>90 ngày</option>' in page)
check('Frontend renders summary lifecycle cohorts and daily series', all(x in page for x in ['retention-summary-v55','retention-lifecycle-v55','retention-cohorts-v55','retention-daily-v55']))
check('Frontend documents honest retention semantics', all(x in page for x in ['booking CONFIRMED','payment SUCCESS','không phải điểm churn','transfer vé không biến người nhận']))
check('Frontend types include V55 retention contracts', all(x in types for x in ['RetentionCinemaV55','RetentionLifecycleV55','RetentionCohortV55','RetentionDailyV55','RetentionScorecardV55']))
check('Header exposes V55 Retention to Manager/Admin menus', header.count('/admin/retention') >= 4)
check('Admin dashboard links V55 Retention', '/admin/retention' in admin and 'Retention V55' in admin)
check('V55 Playwright covers summary lifecycle cohort period and cinema filters', all(x in e2e for x in ['V55 admin reviews honest customer retention cohorts','retention-summary-v55','retention-lifecycle-v55','retention-cohorts-v55','retention-period-v55','retention-cinema-filter-v55']))
ci_match=re.search(r'name:\s*V26-V(\d+) source regression',ci)
check('Main CI extends source regression through V55', bool(ci_match) and int(ci_match.group(1))>=55 and 'verify_v55_customer_retention.py' in ci)
rc_versions=[int(v) for v in re.findall(r'default: "v(\d+)\.0\.0-rc\.1"',rc)]
check('Standalone RC defaults to V55-or-newer and runs V55 gate', bool(rc_versions) and max(rc_versions)>=55 and 'verify_v55_customer_retention.py' in rc)
release_versions=[int(v) for v in re.findall(r'default: "(\d+)\.0\.0"',release)]
check('Stable release defaults to V55-or-newer and runs V55 gate', bool(release_versions) and max(release_versions)>=55 and 'verify_v55_customer_retention.py' in release)
check('Makefile exposes V55 verify diagnose and unchanged 57-table lifecycle', all(x in make for x in ['verify-v55:','diagnose-v55:','verify-seed-demo-v55:','check-seed-demo-v55:','verify-reference-v55:','seed-reference-v55:']))
check('V55 diagnostics chain V54 V55 and 57-table verifier', all(x in diagnose for x in ['verify_v54_performance_benchmarking.py','verify_v55_customer_retention.py','verify_seed_demo_57.py','V55 source diagnostics passed.']))
current_match=re.search(r'^# CineBooking Pro V(\d+)',readme,re.M)
check('README identifies V55 Customer Retention release', bool(current_match) and int(current_match.group(1))>=55 and 'V55 - Customer Retention & Cohort Intelligence 3.0' in readme)
check('README states V55 is read-only no-schema and keeps 57 public tables', 'V55 không tạo migration Flyway mới' in readme and '57 public tables' in readme and 'customer retention analytics read-only' in readme)
check('README documents purchaser attribution complete cohort window and no fake churn score', all(x in readme for x in ['booking.purchaser_user_id','đủ 30 ngày quan sát','không dùng churn score tùy ý']))
check('README release lifecycle defaults to v55.0.0-rc.1 and v55.0.0', 'v55.0.0-rc.1' in readme and 'v55.0.0' in readme)

passed=sum(ok for _,ok in checks)
print(f"\nV55 verification: {passed}/{len(checks)} checks passed")
if passed != len(checks):
    print("\nFailed checks:")
    for name,ok in checks:
        if not ok: print(f" - {name}")
raise SystemExit(0 if passed==len(checks) else 1)
