"use client";
import Link from "next/link";
import { use, useEffect, useMemo, useState } from "react";
import { api, currency } from "@/lib/api";
import { getAuth } from "@/lib/auth";
import type { AdminSeat, Auditorium } from "@/lib/types";

type SeatKind="STANDARD"|"VIP"|"COUPLE"|"ACCESSIBLE"|"BLOCKED";
const kinds:SeatKind[]=["STANDARD","VIP","COUPLE","ACCESSIBLE","BLOCKED"];
const price:Record<SeatKind,number>={STANDARD:0,VIP:20000,COUPLE:50000,ACCESSIBLE:0,BLOCKED:0};
const cls:Record<SeatKind,string>={STANDARD:"border-emerald-700 bg-emerald-950 text-emerald-200",VIP:"border-violet-700 bg-violet-950 text-violet-200",COUPLE:"border-pink-700 bg-pink-950 text-pink-200",ACCESSIBLE:"border-cyan-700 bg-cyan-950 text-cyan-200",BLOCKED:"border-slate-700 bg-slate-900 text-slate-600"};
function rowName(i:number){let n=i+1,s="";while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s;}
export default function SeatLayoutPage({params}:{params:Promise<{auditoriumId:string}>}){
 const {auditoriumId}=use(params);const [aud,setAud]=useState<Auditorium|null>(null);const [rows,setRows]=useState(8);const [cols,setCols]=useState(10);const [grid,setGrid]=useState<Record<string,SeatKind>>({});const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{const a=getAuth();if(!a||a.role!=="ADMIN"){location.href="/login?next=/admin";return;}(async()=>{try{const [as,seats]=await Promise.all([api<Auditorium[]>("/admin/auditoriums"),api<AdminSeat[]>(`/admin/seats?auditoriumId=${auditoriumId}`)]);setAud(as.find(x=>x.id===auditoriumId)||null);let r=Math.max(5,...seats.map(s=>s.rowLabel.charCodeAt(0)-64));let c=Math.max(8,...seats.map(s=>s.seatNumber));setRows(Math.min(20,r));setCols(Math.min(30,c));const g:Record<string,SeatKind>={};seats.forEach(s=>g[`${s.rowLabel}-${s.seatNumber}`]=(s.seatType as SeatKind));setGrid(g);}catch(e){setMsg((e as Error).message)}})();},[auditoriumId]);
 const cells=useMemo(()=>Array.from({length:rows},(_,r)=>({row:rowName(r),seats:Array.from({length:cols},(_,i)=>i+1)})),[rows,cols]);
 function kind(row:string,num:number):SeatKind{return grid[`${row}-${num}`]||"STANDARD"} function cycle(row:string,num:number){const k=kind(row,num);setGrid(v=>({...v,[`${row}-${num}`]:kinds[(kinds.indexOf(k)+1)%kinds.length]}));}
 function applyRow(row:string,k:SeatKind){setGrid(v=>{const n={...v};for(let i=1;i<=cols;i++)n[`${row}-${i}`]=k;return n})}
 async function save(){setBusy(true);setMsg("");try{const seats=cells.flatMap(r=>r.seats.map(n=>{const k=kind(r.row,n);return {rowLabel:r.row,seatNumber:n,seatType:k,priceModifier:price[k]}}));await api(`/admin/auditoriums/${auditoriumId}/seat-layout`,{method:"PUT",body:JSON.stringify({seats})});setMsg(`Đã lưu ${seats.length} vị trí ghế.`);}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">SEAT LAYOUT EDITOR</p><h1 className="text-3xl font-bold">{aud?.name||"Phòng chiếu"}</h1><p className="mt-2 text-slate-400">Click từng ghế để đổi loại. Ghế BLOCKED tạo lối đi/khoảng trống và không thể đặt.</p></div><Link className="btn btn-secondary" href="/admin">← Admin</Link></div>
 <section className="card p-5"><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Số hàng<input className="input mt-1 !w-28" type="number" min={1} max={20} value={rows} onChange={e=>setRows(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/></label><label className="text-sm">Ghế / hàng<input className="input mt-1 !w-28" type="number" min={1} max={30} value={cols} onChange={e=>setCols(Math.max(1,Math.min(30,Number(e.target.value)||1)))}/></label><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?"Đang lưu...":"Lưu sơ đồ"}</button></div>{msg&&<div className="mt-4 rounded-xl bg-slate-900 p-3 text-sm">{msg}</div>}</section>
 <section className="card p-5 md:p-7"><div className="mx-auto mb-8 max-w-3xl"><div className="h-2 rounded-full bg-gradient-to-r from-transparent via-slate-100 to-transparent"/><div className="mt-2 text-center text-xs tracking-[.4em] text-slate-500">MÀN HÌNH</div></div><div className="overflow-x-auto"><div className="mx-auto w-max space-y-2 px-4">{cells.map(r=><div key={r.row} className="flex items-center gap-2"><button title="Đổi cả hàng thành STANDARD" className="w-8 text-xs font-black text-slate-500" onClick={()=>applyRow(r.row,"STANDARD")}>{r.row}</button>{r.seats.map(n=>{const k=kind(r.row,n);return <button key={n} title={`${r.row}${n} · ${k} · +${currency(price[k])}`} onClick={()=>cycle(r.row,n)} className={`h-10 w-11 rounded-t-xl rounded-b-md border text-xs font-bold ${cls[k]}`}>{k==="BLOCKED"?"×":n}</button>})}<span className="w-8 text-xs font-black text-slate-500">{r.row}</span></div>)}</div></div><div className="mt-7 flex flex-wrap gap-3 text-xs">{kinds.map(k=><span key={k} className={`rounded-lg border px-2 py-1 ${cls[k]}`}>{k} {price[k]>0?`+${currency(price[k])}`:""}</span>)}</div></section>
 </div>}
