const LABELS_VI: Record<string, string> = {
  ADMIN: "Quản trị viên",
  MANAGER: "Quản lý",
  STAFF: "Nhân viên",
  USER: "Khách hàng",

  LOW: "Thấp",
  MEDIUM: "Trung bình",
  HIGH: "Cao",
  CRITICAL: "Nghiêm trọng",

  OPEN: "Đang mở",
  CLOSED: "Đã đóng",
  IN_PROGRESS: "Đang xử lý",
  BLOCKED: "Đang bị chặn",
  RESOLVED: "Đã hoàn tất",
  CANCELLED: "Đã hủy",
  CANCELED: "Đã hủy",
  OVERDUE: "Quá hạn",

  OPERATIONAL: "Hoạt động bình thường",
  DEGRADED: "Hoạt động suy giảm",
  OUT_OF_SERVICE: "Ngừng hoạt động",
  MAINTENANCE: "Đang bảo trì",

  PROJECTOR: "Máy chiếu",
  AUDIO: "Âm thanh",
  HVAC: "Điều hòa & thông gió",
  SCREEN: "Màn chiếu",
  POS: "Điểm bán hàng",
  NETWORK: "Mạng",
  POWER: "Nguồn điện",
  SAFETY: "An toàn",
  OTHER: "Khác",

  ACTIVE: "Đang hoạt động",
  INACTIVE: "Ngừng hoạt động",
  ON_LEAVE: "Nghỉ phép",
  ENABLED: "Đã bật",
  DISABLED: "Đã tắt",

  PENDING: "Đang chờ",
  SUCCESS: "Thành công",
  FAILED: "Thất bại",
  REVIEW: "Cần xem xét",
  REFUNDED: "Đã hoàn tiền",
  PAID: "Đã thanh toán",
  CONFIRMED: "Đã xác nhận",
  EXPIRED: "Đã hết hạn",
  NOTIFIED: "Đã thông báo",
  CREATED: "Đã tạo",
  APPROVED: "Đã duyệt",
  REJECTED: "Đã từ chối",

  MANUAL: "Thủ công",
  BATCH: "Theo lô",
  SMART: "Thông minh",
  RUNNING: "Đang chạy",
  COMPLETED: "Đã hoàn thành",
  WARNING: "Cảnh báo",
  WARN: "Cảnh báo",
  HEALTHY: "Bình thường",
  UNHEALTHY: "Bất thường",
  UP: "Đang hoạt động",
  DOWN: "Ngừng hoạt động",

  STATUS_CHANGED: "Thay đổi trạng thái",
  CREATED_WORK_ORDER: "Tạo phiếu bảo trì",
  UPDATED: "Đã cập nhật",
  DELETED: "Đã xóa",

  FAMILIAR: "Bám gu",
  DISCOVERY: "Khám phá",
  BALANCED: "Cân bằng",

  NEW: "Mới",
  ACKNOWLEDGED: "Đã xác nhận",
  SUPPRESSED: "Đã bỏ qua",
  UNKNOWN: "Chưa xác định",

  ALL: "Tất cả",
  REFUND_REQUESTED: "Đang yêu cầu hoàn tiền",
  SCHEDULED: "Đã lên lịch",
  CHECKED_IN: "Đã soát vé",
  ACTION_REQUIRED: "Cần xử lý",
  ESCALATED: "Đã nâng mức",
  CLEARED: "Đã làm rõ",
  CHALLENGE: "Yêu cầu xác minh thêm",
  BLOCK_RECOMMENDED: "Đề nghị chặn",
  UNREVIEWED: "Chưa đánh giá",
  PASS: "Đạt",
  FAIL: "Không đạt",
  NO_DATA: "Chưa có dữ liệu",
  READY: "Sẵn sàng",
  PARTIAL: "Một phần",
  VALID: "Hợp lệ",
  INVALID: "Không hợp lệ",
  RECEIVED: "Đã nhận",
  ORPHANED: "Mồ côi",
  RECOVERY_PENDING: "Chờ khôi phục",
  RECOVERED: "Đã khôi phục",
  DEAD_LETTER: "Hàng đợi lỗi",
  HELD: "Đang giữ",
  CONVERTED: "Đã chuyển đổi",
  RELEASED: "Đã nhả",
  AVAILABLE: "Sẵn sàng",
  SETTLED: "Đã quyết toán",

  BOOKING: "Đặt vé",
  PAYMENT: "Thanh toán",
  REFUND: "Hoàn tiền",
  TICKET: "Vé",
  CINEMA_EXPERIENCE: "Trải nghiệm rạp",
  TECHNICAL: "Kỹ thuật",
  INCIDENT: "Sự cố",
  ACCESS: "Truy cập",
  ACCOUNT: "Tài khoản",
  SECURITY: "Bảo mật",
  PROMOTION: "Ưu đãi",
  GENERAL: "Chung",

  WATCH: "Cần theo dõi",
  GOOD: "Tốt",
  GREAT: "Rất tốt",
  BEST: "Tốt nhất",
  STANDARD: "Tiêu chuẩn",
  VIP: "VIP",
  COUPLE: "Ghế đôi",
  ACCESSIBLE: "Hỗ trợ tiếp cận",
  PERCENT: "Phần trăm",
  FIXED: "Số tiền cố định",
  REVIEW_REQUIRED: "Cần xem xét",
  ON_TIME: "Đúng giờ",
  LATE: "Đi trễ",
  EARLY_LEAVE: "Về sớm",
  ABSENT: "Vắng mặt",
  INFO: "Thông tin",
  EQUIPMENT: "Thiết bị",
  SUPPORT: "Hỗ trợ",
  INVENTORY: "Kho",

  VERIFIED: "Đã xác minh",
  ROTATED: "Đã xoay vòng",
  REVOKED: "Đã thu hồi",
  ERASURE: "Xóa dữ liệu",
  RECTIFICATION: "Chỉnh sửa dữ liệu",
  WAITING_CUSTOMER: "Chờ khách hàng",
  VACATION: "Nghỉ phép",
  SICK: "Nghỉ bệnh",
  PERSONAL: "Việc riêng",
  EXPORT: "Xuất dữ liệu",
  ARCHIVE: "Lưu trữ",
  DELETE: "Xóa",
  ANONYMIZE: "Ẩn danh hóa",
  MATURED: "Đủ thời gian quan sát",
  BACKEND_JAR: "Gói backend JAR",
  FRONTEND_BUNDLE: "Gói giao diện frontend",
  CONTAINER_IMAGE: "Ảnh container",
  DEPENDENCY_INVENTORY: "Danh mục phụ thuộc",
  INTERNAL: "Nội bộ",
  EXTERNAL: "Bên ngoài",

  PAYMENT_CAPTURED: "Ghi nhận thanh toán",
  REFUND_SETTLED: "Ghi nhận hoàn tiền",
  PAYMENT_LEDGER_MISSING: "Thiếu bút toán thanh toán",
  PAYMENT_LEDGER_AMOUNT_MISMATCH: "Sai lệch số tiền thanh toán",
  REFUND_LEDGER_MISSING: "Thiếu bút toán hoàn tiền",
  REFUND_LEDGER_AMOUNT_MISMATCH: "Sai lệch số tiền hoàn tiền",
  CAPTURE_TOTAL_MISMATCH: "Sai lệch tổng thanh toán",
  REFUND_TOTAL_MISMATCH: "Sai lệch tổng hoàn tiền",
  LOYALTY_BALANCE_MISMATCH: "Sai lệch điểm thành viên",
  CLEAN: "Đã đối soát, không sai lệch",
  ISSUES: "Có sai lệch cần xử lý",
  DEBIT: "Nợ",
  CREDIT: "Có",
  DATE: "Ngày",
};

export function viLabel(value: string | null | undefined): string {
  if (value == null || value === "") return "—";
  const normalized = value.trim().toUpperCase();
  return LABELS_VI[normalized] ?? value.replaceAll("_", " ");
}

export const maintenanceCategoryOptions = [
  "PROJECTOR", "AUDIO", "HVAC", "SCREEN", "POS", "NETWORK", "POWER", "SAFETY", "OTHER"
] as const;

export const maintenanceAssetStatusOptions = [
  "OPERATIONAL", "DEGRADED", "OUT_OF_SERVICE", "MAINTENANCE"
] as const;

export const maintenancePriorityOptions = ["LOW", "MEDIUM", "HIGH", "CRITICAL"] as const;
